package model

type DeliveryRequest struct {
	ReasonConsultation       string `json:"-"`
	ReferenceType            string `json:"-"`
	DeliveryDocument         string `json:"-"`
	DeliveryPosition         string `json:"-"`
	DispatchPoint            string `json:"-"`
	PurchasingDocumentNumber string `json:"-"`
	DateStart                string `json:"-"`
	DateEnd                  string `json:"-"`
	MaterialDescription      string `json:"-"`
	MaterialNumber           string `json:"-"`
	DestinationCenter        string `json:"-"`
}

type DeliveryResponse struct {
	HeaderDeliveries   HeaderDeliveries
	PositionDeliveries PositionDeliveries
}

type HeaderDeliveries []HeaderDelivery
type PositionDeliveries []PositionDelivery

type HeaderDelivery struct {
	Principal                            string  `json:"principal"`
	Delivery                             string  `json:"delivery"`
	Author                               string  `json:"author"`
	Hour                                 string  `json:"hour"`
	Created                              string  `json:"created"`
	SalesArea                            string  `json:"salesArea"`
	DispatchPoint                        string  `json:"dispatchPoint"`
	ShippingPositionDescription          string  `json:"shippingPositionDescription"`
	SalesOrganization                    string  `json:"salesOrganization"`
	DeliveryClass1                       string  `json:"deliveryClass1"`
	CompleteSupply                       string  `json:"completeSupply"`
	GroupingOrders                       string  `json:"groupingOrders"`
	MerchandiseMovementDate              string  `json:"merchandiseMovementDate"`
	UploadDate                           string  `json:"uploadDate"`
	TransportationPlanningDate           string  `json:"transportationPlanningDate"`
	DateDelivery                         string  `json:"dateDelivery"`
	PickingDAte                          string  `json:"pickingDAte"`
	UnloadingStation                     string  `json:"unloadingStation"`
	Incoterms1                           string  `json:"incoterms1"`
	Incoterms2                           string  `json:"incoterms2"`
	Export                               string  `json:"export"`
	Route                                string  `json:"route"`
	InvoiceLock                          string  `json:"invoiceLock"`
	DeliveryLock                         string  `json:"deliveryLock"`
	SalesDocumentType                    string  `json:"salesDocumentType"`
	FactoryCalendar                      string  `json:"factoryCalendar"`
	TransportationMeansQualificat        string  `json:"transportationMeansQualification"`
	TransportationMeansGroup             string  `json:"transportationMeansGroup"`
	DeliveryPriority                     string  `json:"deliveryPriority"`
	ShippingCondition                    string  `json:"shippingCondition"`
	Customer                             string  `json:"customer"`
	SupplierName                         string  `json:"supplierName"`
	PostalCode                           string  `json:"postalCode"`
	Population                           string  `json:"population"`
	District                             string  `json:"district"`
	Region                               string  `json:"region"`
	Street                               string  `json:"street"`
	Applicant                            string  `json:"applicant"`
	CustomerGroup                        string  `json:"customerGroup"`
	WaitingTimeClass                     float64 `json:"waitingTimeClass"`
	WaitingTimeSurcharge                 float64 `json:"waitingTimeSurcharge"`
	TotalWeigh                           float64 `json:"totalWeigh"`
	NetWeight                            float64 `json:"netWeight"`
	WeightUnit                           string  `json:"weightUnit"`
	Volume                               float64 `json:"volume"`
	VolumeUnit                           string  `json:"volumeUnit"`
	NumberPackages                       string  `json:"numberPackages"`
	LocationAvailable                    string  `json:"locationAvailable"`
	DeliveryTime                         string  `json:"deliveryTime"`
	WeightGroup                          string  `json:"weightGroup"`
	ChargingStation                      string  `json:"chargingStation"`
	TransportGroup                       string  `json:"transportGroup"`
	InvoiceClassDelivery                 string  `json:"invoiceClassDelivery"`
	InvoiceDate                          string  `json:"invoiceDate"`
	BillingDates                         string  `json:"billingDates"`
	Route2                               string  `json:"route2"`
	Current                              string  `json:"current"`
	Scheme                               string  `json:"scheme"`
	DocumentConditionNumber1             string  `json:"documentConditionNumber1"`
	DocumentCurrency                     string  `json:"documentCurrency"`
	SalesOffice                          string  `json:"salesOffice"`
	TimeTratamExpedic                    float64 `json:"timeTratamExpedic"`
	GroupingCriterion                    string  `json:"groupingCriterion"`
	OriginalDocument                     string  `json:"originalDocument"`
	CommunicationNumber                  string  `json:"communicationNumber"`
	StatisticalCurrency                  string  `json:"statisticalCurrency"`
	EstablishedExchangeRate              float64 `json:"establishedExchangeRate"`
	ForeignTradeDataNumber               string  `json:"foreignTradeDataNumber"`
	ModifiedBy                           string  `json:"modifiedBy"`
	CreationDate                         string  `json:"creationDate"`
	WarehouseNumber                      string  `json:"warehouseNumber"`
	DeliveryIdWarehouseNumber            string  `json:"deliveryIdWarehouseNumber"`
	VciSalesOrganization                 string  `json:"vciSalesOrganization"`
	DistributionChannel                  string  `json:"distributionChannel"`
	InternalSector                       string  `json:"internalSector"`
	InternalBillingDateA                 string  `json:"internalBillingDateA"`
	InternalBillingDateO                 string  `json:"internalBillingDateO"`
	InternalBillingDateD                 string  `json:"internalBillingDateD"`
	InternalBillingCustomer              string  `json:"internalBillingCustomer"`
	CreditControlArea                    string  `json:"creditControlArea"`
	CreditAccount                        string  `json:"creditAccount"`
	CustomerCreditGroup                  string  `json:"customerCreditGroup"`
	ResponsibleTeam                      string  `json:"responsibleTeam"`
	RiskClass                            string  `json:"riskClass"`
	Currency                             string  `json:"currency"`
	FreeCreditValue                      float64 `json:"freeCreditValue"`
	Waybill                              string  `json:"waybill"`
	Supplier                             string  `json:"supplier"`
	TypeNif                              string  `json:"typeNif"`
	Nif                                  string  `json:"nif"`
	TypeTransport                        string  `json:"typeTransport"`
	MeansTransportIdentifier             string  `json:"meansTransportIdentifier"`
	ReleaseDate                          string  `json:"releaseDate"`
	NextDate                             string  `json:"nextDate"`
	MerchandiseVoucher                   string  `json:"merchandiseVoucher"`
	DocumentDate                         string  `json:"documentDate"`
	ActualMerchandiseMovementDate        string  `json:"actualMerchandiseMovementDate"`
	TransportBlockageReason              string  `json:"transportBlockageReason"`
	TransportSystemId                    string  `json:"transportSystemId"`
	ExternalDeliveryIdentification       string  `json:"externalDeliveryIdentification"`
	Order1                               string  `json:"order1"`
	SearchScheme                         string  `json:"searchScheme"`
	CorrectiveDelivery                   string  `json:"correctiveDelivery"`
	Scheme2                              string  `json:"scheme2"`
	DocumentConditionNumber2             string  `json:"documentConditionNumber2"`
	NetOrderValue                        float64 `json:"netOrderValue"`
	ItineraryPlan                        string  `json:"itineraryPlan"`
	Enter                                string  `json:"enter"`
	FinancialDocumentNumber              string  `json:"financialDocumentNumber"`
	GuaranteeScheme                      string  `json:"guaranteeScheme"`
	PickingTime                          string  `json:"pickingTime"`
	TransportationPlanningTime           string  `json:"transportationPlanningTime"`
	ChargingTime                         string  `json:"chargingTime"`
	GoodsDepartureTime1                  string  `json:"goodsDepartureTime1"`
	DockWarehouseNumber                  string  `json:"dockWarehouseNumber"`
	LayoutArea                           string  `json:"layoutArea"`
	LetterCreditDocument1                string  `json:"letterCreditDocument1"`
	ExchangeCreditDocument               float64 `json:"exchangeCreditDocument"`
	AmortizationDegree                   float64 `json:"amortizationDegree"`
	DangerousGoods                       string  `json:"dangerousGoods"`
	Reference                            string  `json:"reference"`
	ProgramControl                       string  `json:"programControl"`
	AvailSafeSecurity                    string  `json:"availSafeSecurity"`
	Model                                string  `json:"model"`
	SupplyLocation                       string  `json:"supplyLocation"`
	TimeZone1                            string  `json:"timeZone1"`
	ContainsDangerousGoods               string  `json:"containsDangerousGoods"`
	OriginalSystem                       string  `json:"originalSystem"`
	MerchandiseMovementIndicator         string  `json:"merchandiseMovementIndicator"`
	TransactionCode                      string  `json:"transactionCode"`
	ShippingClass                        string  `json:"shippingClass"`
	Conveyance1                          string  `json:"conveyance1"`
	SpecialManagementIndicator           string  `json:"specialManagementIndicator"`
	GlCompanyNumber                      string  `json:"glCompanyNumber"`
	OpenValFormat                        string  `json:"openValFormat"`
	DirectOtCreation                     string  `json:"directOtCreation"`
	ProductionSupplyArea                 string  `json:"productionSupplyArea"`
	DeliveryClass2                       string  `json:"deliveryClass2"`
	DeliveryReceiptDate                  string  `json:"deliveryReceiptDate"`
	DeliveryReceiptTime                  string  `json:"deliveryReceiptTime"`
	PosPredSystem                        int     `json:"posPredSystem"`
	Middle                               string  `json:"middle"`
	DocumentDeletionIndicator            string  `json:"documentDeletionIndicator"`
	LocationSequence                     string  `json:"locationSequence"`
	DeliveryConfirmationStatus           string  `json:"deliveryConfirmationStatus"`
	TransportInformationStatus           string  `json:"transportInformationStatus"`
	CanceledReturnDelivery               string  `json:"canceledReturnDelivery"`
	GoodsDepartureTime2                  string  `json:"goodsDepartureTime2"`
	TimeZone2                            string  `json:"timeZone2"`
	WarehouseStatus1                     string  `json:"warehouseStatus1"`
	LogisticsExecutionScene              string  `json:"logisticsExecutionScene"`
	OriginalSystemCategory               string  `json:"originalSystemCategory"`
	ModifiedSystemCategory               string  `json:"modifiedSystemCategory"`
	GeographicRoute                      string  `json:"geographicRoute"`
	RouteModification                    string  `json:"routeModification"`
	TransportModification                string  `json:"transportModification"`
	CirculationMerchandise               string  `json:"circulationMerchandise"`
	SapGtsCode                           string  `json:"sapGtsCode"`
	TimeframeRelease                     float64 `json:"timeframeRelease"`
	MeasurementUnitSystems               string  `json:"measurementUnitSystems"`
	InvoiceBefore                        string  `json:"invoiceBefore"`
	StatusQuality                        string  `json:"statusQuality"`
	IndicatorDeviation                   string  `json:"indicatorDeviation"`
	CustodyStatus                        string  `json:"custodyStatus"`
	ExternalIdentifier                   string  `json:"externalIdentifier"`
	Conveyance2                          string  `json:"conveyance2"`
	ProNumber                            string  `json:"proNumber"`
	LetterCreditDocument2                string  `json:"letterCreditDocument2"`
	BillingIndicationEwm                 string  `json:"billingIndicationEwm"`
	PrintProfile                         string  `json:"printProfile"`
	ReturnExtensionManagement            string  `json:"returnExtensionManagement"`
	LogDocument                          string  `json:"logDocument"`
	WarehouseModification                string  `json:"warehouseModification"`
	Controlkey                           string  `json:"controlkey"`
	PartitionLauncher                    string  `json:"partitionLauncher"`
	DeliveryVersion                      string  `json:"deliveryVersion"`
	DataFilterValue                      string  `json:"dataFilterValue"`
	PreliminaryDocumentType              string  `json:"preliminaryDocumentType"`
	PreliminaryDocumentNumber            string  `json:"preliminaryDocumentNumber"`
	TransportMode                        string  `json:"transportMode"`
	PortAirport                          string  `json:"portAirport"`
	BorderTransportationMode             string  `json:"borderTransportationMode"`
	CountryMeansTransportationBorder     string  `json:"countryMeansTransportationBorder"`
	TransfrontMediaId                    string  `json:"transfrontMediaId"`
	PropertyTransmissionReferrerId       string  `json:"propertyTransmissionReferrerId"`
	RiverTransportMode                   string  `json:"riverTransportMode"`
	CountryAverageNationalTransportation string  `json:"countryAverageNationalTransportation"`
	NationalTransportationId             string  `json:"nationalTransportationId"`
	PlaceDelivery                        string  `json:"placeDelivery"`
	DeliverDate                          string  `json:"deliverDate"`
	TransferTime                         string  `json:"transferTime"`
	PickupLocation                       string  `json:"pickupLocation"`
	DeliveryStatus                       string  `json:"deliveryStatus"`
	MaximumValue                         string  `json:"maximumValue"`
	PaymentConditions                    string  `json:"paymentConditions"`
	FinancialDocument                    string  `json:"financialDocument"`
	CreditInsurance                      string  `json:"creditInsurance"`
	PaymentCardStatus                    string  `json:"paymentCardStatus"`
	SapCreditManagement                  string  `json:"sapCreditManagement"`
	TechnicalErrorStatus                 string  `json:"technicalErrorStatus"`
	CreditStatus                         string  `json:"creditStatus"`
	IntercompanyBillingStatus            string  `json:"intercompanyBillingStatus"`
	StockTransferOrderStatus             string  `json:"stockTransferOrderStatus"`
	GlobalStatus                         string  `json:"globalStatus"`
	Hold                                 string  `json:"hold"`
	HoldPosition                         string  `json:"holdPosition"`
	PickingConfirmation                  string  `json:"pickingConfirmation"`
	PickingStatus                        string  `json:"pickingStatus"`
	PickingStorage                       string  `json:"pickingStorage"`
	ActivityStatus                       string  `json:"activityStatus"`
	DeliveryReceiptStatus                string  `json:"deliveryReceiptStatus"`
	PackagingStatus                      string  `json:"packagingStatus"`
	TemporaryDeliveryInformation         string  `json:"temporaryDeliveryInformation"`
	OverallBillingStatus                 string  `json:"overallBillingStatus"`
	TransportationPlanningStatus         string  `json:"transportationPlanningStatus"`
	GeneralHeader                        string  `json:"generalHeader"`
	IncompleteArticles                   string  `json:"incompleteArticles"`
	InvoiceHeader                        string  `json:"invoiceHeader"`
	InvoiceAllpositions                  string  `json:"invoiceAllpositions"`
	PackagingHeader                      string  `json:"packagingHeader"`
	PackagingOptions                     string  `json:"packagingOptions"`
	EntryStock                           string  `json:"entryStock"`
	PositionsPicking                     string  `json:"positionsPicking"`
	DeliveryHeader                       string  `json:"deliveryHeader"`
	DeliveryAll                          string  `json:"deliveryAll"`
	MovementHeader                       string  `json:"movementHeader"`
	MovementMerchandise                  string  `json:"movementMerchandise"`
	WarehouseHandling                    string  `json:"warehouseHandling"`
	WarehouseStatus2                     string  `json:"warehouseStatus2"`
	MovementStatus                       string  `json:"movementStatus"`
	ReserveHeader1                       string  `json:"reserveHeader1"`
	ReserveHeader2                       string  `json:"reserveHeader2"`
	ReserveHeader3                       string  `json:"reserveHeader3"`
	ReserveHeader4                       string  `json:"reserveHeader4"`
	ReserveHeader5                       string  `json:"reserveHeader5"`
	TotalReservation1                    string  `json:"totalReservation1"`
	TotalReservation2                    string  `json:"totalReservation2"`
	TotalReservation3                    string  `json:"totalReservation3"`
	TotalReservation4                    string  `json:"totalReservation4"`
	TotalReservation5                    string  `json:"totalReservation5"`
	TotalProductMarket                   string  `json:"totalProductMarket"`
	TotalDangerousGoods                  string  `json:"totalDangerousGoods"`
	TotalDataSheet                       string  `json:"totalDataSheet"`
	TotalConsumptionTax                  string  `json:"totalConsumptionTax"`
	InvoiceStatusBetweenCompanies        string  `json:"invoiceStatusBetweenCompanies"`
	EmbargoStatus                        string  `json:"embargoStatus"`
	InspectionStatus                     string  `json:"inspectionStatus"`
	LegalControlStatus                   string  `json:"legalControlStatus"`
	StatDnp                              string  `json:"statDnp"`
	IncotermsVersion                     string  `json:"incotermsVersion"`
	IncotermsPlace1                      string  `json:"incotermsPlace1"`
	IncotermsPlace2                      string  `json:"incotermsPlace2"`
	IncotermLocation1                    string  `json:"incotermLocation1"`
	IncotermLocation2                    string  `json:"incotermLocation2"`
	DeviationDestiny                     string  `json:"deviationDestiny"`
	ExtConsignmentNumber                 string  `json:"extConsignmentNumber"`
	MiscellaneousDeliveries              string  `json:"miscellaneousDeliveries"`
	ExternalBusinessSystemId             string  `json:"externalBusinessSystemId"`
	TransportStockSpecification          string  `json:"transportStockSpecification"`
	RelevanceDeliveryReceipt             string  `json:"relevanceDeliveryReceipt"`
	WarehouseExecution                   string  `json:"warehouseExecution"`
	WarehouseExecutionBlock              string  `json:"warehouseExecutionBlock"`
	LegalControlLicenseIndicator         string  `json:"legalControlLicenseIndicator"`
	Timekeeper1                          float64 `json:"timekeeper1"`
	Timekeeper2                          float64 `json:"timekeeper2"`
	CorrectionIndicator                  string  `json:"correctionIndicator"`
	DummyFunction                        string  `json:"dummyFunction"`
	LoadUnits                            string  `json:"loadUnits"`
	CategoryNumber1                      float64 `json:"categoryNumber1"`
	CategoryNumber2                      float64 `json:"categoryNumber2"`
	CategoryNumber3                      float64 `json:"categoryNumber3"`
	CategoryNumber4                      float64 `json:"categoryNumber4"`
	SequenceNumber                       string  `json:"sequenceNumber"`
	CurrentNode                          string  `json:"currentNode"`
	IndicatesArrivalDepartureNode1       string  `json:"indicatesArrivalDepartureNode1"`
	CurrentTimearker                     float64 `json:"currentTimearker"`
	CurrentBaseNode                      string  `json:"currentBaseNode"`
	CheckCheckOut                        string  `json:"checkCheckOut"`
	TimeEstimateMark                     float64 `json:"timeEstimateMark"`
	IndicatesEventTimeEstimate1          string  `json:"indicatesEventTimeEstimate1"`
	PreviousNodeRouteTracking            string  `json:"previousNodeRouteTracking"`
	IndicatesArrivalDepartureNode2       string  `json:"indicatesArrivalDepartureNode2"`
	IndicatesPreviousTimeMarker          float64 `json:"indicatesPreviousTimeMarker"`
	InidcatePreviousBaseNode             string  `json:"inidcatePreviousBaseNode"`
	IndicatesCheckCheckOut               string  `json:"indicatesCheckCheckOut"`
	IndicatesTimeEstimateMark            float64 `json:"indicatesTimeEstimateMark"`
	IndicatesEventTimeEstimate2          string  `json:"indicatesEventTimeEstimate2"`
	IndicatesCurrentBaseNode             string  `json:"indicatesCurrentBaseNode"`
	IndicatesArrivalNode                 string  `json:"indicatesArrivalNode"`
	IndicatesEstimatedTime               float64 `json:"indicatesEstimatedTime"`
	IndicatesDegreeObligation            string  `json:"indicatesDegreeObligation"`
	IndicatesDocumentNumber              string  `json:"indicatesDocumentNumber"`
	InboundDeliveryGroup                 string  `json:"inboundDeliveryGroup"`
	ProductSupply                        string  `json:"productSupply"`
	TransactionNumber                    string  `json:"transactionNumber"`
	SvaLastItem                          string  `json:"svaLastItem"`
	SvaClientGroup                       string  `json:"svaClientGroup"`
	PsstGroup                            string  `json:"psstGroup"`
	ExternalActualDate                   float64 `json:"externalActualDate"`
	ExternalPlanningDate                 float64 `json:"externalPlanningDate"`
	ExternalZoneDate                     string  `json:"externalZoneDate"`
	InternalActualTdcDate                float64 `json:"internalActualTdcDate"`
	InternalPlanningTdcDate              float64 `json:"internalPlanningTdcDate"`
	InternalZoneTdcDate                  string  `json:"internalZoneTdcDate"`
	ReliefJit                            string  `json:"reliefJit"`
	FreightOrder                         string  `json:"freightOrder"`
	BpCarrier                            string  `json:"bpCarrier"`
	DriverName                           string  `json:"driverName"`
	DriverLicense                        string  `json:"driverLicense"`
	Plate1                               string  `json:"plate1"`
	Plate2                               string  `json:"plate2"`
	Plate3                               string  `json:"plate3"`
}

type PositionDelivery struct {
	Principal                   string  `json:"principal"`
	Delivery                    string  `json:"delivery"`
	Position1                   string  `json:"position1"`
	DocumentNumber              string  `json:"documentNumber"`
	TransportDocumentType       string  `json:"transportDocumentType"`
	BusinessName                string  `json:"businessName"`
	CompanyName                 string  `json:"companyName"`
	TypeNif                     string  `json:"typeNif"`
	Nif                         string  `json:"nif"`
	PositionType1               string  `json:"positionType1"`
	Author                      string  `json:"author"`
	Hour                        string  `json:"hour"`
	CreateDay                   string  `json:"createDay"`
	Material                    string  `json:"material"`
	ShortMaterialText           string  `json:"shortMaterialText"`
	ShortMaterialMatchcodes     string  `json:"shortMaterialMatchcodes"`
	MaterialIntroduced          string  `json:"materialIntroduced"`
	ExtSunatCode                string  `json:"extSunatCode"`
	MaterialBaseMeasurementUnit string  `json:"materialBaseMeasurementUnit"`
	ItemGroup                   string  `json:"itemGroup"`
	Center                      string  `json:"center"`
	SupplierName                string  `json:"supplierName"`
	Society                     string  `json:"society"`
	DescriptionSociety          string  `json:"descriptionSociety"`
	Store                       string  `json:"store"`
	WarehouseName               string  `json:"warehouseName"`
	Batch                       string  `json:"batch"`
	SupplierLot                 string  `json:"supplierLot"`
	ClientItemCode              string  `json:"clientItemCode"`
	ProductHierarchy            string  `json:"productHierarchy"`
	NodeCode                    string  `json:"nodeCode"`
	DeliveryQuantity1           float64 `json:"deliveryQuantity1"`
	OrderedUnitMeasure          string  `json:"orderedUnitMeasure"`
	SalesUnitMeasure            string  `json:"salesUnitMeasure"`
	Counter1                    float64 `json:"counter1"`
	Denominator                 float64 `json:"denominator"`
	NetWeight                   float64 `json:"netWeight"`
	GrossWeight                 float64 `json:"grossWeight"`
	WeightUnit1                 string  `json:"weightUnit1"`
	Volume                      float64 `json:"volume"`
	VolumeUnit1                 string  `json:"volumeUnit1"`
	PartialPosDelivery          string  `json:"partialPosDelivery"`
	ExcessSupply                string  `json:"excessSupply"`
	TolExcSupply                float64 `json:"tolExcSupply"`
	TolerateSupplyFaults        float64 `json:"tolerateSupplyFaults"`
	LotDivisionAllowed          string  `json:"lotDivisionAllowed"`
	InvoiceLock                 string  `json:"invoiceLock"`
	MateiralDistributionDate    string  `json:"mateiralDistributionDate"`
	ActualAmountUma             float64 `json:"actualAmountUma"`
	PositionName                string  `json:"positionName"`
	Location1                   string  `json:"location1"`
	Cause                       string  `json:"cause"`
	CausativePosition           string  `json:"causativePosition"`
	SalesDocumentType           string  `json:"salesDocumentType"`
	PredecessorLogicalSystem    string  `json:"predecessorLogicalSystem"`
	ModelDocument               string  `json:"modelDocument"`
	ModelPosition               string  `json:"modelPosition"`
	DocumentFlowUpdate          string  `json:"documentFlowUpdate"`
	TopPosition                 string  `json:"topPosition"`
	RelevantInvoice             string  `json:"relevantInvoice"`
	BatchBillingVariant         string  `json:"batchBillingVariant"`
	LoadGroup                   string  `json:"loadGroup"`
	TransportGroup              string  `json:"transportGroup"`
	PickingIndicator            string  `json:"pickingIndicator"`
	WarehouseNumber             string  `json:"warehouseNumber"`
	DeliveryIDWarehouseNumber   string  `json:"deliveryIdWarehouseNumber"`
	WarehouseType               string  `json:"warehouseType"`
	Location2                   string  `json:"location2"`
	ReviewSeparate              string  `json:"reviewSeparate"`
	DistributionType            string  `json:"distributionType"`
	MovementClass1              string  `json:"movementClass1"`
	MovementClass2              string  `json:"movementClass2"`
	DynamicLocationIndex        string  `json:"dynamicLocationIndex"`
	NeedClass                   string  `json:"needClass"`
	PlanningClass               string  `json:"planningClass"`
	MaterialType                string  `json:"materialType"`
	BatchManagement1            string  `json:"batchManagement1"`
	BatchManagement2            string  `json:"batchManagement2"`
	PreviousDocumentCreated     string  `json:"previousDocumentCreated"`
	PositionType2               string  `json:"positionType2"`
	ValuationClass              string  `json:"valuationClass"`
	TotalNeed                   string  `json:"totalNeed"`
	AvailabilityCheck1          string  `json:"availabilityCheck1"`
	EanNumber                   string  `json:"eanNumber"`
	Division                    string  `json:"division"`
	SalesOffice                 string  `json:"salesOffice"`
	SellerGroup                 string  `json:"sellerGroup"`
	DistributionChannel         string  `json:"distributionChannel"`
	Sector                      string  `json:"sector"`
	DeliveryGroup               string  `json:"deliveryGroup"`
	FixedQuantity               string  `json:"fixedQuantity"`
	MaximumPartialDeliveries    float64 `json:"maximumPartialDeliveries"`
	FixedTreatmentTime          float64 `json:"fixedTreatmentTime"`
	VariableProcessingTime      float64 `json:"variableProcessingTime"`
	Current                     string  `json:"current"`
	InternalCosts               float64 `json:"internalCosts"`
	Subtotal1                   float64 `json:"subtotal1"`
	Subtotal2                   float64 `json:"subtotal2"`
	Subtotal3                   float64 `json:"subtotal3"`
	Subtotal4                   float64 `json:"subtotal4"`
	Subtotal5                   float64 `json:"subtotal5"`
	Subtotal6                   float64 `json:"subtotal6"`
	SpecialStock                string  `json:"specialStock"`
	CreationDate                string  `json:"creationDate"`
	EanCode                     string  `json:"eanCode"`
	CustomerGroup1              string  `json:"customerGroup1"`
	CustomerGroup2              string  `json:"customerGroup2"`
	CustomerGroup3              string  `json:"customerGroup3"`
	CustomerGroup4              string  `json:"customerGroup4"`
	CustomerGroup5              string  `json:"customerGroup5"`
	ItemCodeGroup1              string  `json:"itemCodeGroup1"`
	ItemCodeGroup2              string  `json:"itemCodeGroup2"`
	ItemCodeGroup3              string  `json:"itemCodeGroup3"`
	ItemCodeGroup4              string  `json:"itemCodeGroup4"`
	ItemCodeGroup5              string  `json:"itemCodeGroup5"`
	AssignmentIndicator         string  `json:"assignmentIndicator"`
	PreviousDocumentType        string  `json:"previousDocumentType"`
	CentralDocumentType         string  `json:"centralDocumentType"`
	CostCenter                  string  `json:"costCenter"`
	ControlledSociety           string  `json:"controlledSociety"`
	PaObjectNumber              string  `json:"paObjectNumber"`
	ProfitCenter                string  `json:"profitCenter"`
	Element                     string  `json:"element"`
	Order                       string  `json:"order"`
	PositionNumber1             string  `json:"positionNumber1"`
	Operation                   string  `json:"operation"`
	RecipientLocation           string  `json:"recipientLocation"`
	OperationRouteSheetNumber   string  `json:"operationRouteSheetNumber"`
	Counter2                    string  `json:"counter2"`
	CustomerOrder               string  `json:"customerOrder"`
	CustomerOrderPosition       string  `json:"customerOrderPosition"`
	PreplanningMaterial         string  `json:"preplanningMaterial"`
	PreplanningCenter           string  `json:"preplanningCenter"`
	UmProductGroup              string  `json:"umProductGroup"`
	Conversion                  bool    `json:"conversion"`
	AllocationType              string  `json:"allocationType"`
	Consumption                 string  `json:"consumption"`
	BudgetPosition              string  `json:"budgetPosition"`
	ManagementCenter            string  `json:"managementCenter"`
	Money                       string  `json:"money"`
	PackagingControl            string  `json:"packagingControl"`
	NeedCategory                string  `json:"needCategory"`
	ActiveCreditFunction        string  `json:"activeCreditFunction"`
	AcumulatedBatchQuantity     float64 `json:"acumulatedBatchQuantity"`
	AccumulatedGrossWeight      float64 `json:"accumulatedGrossWeight"`
	AccumulatedNetWeight        float64 `json:"accumulatedNetWeight"`
	AccumulatedVolume           float64 `json:"accumulatedVolume"`
	LotTopPosition              string  `json:"lotTopPosition"`
	Configuration               string  `json:"configuration"`
	InternalObjectNumber        string  `json:"internalObjectNumber"`
	QuantitySerialNumbers       int     `json:"quantitySerialNumbers"`
	ProfileSerialNumber         string  `json:"profileSerialNumber"`
	WeightUnit2                 string  `json:"weightUnit2"`
	VolumeUnit2                 string  `json:"volumeUnit2"`
	SerialNumber                string  `json:"serialNumber"`
	OrderInternalDelivery       string  `json:"orderInternalDelivery"`
	DeliveryOrderClass          string  `json:"deliveryOrderClass"`
	Utilization                 string  `json:"utilization"`
	InspectionLot               string  `json:"inspectionLot"`
	PartialLot                  string  `json:"partialLot"`
	WithoutEmClient             string  `json:"withoutEmClient"`
	MeMaterials                 string  `json:"meMaterials"`
	HeaderObjectNumber          string  `json:"headerObjectNumber"`
	ObjectPositionNumber        string  `json:"objectPositionNumber"`
	ModifyProject               string  `json:"modifyProject"`
	Returns                     string  `json:"returns"`

	ActiveMaterialDetection         string  `json:"activeMaterialDetection"`
	PossUsage                       string  `json:"possUsage"`
	ReceptionPoint                  string  `json:"receptionPoint"`
	Department                      string  `json:"department"`
	Confirmation                    string  `json:"confirmation"`
	StatisticalDate                 string  `json:"statisticalDate"`
	TradePromotion                  string  `json:"tradePromotion"`
	ConditionLotNumber              string  `json:"conditionLotNumber"`
	CustomsPreference               string  `json:"customsPreference"`
	OperationComercial              string  `json:"operationComercial"`
	InternalClassNumber             string  `json:"internalClassNumber"`
	ProposedQuantities              string  `json:"proposedQuantities"`
	AllocationTable                 string  `json:"allocationTable"`
	Position2                       string  `json:"position2"`
	InternalFieldLfimg              bool    `json:"internalFieldLfimg"`
	InternalFieldLfgmng             bool    `json:"internalFieldLfgmng"`
	InternalFieldKcmeng             bool    `json:"internalFieldKcmeng"`
	EnvironmentalRelief             string  `json:"environmentalRelief"`
	ComponentQuantity               float64 `json:"componentQuantity"`
	RelayAssignedTable              string  `json:"relayAssignedTable"`
	PriceUm                         float64 `json:"priceUm"`
	UnitMeasurement                 string  `json:"unitMeasurement"`
	NetAskingPrice                  float64 `json:"netAskingPrice"`
	NetOrderValue                   float64 `json:"netOrderValue"`
	StatisticalValues               string  `json:"statisticalValues"`
	MovementIndicator               string  `json:"movementIndicator"`
	MaterialCarryingGroup           string  `json:"materialCarryingGroup"`
	PackagingAccumulatedLotPosition string  `json:"packagingAccumulatedLotPosition"`
	GuaranteeForm                   string  `json:"guaranteeForm"`
	Guaranteed                      bool    `json:"guaranteed"`
	TimeMadeAvailableMaterial       string  `json:"timeMadeAvailableMaterial"`
	OpenOrderNumberValue            string  `json:"openOrderNumberValue"`
	OpenOrderPosition               string  `json:"openOrderPosition"`
	Cfop                            string  `json:"cfop"`
	IcmsLaw                         string  `json:"icmsLaw"`
	IpiLaw                          string  `json:"ipiLaw"`
	TaxCode                         string  `json:"taxCode"`
	Situation                       string  `json:"situation"`
	Booking1                        string  `json:"booking1"`
	ReservationPositionNumber1      string  `json:"reservationPositionNumber1"`
	RegistrationClass               string  `json:"registrationClass"`
	SequenceNumber                  string  `json:"sequenceNumber"`
	UseMeasure1                     string  `json:"useMeasure1"`
	MpIndicatorProfile              string  `json:"mpIndicatorProfile"`
	QuantityCumulativeBatch         float64 `json:"quantityCumulativeBatch"`
	CumulativeBatchSplitQuantity    bool    `json:"cumulativeBatchSplitQuantity"`
	SpecialStockValue               string  `json:"specialStockValue"`

	DefinitionProject             string  `json:"definitionProject"`
	TakeSequenceGroup             string  `json:"takeSequenceGroup"`
	StockDeterminationRule        string  `json:"stockDeterminationRule"`
	CurrentStockDetermination     string  `json:"currentStockDetermination"`
	FabricPartsProfile            string  `json:"fabricPartsProfile"`
	ManufacturerPartNumber        string  `json:"manufacturerPartNumber"`
	DischargePoint1               string  `json:"dischargePoint1"`
	ProgramControl                string  `json:"programControl"`
	OriginalPosition              string  `json:"originalPosition"`
	ExternalPosition              string  `json:"externalPosition"`
	AvailabilityCheck2            string  `json:"availabilityCheck2"`
	NotRelevantPicking            string  `json:"notRelevantPicking"`
	WmReferenceMovementClass      string  `json:"wmReferenceMovementClass"`
	NecArea                       string  `json:"necArea"`
	StockDifferentiation1         string  `json:"stockDifferentiation1"`
	StockDifferentiation2         string  `json:"stockDifferentiation2"`
	ReceivingMaterial             string  `json:"receivingMaterial"`
	ReceivingCenter               string  `json:"receivingCenter"`
	ReceivingWarehouse            string  `json:"receivingWarehouse"`
	ReceivingLot                  string  `json:"receivingLot"`
	DestLotValueClass             string  `json:"destLotValueClass"`
	TransferIndicator             string  `json:"transferIndicator"`
	SpecialStockNumber1           string  `json:"specialStockNumber1"`
	SpecialStockNumber2           string  `json:"specialStockNumber2"`
	ChangeTypeCreditDocLetter     float64 `json:"changeTypeCreditDocLetter"`
	CurrentQuantity               string  `json:"currentQuantity"`
	ClassificationPositions       string  `json:"classificationPositions"`
	ReferenceAccountingIndicator  string  `json:"referenceAccountingIndicator"`
	StockType                     string  `json:"stockType"`
	BatchEntry                    string  `json:"batchEntry"`
	DestinationLocationDataCopied string  `json:"destinationLocationDataCopied"`
	MadeAvailable                 string  `json:"madeAvailable"`
	DeliveryItemStoreItem         string  `json:"deliveryItemStoreItem"`
	NoMovementMerchandise         string  `json:"noMovementMerchandise"`

	GeneralLedgerAccount                string  `json:"generalLedgerAccount"`
	FinalDeparture                      string  `json:"finalDeparture"`
	ManufacturingDate                   string  `json:"manufacturingDate"`
	ExpiresDate                         string  `json:"expiresDate"`
	CurrentPeriod                       string  `json:"currentPeriod"`
	ReferenceDocument                   string  `json:"referenceDocument"`
	ReferenceDocumentPosition           string  `json:"referenceDocumentPosition"`
	MovementReason                      string  `json:"movementReason"`
	SubsequentMovement                  string  `json:"subsequentMovement"`
	DeliveryType                        string  `json:"deliveryType"`
	ForeignAmountLocal                  float64 `json:"foreignAmountLocal"`
	QuantityUmpp                        float64 `json:"quantityUmpp"`
	SaleValue                           float64 `json:"saleValue"`
	CreditPrice                         bool    `json:"creditPrice"`
	AreIndicator                        string  `json:"areIndicator"`
	NotRelevantSga                      string  `json:"notRelevantSga"`
	ConversionFactor                    bool    `json:"conversionFactor"`
	PurchaseSaleDocument                string  `json:"purchaseSaleDocument"`
	Transfer                            string  `json:"transfer"`
	FunctionalArea                      string  `json:"functionalArea"`
	Grant                               string  `json:"grant"`
	UseMeasure2                         string  `json:"useMeasure2"`
	MerchandiseMovementControl          string  `json:"merchandiseMovementControl"`
	MerchandiseMovementControlIndicator string  `json:"merchandiseMovementControlIndicator"`
	ElementTransfer                     string  `json:"elementTransfer"`
	CurrentNumber                       string  `json:"currentNumber"`
	CompleteDelivery                    string  `json:"completeDelivery"`
	IndustryProcessingEwm               string  `json:"industryProcessingEwm"`
	RmaNumber                           string  `json:"rmaNumber"`
	InspectionResult                    string  `json:"inspectionResult"`
	NextActivity                        string  `json:"nextActivity"`
	EndValidityReturnsReceipts          float64 `json:"endValidityReturnsReceipts"`
	EndValidityInternal                 float64 `json:"endValidityInternal"`
	ClosedRmaNumber                     string  `json:"closedRmaNumber"`
	DeliveryQuantity2                   string  `json:"deliveryQuantity2"`

	AtpTimekeeper                       float64 `json:"atpTimekeeper"`
	OriginalSystemCategory              string  `json:"originalSystemCategory"`
	AccumulatedQuantityDeliverySupplier float64 `json:"accumulatedQuantityDeliverySupplier"`
	Middle                              string  `json:"middle"`
	ExternalProductIdentifier           string  `json:"externalProductIdentifier"`
	StoreExceptionCode                  string  `json:"storeExceptionCode"`
	RetentionAmountScrappingProcess     float64 `json:"retentionAmountScrappingProcess"`
	AlternativeProductNumber            string  `json:"alternativeProductNumber"`
	ReplacementReason                   string  `json:"replacementReason"`
	Structure                           string  `json:"structure"`
	Numerator                           float64 `json:"numerator"`
	Denomination                        float64 `json:"denomination"`
	CountryRegionOrigin                 string  `json:"countryRegionOrigin"`
	ReturnsDeliveryValidityIndicator    float64 `json:"returnsDeliveryValidityIndicator"`
	ConfirmationDelivery                string  `json:"confirmationDelivery"`
	ClosingContab                       string  `json:"closingContab"`
	CofinsLaw                           string  `json:"cofinsLaw"`
	PsiLaw                              string  `json:"psiLaw"`
	IssLaw                              string  `json:"issLaw"`
	Budget                              string  `json:"budget"`
	ProductSupply                       string  `json:"productSupply"`
	IncomeAccountingClass               string  `json:"incomeAccountingClass"`
	StockSpecification                  string  `json:"stockSpecification"`
	NeedSegment                         string  `json:"needSegment"`
	StockSegment                        string  `json:"stockSegment"`
	Resource                            string  `json:"resource"`
	ReceivingResource                   string  `json:"receivingResource"`
	FieldLogisticsIndustry              string  `json:"fieldLogisticsIndustry"`

	LoadingUnloadingPoint          string  `json:"loadingUnloadingPoint"`
	SolutionOrder                  string  `json:"solutionOrder"`
	PositionNumberDocument         string  `json:"positionNumberDocument"`
	RegionOrigin                   string  `json:"regionOrigin"`
	MerchandiseCode                string  `json:"merchandiseCode"`
	MerchandiseDestination         string  `json:"merchandiseDestination"`
	TimekeeperCreation             float64 `json:"timekeeperCreation"`
	TimekeeperChanged              float64 `json:"timekeeperChanged"`
	PickingQuantity1               float64 `json:"pickingQuantity1"`
	PickingQuantity2               float64 `json:"pickingQuantity2"`
	DeliveryStatus                 string  `json:"deliveryStatus"`
	FinancialDocument              string  `json:"financialDocument"`
	CreditInsurance                string  `json:"creditInsurance"`
	InvoiceStatusBetweenCompanies1 string  `json:"invoiceStatusBetweenCompanies1"`
	DeliveryInvoiceStatus          string  `json:"deliveryInvoiceStatus"`
	GlobalStatus                   string  `json:"globalStatus"`
	DeliveryPositionNotComplete    string  `json:"deliveryPositionNotComplete"`
	ConfirmationPicking            string  `json:"confirmationPicking"`
	PickingStatus1                 string  `json:"pickingStatus1"`
	GaActivityStatus               string  `json:"gaActivityStatus"`
	DeliveryReceiptStatus          string  `json:"deliveryReceiptStatus"`
	PackagingStatus                string  `json:"packagingStatus"`
	Position3                      string  `json:"position3"`
	InvoicePosition                string  `json:"invoicePosition"`
	PackingPosition                string  `json:"packingPosition"`
	PickingStockEntry              string  `json:"pickingStockEntry"`
	DeliveryPosition               string  `json:"deliveryPosition"`
	MovementPosition               string  `json:"movementPosition"`
	DecentralizedWarehouse         string  `json:"decentralizedWarehouse"`
	MovementStatus                 string  `json:"movementStatus"`
	ReservePosition1               string  `json:"reservePosition1"`
	ReservePosition2               string  `json:"reservePosition2"`
	ReservePosition3               string  `json:"reservePosition3"`
	ReservePosition4               string  `json:"reservePosition4"`

	ReservePosition5                 string  `json:"reservePosition5"`
	EmbargoStatus                    string  `json:"embargoStatus"`
	VerificationStatus               string  `json:"verificationStatus"`
	LegalControlStatus               string  `json:"legalControlStatus"`
	ProductMarketCapacityStatus      string  `json:"productMarketCapacityStatus"`
	DangerousGoodsStatus             string  `json:"dangerousGoodsStatus"`
	SafetyDataSheetStatus            string  `json:"safetyDataSheetStatus"`
	InvoiceStatusBetweenCompanies2   string  `json:"invoiceStatusBetweenCompanies2"`
	PickingStatus2                   string  `json:"pickingStatus2"`
	StatDnp                          string  `json:"statDnp"`
	ExciseTaxArcStatus               string  `json:"exciseTaxArcStatus"`
	DataFilterValue                  string  `json:"dataFilterValue"`
	QuantityDeliveredUmp             float64 `json:"quantityDeliveredUmp"`
	DeliveryMeasurementUnit          string  `json:"deliveryMeasurementUnit"`
	PickingQuantity                  float64 `json:"pickingQuantity"`
	ParallelPickingMeasurementUnit   string  `json:"parallelPickingMeasurementUnit"`
	IndicatedQuantity                string  `json:"indicatedQuantity"`
	EntryOt                          string  `json:"entryOt"`
	AccumulatedCatchWeightQuantity   float64 `json:"accumulatedCatchWeightQuantity"`
	QuantityPostedUmp                float64 `json:"quantityPostedUmp"`
	DummyFunction                    string  `json:"dummyFunction"`
	InternalReferenceDocumentype     string  `json:"internalReferenceDocumentype"`
	InternalReferenceDocument        string  `json:"internalReferenceDocument"`
	InternalReferenceocumentPosition string  `json:"internalReferenceocumentPosition"`
	InternalBillingClass             string  `json:"internalBillingClass"`
	SalesOrganization                string  `json:"salesOrganization"`
	BillingDate                      string  `json:"billingDate"`
	FactCompIntDate                  string  `json:"factCompIntDate"`
	UniqueId16                       string  `json:"uniqueId16"`
	ValueChainCategory               string  `json:"valueChainCategory"`
	Inverted                         string  `json:"inverted"`
	Cpa                              string  `json:"cpa"`
	ConversionFactorsIndicator       string  `json:"conversionFactorsIndicator"`
	DockWarehouseNumber              string  `json:"dockWarehouseNumber"`
	SeasonalYear                     string  `json:"seasonalYear"`
	Season2                          string  `json:"season2"`
	Collection                       string  `json:"collection"`
	Issue                            string  `json:"issue"`
	CustomerGroup6                   string  `json:"customerGroup6"`
	CustomerGroup7                   string  `json:"customerGroup7"`
	CustomerGroup8                   string  `json:"customerGroup8"`
	CustomerGroup9                   string  `json:"customerGroup9"`
	CustomerGroup10                  string  `json:"customerGroup10"`
	RelevantSva                      string  `json:"relevantSva"`
	Position4                        string  `json:"position4"`
	TransactionNumber                string  `json:"transactionNumber"`
	PositionGroup                    string  `json:"positionGroup"`
	PositionNumber2                  string  `json:"positionNumber2"`
	Booking2                         string  `json:"booking2"`
	ReservationPositionNumber2       string  `json:"reservationPositionNumber2"`
	LotsCommonOrigin                 string  `json:"lotsCommonOrigin"`
	PreferentialConsignment          string  `json:"preferentialConsignment"`
	CharacteristicDesignation1       string  `json:"characteristicDesignation1"`
	CharacteristicDesignation2       string  `json:"characteristicDesignation2"`
	CharacteristicDesignation3       string  `json:"characteristicDesignation3"`
	Reference                        string  `json:"reference"`
}
