package model

type RemissionOrderRequest struct {
	ReasonConsultation string `json:"-"`
	ReferenceType      string `json:"-"`
	Society            string `json:"-"`
	SupplierCode       string `json:"-"`
	SupplyCenter       string `json:"-"`
	DocumentType       string `json:"-"`
	DateStart          string `json:"-"`
	DateEnd            string `json:"-"`
	DocumentNumber     string `json:"-"`
	DocumentPosition   string `json:"-"`
	MaterialNumber     string `json:"-"`
	DestinationCenter  string `json:"-"`
}

type RemissionOrderResponse struct {
	HeaderOrders HeaderOrders `json:"headerOrder"`
	DetailOrders DetailOrders `json:"detailOrder"`
}

type HeaderOrders []HeaderOrder
type DetailOrders []DetailOrder

type HeaderOrder struct {
	Principal                           string  `json:"principal"`
	PurchasingDocument                  string  `json:"purchasingDocument"`
	Society                             string  `json:"society"`
	DescriptionSociety                  string  `json:"descriptionSociety"`
	PurchasingDocumentType              string  `json:"purchasingDocumentType"`
	PurchasingDocumentCI                string  `json:"purchasingDocumentCI"`
	ControlIndicator                    string  `json:"controlIndicator"`
	EraseIndicator                      string  `json:"eraseIndicator"`
	Status                              string  `json:"status"`
	CreationDate                        string  `json:"creationDate"`
	Author                              string  `json:"author"`
	LastModification                    float64 `json:"lastModification"` //ver tipo de dato
	PositionInterval                    string  `json:"positionInterval"`
	LastPosition                        string  `json:"lastPosition"`
	Supplier                            string  `json:"supplier"`
	SupplierName                        string  `json:"supplierName"`
	TypeNIF                             string  `json:"typeNIF"`
	Nif                                 string  `json:"nif"`
	LanguajeKey                         string  `json:"languajeKey"`
	PaymentCondition                    string  `json:"paymentCondition"`
	Pay1                                float64 `json:"pay1"`
	Pay2                                float64 `json:"pay2"`
	Pay3                                float64 `json:"pay3"`
	Discount1                           float64 `json:"discount1"`
	Discount2                           float64 `json:"discount2"`
	PurchasingOrganization              string  `json:"purchasingOrganization"`
	ShoppingGroup                       string  `json:"shoppingGroup"`
	Currency                            string  `json:"currency"`
	ExchangeRate                        float64 `json:"exchangeRate"`
	FixedExchangeRate                   string  `json:"fixedExchangeRate"`
	DocumentDate                        string  `json:"documentDate"`
	StartPeriodValidity                 string  `json:"startPeriodValidity"`
	EndPeriodValidity                   string  `json:"endPeriodValidity"`
	TenderDeadline                      string  `json:"tenderDeadline"`
	OfferPeriod                         string  `json:"offerPeriod"`
	BindingTerm                         string  `json:"bindingTerm"`
	Warranty                            string  `json:"warranty"`
	Tender                              string  `json:"tender"`
	Offer                               string  `json:"offer"`
	OfferDate                           string  `json:"offerDate"`
	Reference                           string  `json:"reference"`
	Seller                              string  `json:"seller"`
	Phone                               string  `json:"phone"`
	MerchandiseSupplier                 string  `json:"merchandiseSupplier"`
	Customer                            string  `json:"customer"`
	ActivePurchasingDocument            string  `json:"activePurchasingDocument"`
	FrameworkContract                   string  `json:"frameworkContract"`
	NotUsed                             string  `json:"notUsed"`
	CompleteSupply                      string  `json:"completeSupply"`
	MessageEM                           string  `json:"messageEM"`
	SupplyCenter                        string  `json:"supplyCenter"`
	ReceivingProvider                   string  `json:"receivingProvider"`
	Incoterms1                          string  `json:"incoterms1"`
	Incoterms2                          string  `json:"incoterms2"`
	ExpectedValue                       float64 `json:"expectedValue"`
	DistributionClassPurchasingDocument string  `json:"distributionClassPurchasingDocument"`
	Tender2                             string  `json:"tender2"`
	DocumentConditionNumber             string  `json:"documentConditionNumber"`
	Scheme                              string  `json:"scheme"`
	Current                             string  `json:"current"`
	InvoiceIssuer                       string  `json:"invoiceIssuer"`
	ForeignTradeData                    string  `json:"foreignTradeData"`
	OurReference                        string  `json:"ourReference"`
	LogicalSystem                       string  `json:"logicalSystem"`
	SubpositionInterval                 string  `json:"subpositionInterval"`
	TemporaryConditions                 string  `json:"temporaryConditions"`
	LiberationGroup                     string  `json:"liberationGroup"`
	LiberationStrategy                  string  `json:"liberationStrategy"`
	IndRelease                          string  `json:"indRelease"`
	ReleaseStatus                       string  `json:"releaseStatus"`
	RelevantRelease                     string  `json:"relevantRelease"`
	Country                             string  `json:"Country"`
	DeliveryOrderDocument               string  `json:"deliveryOrderDocument"`
	Address                             string  `json:"address"`
	CountryNIF                          string  `json:"countryNIF"`
	CommunityNIF                        string  `json:"communityNIF"`
	ReasonRejection                     string  `json:"reasonRejection"`
	DocumentNumber                      string  `json:"documentNumber"`
	Type                                string  `json:"type"`
	Incomplete                          string  `json:"incomplete"`
	PurchasingProcessStatus             string  `json:"purchasingProcessStatus"`
	ProcessIndicator                    string  `json:"processIndicator"`
	TotalReleaseValue                   float64 `json:"totalReleaseValue"`
	ModificationStatus                  string  `json:"modificationStatus"`
	Version                             string  `json:"version"`
	Scmproc                             string  `json:"scmproc"`
	CauseCode                           string  `json:"causeCode"`
	IncompleteDate                      string  `json:"incompleteDate"`
	Retention                           string  `json:"retention"`
	RetentionPercentage                 float64 `json:"retentionPercentage"`
	Advance                             string  `json:"advance"`
	AdvancePercentage                   float64 `json:"advancePercentage"`
	AdvanceAmount                       float64 `json:"advanceAmount"`
	AdvancePaymentDueDate               string  `json:"advancePaymentDueDate"`
	ProcessIdNumber                     string  `json:"processIdNumber"`
	OrderHierachyPart                   string  `json:"orderHierachyPart"`
	GroupingID                          string  `json:"groupingID"`
	SuperiorDocument                    string  `json:"superiorDocument"`
	ThresholdExchange                   string  `json:"thresholdExchange"`
	LegalOrder                          string  `json:"legalOrder"`
	LegalOrderDescription               string  `json:"legalOrderDescription"`
	LegarOrderDate                      string  `json:"legarOrderDate"`
	ShippingClass                       string  `json:"shippingClass"`
	PlaceDelivery                       string  `json:"placeDelivery"`
	ShippingCondition                   string  `json:"shippingCondition"`
	IncotermsVersion                    string  `json:"incotermsVersion"`
	IncotermsPlace                      string  `json:"incotermsPlace"`
	IncotermsPlace2                     string  `json:"incotermsPlace2"`
	IncotermLocation1                   string  `json:"incotermLocation1"`
	IncotermLocation2                   string  `json:"incotermLocation2"`
	DeviationDestiny                    string  `json:"deviationDestiny"`
	Currency2                           string  `json:"currency2"`
	IntraRelevance                      string  `json:"intraRelevance"`
	IntraExclude                        string  `json:"intraExclude"`
	TotalStatusProducts                 string  `json:"totalStatusProducts"`
	TotalStatusMarket                   string  `json:"totalStatusMarket"`
	TotalStatusDangerous                string  `json:"totalStatusDangerous"`
	TotalStatusSecurity                 string  `json:"totalStatusSecurity"`
	OfferStartDate                      string  `json:"offerStartDate"`
	FollowDocumentCategory              string  `json:"followDocumentCategory"`
	FollowDocumentType                  string  `json:"followDocumentType"`
	DummyOrder                          string  `json:"dummyOrder"`
	ExternarlSystem                     string  `json:"externarlSystem"`
	ExternalReference                   string  `json:"externalReference"`
	ExternalReviewing                   float64 `json:"externalReviewing"`
	BusinessObjectiveAchieved           string  `json:"businessObjectiveAchieved"`
	DocumentOld                         string  `json:"documentOld"`
	UniqueId                            string  `json:"uniqueId"`
	Counter                             string  `json:"counter"`
	TransferId                          string  `json:"transferId"`
	TransferStageId                     string  `json:"transferStageId"`
	SourceLogicalSystem                 string  `json:"sourceLogicalSystem"`
	TransactionNumber                   string  `json:"transactionNumber"`
	PositionGroup                       string  `json:"positionGroup"`
	SvaLastItem                         string  `json:"svaLastItem"`
	OrderScheduleChange                 string  `json:"orderScheduleChange"`
	TransportationSap                   string  `json:"transportationSap"`
	ConsideredPaymentDate               string  `json:"consideredPaymentDate"`
	OperationNumber                     string  `json:"operationNumber"`
	RenewalPeriod                       string  `json:"renewalPeriod"`
	CancellationPeriod                  string  `json:"cancellationPeriod"`
	AnnexingPackageKey                  string  `json:"annexingPackageKey"`
	AnnexingPackageExtend               string  `json:"annexingPackageExtend"`
	BaseDate                            string  `json:"baseDate"`
	AnnexingDateType                    string  `json:"annexingDateType"`
	AnnexingStartDate                   string  `json:"annexingStartDate"`
	DeviationPerecentage                float64 `json:"deviationPerecentage"`
	AnnexedIndicator                    string  `json:"annexedIndicator"`
	LimitDate                           string  `json:"limitDate"`
	Numerator                           string  `json:"numerator"`
	NewBaseDate                         string  `json:"newBaseDate"`
	AccountGeneralMethod                string  `json:"accountGeneralMethod"`
	NegativeAnnexing                    string  `json:"negativeAnnexing"`
	PurchasingOrganization2             string  `json:"purchasingOrganization2"`
	IndexIndicator                      string  `json:"indexIndicator"`
	Postat                              string  `json:"postat"`
	InterestIndicator                   string  `json:"interestIndicator"`
	InstantStatus                       string  `json:"instantStatus"`
	ProcedureNumber                     string  `json:"procedureNumber"`
	Adjustment                          string  `json:"adjustment"`
	ContractType                        string  `json:"contractType"`
	LegalCompetence                     string  `json:"legalCompetence"`
	Miscellaneous                       string  `json:"miscellaneous"`
	Despatch                            string  `json:"despatch"`
	DespDate                            string  `json:"despDate"`
	DespJob                             string  `json:"despJob"`
	Assesment                           string  `json:"assesment"`
	AssesmentDate                       string  `json:"assesmentDate"`
	AssesmentJob                        string  `json:"assesmentJob"`
	Contract                            string  `json:"contract"`
	DocumentType                        string  `json:"documentType"`
	SameDelliveryDate                   string  `json:"sameDelliveryDate"`
	SameCenter                          string  `json:"sameCenter"`
	FixedDateCommercial                 string  `json:"fixedDateCommercial"`
	ConsiderPurchasingGroup             string  `json:"considerPurchasingGroup"`
	ConsiderCenter                      string  `json:"considerCenter"`
	ConsiderOpenOrders                  string  `json:"considerOpenOrders"`
	ConsiderPositionType                string  `json:"considerPositionType"`
	FixedOperation                      string  `json:"fixedOperation"`
	ConsiderBudget                      string  `json:"considerBudget"`
	ConsiderReleaveAssignment           string  `json:"considerReleaveAssignment"`
	ConsiderDeliveryPeriod              string  `json:"considerDeliveryPeriod"`
	ConsiderDeliveryDate                string  `json:"considerDeliveryDate"`
	ConsiderSupllier                    string  `json:"considerSupllier"`
	VerificationLevel                   string  `json:"verificationLevel"`
	ConditionClass                      string  `json:"conditionClass"`
	BudgetNumber                        string  `json:"budgetNumber"`
	BudgetNecessary                     float64 `json:"budgetNecessary"`
	Coin                                string  `json:"coin"`
	BudgetReserved                      float64 `json:"budgetReserved"`
	BudgetSpecial                       float64 `json:"budgetSpecial"`
	JustificationProfile                string  `json:"justificationProfile"`
	BudgetClass                         string  `json:"budgetClass"`
	VerificationStatus                  string  `json:"verificationStatus"`
	Justification                       string  `json:"justification"`
	CheckType                           string  `json:"checkType"`
	OpenOrders                          string  `json:"openOrders"`
	OpenOrdersLevel                     string  `json:"openOrdersLevel"`
	OpenOrdersDistribution              string  `json:"openOrdersDistribution"`
}

type DetailOrder struct {
	Principal                            string  `json:"principal"`
	PurchasingDocument                   string  `json:"purchasingDocument"`
	Position                             float64 `json:"position"`
	DispatchPoint                        string  `json:"dispatchPoint"`
	ShippingPositionDescription          string  `json:"shippingPositionDescription"`
	Batch                                string  `json:"batch"`
	DocumentPosition                     string  `json:"documentPosition"`
	EraseIndicator                       string  `json:"eraseIndicator"`
	Origin                               string  `json:"origin"`
	LastModification                     string  `json:"lastModification"`
	ShortText                            string  `json:"shortText"`
	Material                             string  `json:"material"`
	ShortMaterialText                    string  `json:"shortMaterialText"`
	ShortMaterialMatchcodes              string  `json:"shortMaterialMatchcodes"`
	ExtSunatCode                         string  `json:"extSunatCode"`
	MaterialBaseMeasurementUnit          string  `json:"materialBaseMeasurementUnit"`
	MaterialE                            string  `json:"materialE"`
	Society                              string  `json:"society"`
	CompanyName                          string  `json:"companyName"`
	Center                               string  `json:"center"`
	NameCenter                           string  `json:"nameCenter"`
	Store                                string  `json:"store"`
	WarehouseName                        string  `json:"warehouseName"`
	NeedNumber                           string  `json:"needNumber"`
	ItemGroup                            string  `json:"itemGroup"`
	PurchasingInformation                string  `json:"purchasingInformation"`
	SupplierNumber                       string  `json:"supplierNumber"`
	PlannedQuantity                      string  `json:"plannedQuantity"`
	OrderQuantity                        string  `json:"orderQuantity"`
	OrderedUnitMeasure                   string  `json:"orderedUnitMeasure"`
	UmAskingPrice                        string  `json:"umAskingPrice"`
	QuantityConversion1                  float64 `json:"quantityConversion1"`
	QuantityConversion2                  float64 `json:"quantityConversion2"`
	Corresponds                          float64 `json:"corresponds"`
	Denominator                          float64 `json:"denominator"`
	NetAskingPrice                       float64 `json:"netAskingPrice"`
	BaseQuantity                         float64 `json:"baseQuantity"`
	NetOrderValue                        float64 `json:"netOrderValue"`
	GrossOrderedValue                    float64 `json:"grossOrderedValue"`
	OfferPeriod                          string  `json:"offerPeriod"`
	EmTreatmentTime                      float64 `json:"emTreatmentTime"` //estaba antes asi EMTreatmentTime
	TaxIndicator                         string  `json:"taxIndicator"`
	BeginningTaxRateValidity             string  `json:"beginningTaxRateValidity"`
	TaxDate                              string  `json:"taxDate"`
	Country                              string  `json:"country"`
	SettlementGroup1                     string  `json:"settlementGroup1"`
	StockType                            string  `json:"stockType"`
	ActInfo                              string  `json:"actInfo"`
	PricePrinting                        string  `json:"pricePrinting"`
	EstimatedPrice                       string  `json:"estimatedPrice"`
	NumberClaims                         float64 `json:"numberClaims"`
	FirstClaim                           float64 `json:"firstClaim"`
	SecondClaim                          float64 `json:"secondClaim"`
	ThirdClaim                           float64 `json:"thirdClaim"`
	TolExcSupply                         float64 `json:"tolExcSupply"`
	ExcessSupply                         string  `json:"excessSupply"`
	TolerateSupplyFaults                 float64 `json:"tolerateSupplyFaults"`
	ValuationClass                       string  `json:"valuationClass"`
	ValuationType                        string  `json:"valuationType"`
	RejectionIndicator                   string  `json:"rejectionIndicator"`
	OfferCharacteristics                 string  `json:"offerCharacteristics"`
	CompleteDelivery                     string  `json:"completeDelivery"`
	FinalBill                            string  `json:"finalBill"`
	PositionType                         string  `json:"positionType"`
	AllocationType                       string  `json:"allocationType"`
	Consumption                          string  `json:"consumption"`
	DistributionIndustry                 string  `json:"distributionIndustry"`
	PartialInvoice                       string  `json:"partialInvoice"`
	GoodsEntry                           string  `json:"goodsEntry"`
	NotValued                            string  `json:"notValued"`
	ReceiptInvoices                      string  `json:"receiptInvoices"`
	BaseVerification                     string  `json:"baseVerification"`
	ConfirmationRequired                 string  `json:"confirmationRequired"`
	OrderConfirmation                    string  `json:"orderConfirmation"`
	FrameworkContract                    string  `json:"frameworkContract"`
	PostContractSup                      string  `json:"postContractSup"`
	ArrangedDate                         string  `json:"arrangedDate"`
	CaConcert                            float64 `json:"caConcert"` //antes estaba asi CAConcert
	FixationPeriod1                      float64 `json:"fixationPeriod1"`
	FixationPeriod2                      float64 `json:"fixationPeriod2"`
	NecessaryPlanningObligations         string  `json:"necessaryPlanningObligations"`
	ExclusionIndicator                   string  `json:"exclusionIndicator"`
	BaseMeasurementUnit                  string  `json:"baseMeasurementUnit"`
	ShippingRules                        string  `json:"shippingRules"`
	FrameContrPrev                       float64 `json:"frameContrPrev"`
	NonDeductible                        float64 `json:"nonDeductible"`
	QuantityStandOrderDelivery           float64 `json:"quantiyStandOrderDelivery"`
	PriceDate                            string  `json:"priceDate"`
	PurchaseDocumentType                 string  `json:"purchaseDocumentType"`
	EffectiveValue                       float64 `json:"effectiveValue"`
	CommittedRelease                     string  `json:"committedRelease"`
	Customer                             string  `json:"customer"`
	Address                              string  `json:"address"`
	ConditionGroup                       string  `json:"conditionGroup"`
	WithoutDiscount                      string  `json:"withoutDiscount"`
	Status                               string  `json:"status"`
	PreliminaryDeliveryTime              float64 `json:"preliminaryDeliveryTime"`
	NetWeight                            float64 `json:"netWeight"`
	WeightUnit                           string  `json:"weightUnit"`
	TaxResidence                         string  `json:"taxResidence"`
	RelevantImpression                   string  `json:"relevantImpression"`
	SpecialStock                         string  `json:"specialStock"`
	SettlementReserve                    string  `json:"settlementReserve"`
	LiquidReserve                        string  `json:"liquidReserve"`
	Unmodifiable                         string  `json:"unmodifiable"`
	QmControlKey                         string  `json:"qmControlKey"` //antes estaba asi QMControlKey
	CertificateType                      string  `json:"certificateType"`
	EanCode                              string  `json:"eanCode"` //antes estaba asi EANCode
	ConfirmationControl                  string  `json:"confirmationControl"`
	ReviewStatus                         string  `json:"reviewStatus"`
	Money                                string  `json:"money"`
	ManagementCenter                     string  `json:"managementCenter"`
	BudgetPost                           string  `json:"budgetPost"`
	DivisionNotifiedPartner              string  `json:"divisionNotifiedPartner"`
	SupposedDivisionInterlocutor         string  `json:"supposedDivisionInterlocutor"`
	ProfitCenter                         string  `json:"profitCenter"`
	Interlocutor                         string  `json:"interlocutor"`
	PriceDateControl                     string  `json:"PriceDateControl"`
	GrossWeight                          float64 `json:"grossWeight"`
	Volume                               float64 `json:"volume"`
	VolumeUnit                           string  `json:"volumeUnit"`
	Incoterms1                           string  `json:"incoterms"`
	Incoterms2                           string  `json:"incoterms2"`
	PriorApprove                         string  `json:"priorApprove"`
	PreviousSupplier                     string  `json:"previousSupplier"`
	SupplierParkSupply                   string  `json:"supplierParkSupply"`
	PackageNumber                        string  `json:"packageNumber"`
	BillingPlanNumber                    string  `json:"billingPlanNumber"`
	NetOrderValue2                       float64 `json:"netOrderValue2"`
	Statistics                           string  `json:"statistics"`
	TopPosition                          string  `json:"topPosition"`
	LatestDate                           string  `json:"latestDate"`
	Supplier                             string  `json:"supplier"`
	SubcontractedSupplier                string  `json:"subcontractedSupplier"`
	MatConfig                            string  `json:"matConfig"`
	MaterialCategory                     string  `json:"materialCategory"`
	ShippingClass                        string  `json:"shippingClass"`
	PlaceDelivery                        string  `json:"placeDelivery"`
	ProductSupply                        string  `json:"productSupply"`
	Address2                             string  `json:"address2"`
	DeliveryAddressClass                 string  `json:"deliveryAddressClass"`
	InternalObjectNumber                 string  `json:"internalObjectNumber"`
	SelfBilling                          string  `json:"selfBilling"`
	LiquidBased                          string  `json:"liquidBased"`
	DateModificationTransmitted          string  `json:"dateModificationTransmitted"`
	TransmissionTime                     string  `json:"transmissionTime"`
	NextTransmissionNumber               string  `json:"nextTransmissionNumber"`
	TradePromotion                       string  `json:"tradePromotion"`
	AllocationTable                      string  `json:"allocationTable"`
	Position2                            string  `json:"position2"`
	Points                               float64 `json:"points"`
	PointUnit                            string  `json:"pointUnit"`
	Season                               string  `json:"season"`
	SeasonYear                           string  `json:"seasonYear"`
	SettlementGroup2                     string  `json:"settlementGroup2"`
	SettlementGroup3                     string  `json:"settlementGroup3"`
	LiquidPosterior                      string  `json:"liquidPosterior"`
	AssetLedger                          string  `json:"assetLedger"`
	MinDurationTime                      float64 `json:"minDurationTime"`
	OfferPetition                        string  `json:"offerPetition"`
	Position3                            string  `json:"position3"`
	ConfigurationOrigin                  string  `json:"configurationOrigin"`
	UseQuotaRegulation                   string  `json:"useQuotaRegulation"`
	TransferIndicator                    string  `json:"transferIndicator"`
	OrderRequest                         string  `json:"orderRequest"`
	PosRequestOrder                      string  `json:"posRequestOrder"`
	MaterialType                         string  `json:"materialType"`
	SubPositionType                      string  `json:"subpositionType"`
	SubPositions                         string  `json:"subpositions"`
	Subtotal1                            float64 `json:"subtotal1"`
	Subtotal2                            float64 `json:"subtotal2"`
	Subtotal3                            float64 `json:"subtotal3"`
	Subtotal4                            float64 `json:"subtotal4"`
	Subtotal5                            float64 `json:"subtotal5"`
	Subtotal6                            float64 `json:"subtotal6"`
	TreatmentKey                         string  `json:"treatmentKey"`
	QtyAccumMaxRelease                   float64 `json:"qtyAccumMaxRelease"`
	QtyAccumMaxReleaseFabr               float64 `json:"qtyAccumMaxReleaseFabr"`
	ReturnPosition                       string  `json:"returnPosition"`
	RelayAssignedTable                   string  `json:"relayAssignedTable"`
	ReasonOrder                          string  `json:"reasonOrder"`
	ReturnDeliveryClass                  string  `json:"returnDeliveryClass"`
	MaterialCarryingGroup                string  `json:"materialCarryingGroup"`
	KindBonus                            string  `json:"kindBonus"`
	NcmCode                              string  `json:"ncmCode"`
	MaterialUtilization                  string  `json:"materialUtilization"`
	MaterialOrigin                       string  `json:"materialOrigin"`
	OwnManufacturing                     string  `json:"ownManufacturing"`
	CfopTypeMaterial                     string  `json:"cfopTypeMaterial"`
	DeliveryOrderCreationProfile         string  `json:"deliveryOrderCreationProfile"`
	NextOrderDeterminationDeliverySupply string  `json:"nextOrderDeterminationDeliverySupply"`
	NextTransOrdEntrg                    string  `json:"nextTransOrdEntrg"`
	SpecialStockValue                    string  `json:"specialStockValue"`
	RappellingBase                       float64 `json:"rappellingBase"`
	InputExact                           string  `json:"inputExact"`
	LoadingUnloadingPoint                string  `json:"loadingUnloadingPoint"`
	InflationIndex                       string  `json:"inflationIndex"`
	InflationIndexDate                   string  `json:"inflationIndexDate"`
	FabricPartsProfile                   string  `json:"fabricPartsProfile"`
	FinalDelivery                        string  `json:"finalDelivery"`
	PartialPosDelivery                   string  `json:"partialPosDelivery"`
	UseMeasure                           string  `json:"useMeasure"`
	RoundingProfile                      string  `json:"roundingProfile"`
	StandardValuation                    string  `json:"standardValuation"`
	ModifiedConfiguration                string  `json:"modifiedConfiguration"`
	NoInvoicePosition                    string  `json:"noInvoicePosition"`
	ManufacturerPartNumber               string  `json:"manufacturerPartNumber"`
	Maker                                string  `json:"maker"`
	ExternalManufacturer                 string  `json:"externalManufacturer"`
	ShipmentLock                         string  `json:"shipmentLock"`
	Applicant                            string  `json:"applicant"`
	TimeZone                             string  `json:"timeZone"`
	ExpirationIndicator                  string  `json:"expirationIndicator"`
	VerificationInvoicesServices         string  `json:"verificationInvoicesServices"`
	NecArea                              string  `json:"necArea"`
	ConditionPositionInvoice             string  `json:"conditionPositionInvoice"`
	ExternalPlanning                     string  `json:"externalPlanning"`
	TypeTransfer                         string  `json:"typeTransfer"`
	Grant                                string  `json:"grant"`
	FunctionalArea                       string  `json:"functionalArea"`
	PositionStatus                       string  `json:"positionStatus"`
	IssuingWarehouse                     string  `json:"issuingWarehouse"`
	BudgetDocument                       string  `json:"budgetDocument"`
	DocumentPosition2                    string  `json:"documentPosition2"`
	Element                              string  `json:"element"`
	CostCenter                           string  `json:"costCenter"`
	GeneralLedgerAccount                 string  `json:"generalLedgerAccount"`
	SupplierAcceptance                   string  `json:"supplierAcceptance"`
	CommittedServiceBased                string  `json:"committedServiceBased"`
	UrgentNeed                           string  `json:"urgentNeed"`
	NecessaryPriority                    string  `json:"necessaryPriority"`
	ReceptionPoint                       string  `json:"receptionPoint"`
	CreationDifferenceInvoice            string  `json:"creationDifferenceInvoice"`
	RiskRelevance                        string  `json:"riskRelevance"`
	CreationDate                         string  `json:"creationDate"`
	CreationTime                         string  `json:"creationTime"`
	ValueChainCategory                   string  `json:"valueChainCategory"`
	ReasonForRejection                   string  `json:"reasonForRejection"`
	CrmCustomerOrderNumber               string  `json:"crmCustomerOrderNumber"`
	CrmCustomerOrderItemNumber           string  `json:"crmCustomerOrderItemNumber"`
	CrmReferenceOrderNumber              string  `json:"crmReferenceOrderNumber"`
	CrmReferencePositionNumber           string  `json:"crmReferencePositionNumber"`
	CrmInvoiceRelevance                  string  `json:"crmInvoiceRelevance"`
	ModifiedSystemCategory               string  `json:"modifiedSystemCategory"`
	IssuerWarehouseStockType             string  `json:"issuerWarehouseStockType"`
	ControlType                          string  `json:"controlType"`
	TransferInputOrder                   string  `json:"transferInputOrder"`
	CauseCode                            string  `json:"causeCode"`
	AccumulateDivertedOrders             float64 `json:"accumulateDivertedOrders"`
	QuantitySerialNumbers                int     `json:"quantitySerialNumbers"`
	ViewTotalBaseEWM                     string  `json:"viewTotalBaseEWM"`
	HierarchyNumber                      string  `json:"hierarchyNumber"`
	ClassificationExternalNumber         string  `json:"classificationExternalNumber"`
	ExternalHierarchyType                string  `json:"externalHierarchyType"`
	RetentionPercentage                  float64 `json:"retentionPercentage"`
	Advance                              string  `json:"advance"`
	AdvancePaymentPercentage             float64 `json:"advancePaymentPercentage"`
	AdvanceAmount                        float64 `json:"advanceAmount"`
	AdvancePaymentDueDate                string  `json:"advancePaymentDueDate"`
	StoreReturn                          string  `json:"storeReturn"`
	DocumentNumberExternalDocument       string  `json:"documentNumberExternalDocument"`
	ExternalPositionNumber               string  `json:"externalPositionNumber"`
	LogicalSystem                        string  `json:"logicalSystem"`
	CentralOpenRequest                   string  `json:"centralOpenRequest"`
	CentralOpenorderResponsePosition     string  `json:"centralOpenorderResponsePosition"`
	MerchandiseCountCorrection           string  `json:"merchandiseCountCorrection"`
	ExternalDeliveryId                   string  `json:"externalDeliveryId"`
	ExternalPos                          string  `json:"externalPos"`
	MotBloqIdentifier                    string  `json:"motBloqIdentifier"`
	MotivBloqText                        string  `json:"motivBloqText"`
	AccountConsumptionOport              string  `json:"accountConsumptionOport"`
	FixedDateQuantity                    string  `json:"fixedDateQuantity"`
	MechanicalOutputReference            string  `json:"mechanicalOutputReference"`
	CompleteSupply                       string  `json:"completeSupply"`
	IncotermsPlace1                      string  `json:"incotermsPlace1"`
	IncotermsPlace2                      string  `json:"incotermsPlace2"`
	IncotermLocation1                    string  `json:"incotermLocation1"`
	IncotermLocation2                    string  `json:"incotermLocation2"`
	DeviationDestiny                     string  `json:"deviationDestiny"`
	GoodsCode                            string  `json:"goodsCode"`
	IntrastatServiceCode                 string  `json:"intrastatServiceCode"`
	BorderCrossingValue                  float64 `json:"borderCrossingValue"`
	ServiceProvider                      string  `json:"serviceProvider"`
	ProductTypeGroup                     string  `json:"productTypeGroup"`
	Emhes                                string  `json:"emhes"`
	PriceModification                    string  `json:"priceModification"`
	OfferPetition2                       string  `json:"offerPetition2"`
	PositionNumberRFQ                    string  `json:"positionNumberRFQ"`
	RenegotiationStatus                  string  `json:"renegotiationStatus"`
	SupplierVerificationStatus           string  `json:"supplierVerificationStatus"`
	ProductMarketStatus                  string  `json:"productMarketStatus"`
	DangerousGoodsStatus                 string  `json:"dangerousGoodsStatus"`
	SafetyDataSheetStatus                string  `json:"safetyDataSheetStatus"`
	Material2                            string  `json:"material2"`
	ConnectedSystemID                    string  `json:"connectedSystemID"`
	ExpectedPositionValue                float64 `json:"expectedPositionValue"`
	ExternalReferenceID                  string  `json:"externalReferenceID"`
	CodeAutomaticallyDetermined          string  `json:"codeAutomaticallyDetermined"`
	CodeReasonManual                     string  `json:"codeReasonManual"`
	IncentiveType                        string  `json:"incentiveType"`
	SubjectTaxSubstitution               string  `json:"subjectTaxSubstitution"`
	IncentiveId                          string  `json:"incentiveId"`
	OriginJurisdCode                     string  `json:"originJurisdCode"`
	IncludesExtensibility                string  `json:"includesExtensibility"`
	ExpectedValue                        float64 `json:"expectedValue"`
	GlobalLimit                          float64 `json:"globalLimit"`
	OpenPurchaseOrderLimit               string  `json:"openPurchaseOrderLimit"`
	StartDate                            string  `json:"startDate"`
	EndDate                              string  `json:"endDate"`
	PercentageRate                       float64 `json:"percentageRate"`
	WorkingTimeHours                     string  `json:"workingTimeHours"`
	DataFilterValue                      string  `json:"dataFilterValue"`
	UniqueProjectCode                    string  `json:"uniqueProjectCode"`
	CompetitionIdentification            string  `json:"competitionIdentification"`
	MonitoringMajorWorks                 string  `json:"monitoringMajorWorks"`
	BusinessTransaction                  string  `json:"businessTransaction"`
	CustomerUsage                        string  `json:"customerUsage"`
	UsagePurpose                         string  `json:"usagePurpose"`
	GeneratedPosition                    string  `json:"generatedPosition"`
	FreeDependency                       string  `json:"freeDependency"`
	StructureCategory                    string  `json:"structureCategory"`
	InfoCode                             string  `json:"infoCode"`
	Budget                               string  `json:"budget"`
	EntryPeriod                          string  `json:"entryPeriod"`
	USGovernmentCamp                     string  `json:"usGovernmentCamp"`
	RelevantIUID                         string  `json:"relevantIUID"`
	MaxRetailPriceRelevance              string  `json:"maxRetailPriceRelevance"`
	StockSegment                         string  `json:"stockSegment"`
	NeedSegment                          string  `json:"needSegment"`
	TransportationReferenceUuid          string  `json:"transportationReferenceUuid"`
	Location1                            string  `json:"location1"` //cambie tipo de dato float64
	Location2                            string  `json:"location2"`
	CharacteristicDesignation1           string  `json:"characteristicDesignation1"`
	CharacteristicDesignation2           string  `json:"characteristicDesignation2"`
	CharacteristicDesignation3           string  `json:"characteristicDesignation3"`
	ShoppingReferralCenter               string  `json:"shoppingReferralCenter"`
	DetailNumber                         string  `json:"detailNumber"`
	Optionality                          string  `json:"optionality"`
	MaxIcValue                           string  `json:"maxIcValue"`
	PositionType2                        string  `json:"positionType2"`
	EffectiveValidity                    string  `json:"effectiveValidity"`
	Cash                                 string  `json:"cash"`
	OptionItem                           string  `json:"optionItem"`
	PostingCategoryDetails               string  `json:"postingCategoryDetails"`
	FasCodeHeader                        string  `json:"fasCodeHeader"`
	ProgrammingDesk                      string  `json:"programmingDesk"`
	MixedProductNumber                   string  `json:"mixedProductNumber"`
	Product                              string  `json:"product"`
	PostedDate                           string  `json:"postedDate"`
	Accounted                            string  `json:"accounted"`
	UmInvoice                            string  `json:"umInvoice"`
	AnnexingPackageKey                   string  `json:"annexingPackageKey"`
	AnnexingPackageExtend                string  `json:"annexingPackageExtend"`
	BaseDate                             string  `json:"baseDate"`
	AnnexingDateType                     string  `json:"annexingDateType"`
	AnnexingStartDate                    string  `json:"annexingStartDate"`
	DeviationPercentage                  float64 `json:"deviationPercentage"`
	AnnexedIndicator                     string  `json:"annexedIndicator"`
	LimitDate                            string  `json:"limitDate"`
	Numerator                            string  `json:"numerator"`
	NewBaseDate                          string  `json:"newBaseDate"`
	AccountantGeneralMethod              string  `json:"accountantGeneralMethod"`
	NegativeAnnexing                     string  `json:"negativeAnnexing"`
	PurchasingOrganization               string  `json:"purchasingOrganization"`
	KnownIndexIndicator                  string  `json:"knownIndexIndicator"`
	GlobalPositionNumber                 string  `json:"gobalPositionNumber"`
	OfferPositionNumber                  string  `json:"offerPositionNumber"`
	ModelIDCode                          string  `json:"modelIDCode"`
	OrderPriority                        string  `json:"orderPriority"`
	DeliveryPriority                     string  `json:"deliveryPriority"`
	AircraftRegistrationNumber           string  `json:"aircraftRegistrationNumber"`
	Position1                            string  `json:"position1"`
	ConfirmationClass                    string  `json:"confirmationClass"`
	DocumentDate                         string  `json:"documentDate"`
	Quotation                            string  `json:"quotation"`
	MessageS1pnstat                      string  `json:"messageS1pnstat"`
	DoNotReplace                         string  `json:"doNotReplace"`
	DemandPriority1                      string  `json:"demandPriority1"`
	DemandPriority2                      string  `json:"demandPriority2"`
	ArunOrderPriority                    int     `json:"arunOrderPriority"`
	Subcontracting                       string  `json:"subcontracting"`
	ProfileSerialNumber                  string  `json:"profileSerialNumber"`
	SpecialStock2                        string  `json:"specialStock2"`
	ElementPEP                           string  `json:"elementPEP"`
	Customer2                            string  `json:"customer2"`
	CommercialDocument                   string  `json:"commercialDocument"`
	PositionSD                           string  `json:"positionSD"`
	StockOwner                           string  `json:"stockOwner"`
	SeasonalYear                         string  `json:"seasonalYear"`
	Season2                              string  `json:"season2"`
	Collection                           string  `json:"collection"`
	Issue                                string  `json:"issue"`
	StartDateATP                         string  `json:"startDateATP"`
	RelevantSVA                          string  `json:"relevantSVA"`
	Position4                            string  `json:"position4"`
	TransactionNumber                    string  `json:"transactionNumber"`
	PositionGroup                        string  `json:"positionGroup"`
	PositionNumber                       string  `json:"positionNumber"`
	OrderSchedulingStrategy              string  `json:"orderSchedulingStrategy"`
	MatrixRegistrationNumber             string  `json:"matrixRegistrationNumber"`
	PfmPartId                            string  `json:"pfmPartId"`
	ConfirmedQuantity                    float64 `json:"confirmedQuantity"`
	HighQuantityRejection                string  `json:"highQuantityRejection"`
	DeviationProcessStatus               string  `json:"deviationProcessStatus"`
	SeasonIntegrityIndicator             string  `json:"seasonIntegrityIndicator"`
	ActivateOverride                     string  `json:"activateOverride"`
	DischargePoint1                      string  `json:"dischargePoint1"`
	DischargePoint2                      string  `json:"dischargePoint2"`
	AddressNumber                        string  `json:"addressNumber"`
	CurrentNumber                        string  `json:"currentNumber"`
	DuringRegistration                   string  `json:"duringRegistration"`
	Department                           string  `json:"department"`
	BudgetDocument2                      string  `json:"budgetDocument2"`
	DocumentPosition3                    string  `json:"documentPosition3"`
	CommitmentDocument                   string  `json:"commitmentDocument"`
	CommitmentItem                       string  `json:"commitmentItem"`
	ElementWbs                           string  `json:"elementWbs"`
	PsstGroupingRule                     string  `json:"psstGroupingRule"`
	PsstGroup                            string  `json:"psstGroup"`
	ReferenceDocumentOrder               string  `json:"referenceDocumentOrder"`
	ReferenceOrder                       float64 `json:"referenceOrder"`
	ReferencePartitionAction             string  `json:"referencePartitionAction"`
	DistributionItemNumber               float64 `json:"distributionItemNumber"`
	ReferencePosition                    float64 `json:"referencePosition"`
	OriginProfile                        string  `json:"originProfile"`
	KeySourceSystem                      string  `json:"keySourceSystem"`
	TriggerIndicator                     string  `json:"triggerIndicator"`
	OrderListItemNumber                  string  `json:"orderListItemNumber"`
	PreferentialConsignment              string  `json:"preferentialConsignment"`
}
