package order

import (
	"bytes"
	"context"
	"crypto/tls"
	"encoding/xml"
	"fmt"
	"io/ioutil"
	"net/http"

	"dev.azure.com/ciaalicorp/CIA-Funciones/cia-library-domain-alicorp.git/customerror"
	"dev.azure.com/ciaalicorp/CIA-Funciones/cia-library-extension-rkgin-tracing.git/v2/register"

	"notas/model"
)

const (
	_headerContentType      = "Content-Type"
	_headerContentTypeValue = "text/xml;charset=UTF-8"
)

// namespaces xml
const (
	nsSoap = "http://schemas.xmlsoap.org/soap/envelope/"
	nsURN  = "urn:sap-com:document:sap:rfc:functions"
)

type Order struct {
	config model.ConfigSoaps
}

func New(config model.ConfigSoaps) Order {

	return Order{config: config}
}
func (r Order) Order(ctx context.Context, request model.RemissionOrderRequest) (model.RemissionOrderResponse, error) {
	requestBody := RequestBody{RequestRecovery: RequestRecovery{
		PciMotivo:  request.ReasonConsultation,
		PciTipoRef: request.ReferenceType,
		PciBukrs:   request.Society,
		PciLifnr:   request.SupplierCode,
		PciReswk:   request.SupplyCenter,
		PciBsart:   request.DocumentType,
		PciAedat:   request.DateStart,
		PciAedat1:  request.DateEnd,
		PciEbelen:  request.DocumentNumber,
		PciEbelp:   request.DocumentPosition,
		PciMatnr:   request.MaterialNumber,
		PciWerks:   request.DestinationCenter,
	}}

	body, err := doRequestSoap(ctx, r.config, requestBody)
	if err != nil {
		return model.RemissionOrderResponse{}, fmt.Errorf("soap.order.doRequestSoap(): %w", err)
	}

	var response SoapResponseRecovery

	if err := xml.Unmarshal(body, &response); err != nil {
		return model.RemissionOrderResponse{}, fmt.Errorf("soap.order.GetOrder().xml.Unmarshal(): %w", err)

	}

	return makeOrder(response.Body.DataReturn), nil
}

func doRequestSoap(ctx context.Context, configSoap model.ConfigSoaps, payloadData interface{}) ([]byte, error) {
	dataSoap := SoapRequest{
		XMLNsSoap: nsSoap,
		XMLNsUrn:  nsURN,
		Header:    "",
		Body:      payloadData,
	}

	payload, err := xml.MarshalIndent(dataSoap, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("xml.MarshalIndent(): %w", err)
	}

	logTrace := register.NewServiceSoap(ctx, "soap.order.doRequest()")
	logTrace.RegisterRequest(configSoap.Url, string(payload), false)

	req, err := http.NewRequest(http.MethodGet, configSoap.Url, bytes.NewBuffer(payload))
	if err != nil {
		return nil, fmt.Errorf("NewRequest(): %w", err)
	}

	req.Header.Add(_headerContentType, _headerContentTypeValue)
	req.SetBasicAuth(configSoap.User, configSoap.Password)
	client := http.Client{Transport: &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}}
	res, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("DefaultClient: %w", err)
	}
	defer res.Body.Close()

	bodyBytes, err := ioutil.ReadAll(res.Body)
	if err != nil {
		return nil, fmt.Errorf("reading Body: %v", err)
	}

	logTrace.RegisterResponse(res.StatusCode, string(bodyBytes), false)

	if res.StatusCode != http.StatusOK {
		customErr := customerror.NewError()
		customErr.SetStatusHTTP(res.StatusCode)
		customErr.Fields.AddGeneric("sap_soap", "response_backend"+string(bodyBytes), customerror.IssueRequestBackendFailed)

		return nil, customErr
	}

	return bodyBytes, nil
}

func makeOrder(dataReturn DataReturn) model.RemissionOrderResponse {
	var response = model.RemissionOrderResponse{}

	responseHeader := make(model.HeaderOrders, 0)
	for _, header := range dataReturn.HeaderOrders {
		responseHeader = append(responseHeader, model.HeaderOrder{
			Principal:                           header.Principal,
			PurchasingDocument:                  header.PurchasingDocument,
			Society:                             header.Society,
			DescriptionSociety:                  header.DescriptionSociety,
			PurchasingDocumentType:              header.PurchasingDocumentType,
			PurchasingDocumentCI:                header.PurchasingDocumentCI,
			ControlIndicator:                    header.ControlIndicator,
			EraseIndicator:                      header.EraseIndicator,
			Status:                              header.Status,
			CreationDate:                        header.CreationDate,
			Author:                              header.Author,
			LastModification:                    header.LastModification,
			PositionInterval:                    header.PositionInterval,
			LastPosition:                        header.LastPosition,
			Supplier:                            header.Supplier,
			SupplierName:                        header.SupplierName,
			TypeNIF:                             header.TypeNIF,
			Nif:                                 header.Nif,
			LanguajeKey:                         header.LanguajeKey,
			PaymentCondition:                    header.PaymentCondition,
			Pay1:                                header.Pay1,
			Pay2:                                header.Pay2,
			Pay3:                                header.Pay3,
			Discount1:                           header.Discount1,
			Discount2:                           header.Discount2,
			PurchasingOrganization:              header.PurchasingOrganization,
			ShoppingGroup:                       header.ShoppingGroup,
			Currency:                            header.Currency,
			ExchangeRate:                        header.ExchangeRate,
			FixedExchangeRate:                   header.FixedExchangeRate,
			DocumentDate:                        header.DocumentDate,
			StartPeriodValidity:                 header.StartPeriodValidity,
			EndPeriodValidity:                   header.EndPeriodValidity,
			TenderDeadline:                      header.TenderDeadline,
			OfferPeriod:                         header.OfferPeriod,
			BindingTerm:                         header.BindingTerm,
			Warranty:                            header.Warranty,
			Tender:                              header.Tender,
			Offer:                               header.Offer,
			OfferDate:                           header.OfferDate,
			Reference:                           header.Reference,
			Seller:                              header.Seller,
			Phone:                               header.Phone,
			MerchandiseSupplier:                 header.MerchandiseSupplier,
			Customer:                            header.Customer,
			ActivePurchasingDocument:            header.ActivePurchasingDocument,
			FrameworkContract:                   header.FrameworkContract,
			NotUsed:                             header.NotUsed,
			CompleteSupply:                      header.CompleteSupply,
			MessageEM:                           header.MessageEM,
			SupplyCenter:                        header.SupplyCenter,
			ReceivingProvider:                   header.ReceivingProvider,
			Incoterms1:                          header.Incoterms1,
			Incoterms2:                          header.Incoterms2,
			ExpectedValue:                       header.ExpectedValue,
			DistributionClassPurchasingDocument: header.DistributionClassPurchasingDocument,
			Tender2:                             header.Tender2,
			DocumentConditionNumber:             header.DocumentConditionNumber,
			Scheme:                              header.Scheme,
			Current:                             header.Current,
			InvoiceIssuer:                       header.InvoiceIssuer,
			ForeignTradeData:                    header.ForeignTradeData,
			OurReference:                        header.OurReference,
			LogicalSystem:                       header.LogicalSystem,
			SubpositionInterval:                 header.SubpositionInterval,
			TemporaryConditions:                 header.TemporaryConditions,
			LiberationGroup:                     header.LiberationGroup,
			LiberationStrategy:                  header.LiberationStrategy,
			IndRelease:                          header.IndRelease,
			ReleaseStatus:                       header.ReleaseStatus,
			RelevantRelease:                     header.RelevantRelease,
			Country:                             header.Country,
			DeliveryOrderDocument:               header.DeliveryOrderDocument,
			Address:                             header.Address,
			CountryNIF:                          header.CountryNIF,
			CommunityNIF:                        header.CommunityNIF,
			ReasonRejection:                     header.ReasonRejection,
			DocumentNumber:                      header.DocumentNumber,
			Type:                                header.Type,
			Incomplete:                          header.Incomplete,
			PurchasingProcessStatus:             header.PurchasingProcessStatus,
			ProcessIndicator:                    header.ProcessIndicator,
			TotalReleaseValue:                   header.TotalReleaseValue,
			ModificationStatus:                  header.ModificationStatus,
			Version:                             header.Version,
			Scmproc:                             header.Scmproc,
			CauseCode:                           header.CauseCode,
			IncompleteDate:                      header.IncompleteDate,
			Retention:                           header.Retention,
			RetentionPercentage:                 header.RetentionPercentage,
			Advance:                             header.Advance,
			AdvancePercentage:                   header.AdvancePercentage,
			AdvanceAmount:                       header.AdvanceAmount,
			AdvancePaymentDueDate:               header.AdvancePaymentDueDate,
			ProcessIdNumber:                     header.ProcessIdNumber,
			OrderHierachyPart:                   header.OrderHierachyPart,
			GroupingID:                          header.GroupingID,
			SuperiorDocument:                    header.SuperiorDocument,
			ThresholdExchange:                   header.ThresholdExchange,
			LegalOrder:                          header.LegalOrder,
			LegalOrderDescription:               header.LegalOrderDescription,
			LegarOrderDate:                      header.LegarOrderDate,
			ShippingClass:                       header.ShippingClass,
			PlaceDelivery:                       header.PlaceDelivery,
			ShippingCondition:                   header.ShippingCondition,
			IncotermsVersion:                    header.IncotermsVersion,
			IncotermsPlace:                      header.IncotermsPlace,
			IncotermsPlace2:                     header.IncotermsPlace2,
			IncotermLocation1:                   header.IncotermLocation1,
			IncotermLocation2:                   header.IncotermLocation2,
			DeviationDestiny:                    header.DeviationDestiny,
			Currency2:                           header.Currency2,
			IntraRelevance:                      header.IntraRelevance,
			IntraExclude:                        header.IntraExclude,
			TotalStatusProducts:                 header.TotalStatusProducts,
			TotalStatusMarket:                   header.TotalStatusMarket,
			TotalStatusDangerous:                header.TotalStatusDangerous,
			TotalStatusSecurity:                 header.TotalStatusSecurity,
			OfferStartDate:                      header.OfferStartDate,
			FollowDocumentCategory:              header.FollowDocumentCategory,
			FollowDocumentType:                  header.FollowDocumentType,
			DummyOrder:                          header.DummyOrder,
			ExternarlSystem:                     header.ExternarlSystem,
			ExternalReference:                   header.ExternalReference,
			ExternalReviewing:                   header.ExternalReviewing,
			BusinessObjectiveAchieved:           header.BusinessObjectiveAchieved,
			DocumentOld:                         header.DocumentOld,
			UniqueId:                            header.UniqueId,
			Counter:                             header.Counter,
			TransferId:                          header.TransferId,
			TransferStageId:                     header.TransferStageId,
			SourceLogicalSystem:                 header.SourceLogicalSystem,
			TransactionNumber:                   header.TransactionNumber,
			PositionGroup:                       header.PositionGroup,
			SvaLastItem:                         header.SvaLastItem,
			OrderScheduleChange:                 header.OrderScheduleChange,
			TransportationSap:                   header.TransportationSap,
			ConsideredPaymentDate:               header.ConsideredPaymentDate,
			OperationNumber:                     header.OperationNumber,
			RenewalPeriod:                       header.RenewalPeriod,
			CancellationPeriod:                  header.CancellationPeriod,
			AnnexingPackageKey:                  header.AnnexingPackageKey,
			AnnexingPackageExtend:               header.AnnexingPackageExtend,
			BaseDate:                            header.BaseDate,
			AnnexingDateType:                    header.AnnexingDateType,
			AnnexingStartDate:                   header.AnnexingStartDate,
			DeviationPerecentage:                header.DeviationPerecentage,
			AnnexedIndicator:                    header.AnnexedIndicator,
			LimitDate:                           header.LimitDate,
			Numerator:                           header.Numerator,
			NewBaseDate:                         header.NewBaseDate,
			AccountGeneralMethod:                header.AccountGeneralMethod,
			NegativeAnnexing:                    header.NegativeAnnexing,
			PurchasingOrganization2:             header.PurchasingOrganization2,
			IndexIndicator:                      header.IndexIndicator,
			Postat:                              header.Postat,
			InterestIndicator:                   header.InterestIndicator,
			InstantStatus:                       header.InstantStatus,
			ProcedureNumber:                     header.ProcedureNumber,
			Adjustment:                          header.Adjustment,
			ContractType:                        header.ContractType,
			LegalCompetence:                     header.LegalCompetence,
			Miscellaneous:                       header.Miscellaneous,
			Despatch:                            header.Despatch,
			DespDate:                            header.DespDate,
			DespJob:                             header.DespJob,
			Assesment:                           header.Assesment,
			AssesmentDate:                       header.AssesmentDate,
			AssesmentJob:                        header.AssesmentJob,
			Contract:                            header.Contract,
			DocumentType:                        header.DocumentType,
			SameDelliveryDate:                   header.SameDelliveryDate,
			SameCenter:                          header.SameCenter,
			FixedDateCommercial:                 header.FixedDateCommercial,
			ConsiderPurchasingGroup:             header.ConsiderPurchasingGroup,
			ConsiderCenter:                      header.ConsiderCenter,
			ConsiderOpenOrders:                  header.ConsiderOpenOrders,
			ConsiderPositionType:                header.ConsiderPositionType,
			FixedOperation:                      header.FixedOperation,
			ConsiderBudget:                      header.ConsiderBudget,
			ConsiderReleaveAssignment:           header.ConsiderReleaveAssignment,
			ConsiderDeliveryPeriod:              header.ConsiderDeliveryPeriod,
			ConsiderDeliveryDate:                header.ConsiderDeliveryDate,
			ConsiderSupllier:                    header.ConsiderSupllier,
			VerificationLevel:                   header.VerificationLevel,
			ConditionClass:                      header.ConditionClass,
			BudgetNumber:                        header.BudgetNumber,
			BudgetNecessary:                     header.BudgetNecessary,
			Coin:                                header.Coin,
			BudgetReserved:                      header.BudgetReserved,
			BudgetSpecial:                       header.BudgetSpecial,
			JustificationProfile:                header.JustificationProfile,
			BudgetClass:                         header.BudgetClass,
			VerificationStatus:                  header.VerificationStatus,
			Justification:                       header.Justification,
			CheckType:                           header.CheckType,
			OpenOrders:                          header.OpenOrders,
			OpenOrdersLevel:                     header.OpenOrdersLevel,
			OpenOrdersDistribution:              header.OpenOrdersDistribution,
		})
	}

	responseDetail := make(model.DetailOrders, 0)
	for _, detail := range dataReturn.DetailOrders {
		responseDetail = append(responseDetail, model.DetailOrder{
			Principal:                            detail.Principal,
			PurchasingDocument:                   detail.PurchasingDocument,
			Position:                             detail.Position,
			DispatchPoint:                        detail.DispatchPoint,
			ShippingPositionDescription:          detail.ShippingPositionDescription,
			Batch:                                detail.Batch,
			DocumentPosition:                     detail.DocumentPosition,
			EraseIndicator:                       detail.EraseIndicator,
			Origin:                               detail.Origin,
			LastModification:                     detail.LastModification,
			ShortText:                            detail.ShortText,
			Material:                             detail.Material,
			ShortMaterialText:                    detail.ShortMaterialText,
			ShortMaterialMatchcodes:              detail.ShortMaterialMatchcodes,
			ExtSunatCode:                         detail.ExtSunatCode,
			MaterialBaseMeasurementUnit:          detail.MaterialBaseMeasurementUnit,
			MaterialE:                            detail.MaterialE,
			Society:                              detail.Society,
			CompanyName:                          detail.CompanyName,
			Center:                               detail.Center,
			NameCenter:                           detail.NameCenter,
			Store:                                detail.Store,
			WarehouseName:                        detail.WarehouseName,
			NeedNumber:                           detail.NeedNumber,
			ItemGroup:                            detail.ItemGroup,
			PurchasingInformation:                detail.PurchasingInformation,
			SupplierNumber:                       detail.SupplierNumber,
			PlannedQuantity:                      detail.PlannedQuantity,
			OrderQuantity:                        detail.OrderQuantity,
			OrderedUnitMeasure:                   detail.OrderedUnitMeasure,
			UmAskingPrice:                        detail.UmAskingPrice,
			QuantityConversion1:                  detail.QuantityConversion1,
			QuantityConversion2:                  detail.QuantityConversion2,
			Corresponds:                          detail.Corresponds,
			Denominator:                          detail.Denominator,
			NetAskingPrice:                       detail.NetAskingPrice,
			BaseQuantity:                         detail.BaseQuantity,
			NetOrderValue:                        detail.NetOrderValue,
			GrossOrderedValue:                    detail.GrossOrderedValue,
			OfferPeriod:                          detail.OfferPeriod,
			EmTreatmentTime:                      detail.EmTreatmentTime,
			TaxIndicator:                         detail.TaxIndicator,
			BeginningTaxRateValidity:             detail.BeginningTaxRateValidity,
			TaxDate:                              detail.TaxDate,
			Country:                              detail.Country,
			SettlementGroup1:                     detail.SettlementGroup1,
			StockType:                            detail.StockType,
			ActInfo:                              detail.ActInfo,
			PricePrinting:                        detail.PricePrinting,
			EstimatedPrice:                       detail.EstimatedPrice,
			NumberClaims:                         detail.NumberClaims,
			FirstClaim:                           detail.FirstClaim,
			SecondClaim:                          detail.SecondClaim,
			ThirdClaim:                           detail.ThirdClaim,
			TolExcSupply:                         detail.TolExcSupply,
			ExcessSupply:                         detail.ExcessSupply,
			TolerateSupplyFaults:                 detail.TolerateSupplyFaults,
			ValuationClass:                       detail.ValuationClass,
			ValuationType:                        detail.ValuationType,
			RejectionIndicator:                   detail.RejectionIndicator,
			OfferCharacteristics:                 detail.OfferCharacteristics,
			CompleteDelivery:                     detail.CompleteDelivery,
			FinalBill:                            detail.FinalBill,
			PositionType:                         detail.PositionType,
			AllocationType:                       detail.AllocationType,
			Consumption:                          detail.Consumption,
			DistributionIndustry:                 detail.DistributionIndustry,
			PartialInvoice:                       detail.PartialInvoice,
			GoodsEntry:                           detail.GoodsEntry,
			NotValued:                            detail.NotValued,
			ReceiptInvoices:                      detail.ReceiptInvoices,
			BaseVerification:                     detail.BaseVerification,
			ConfirmationRequired:                 detail.ConfirmationRequired,
			OrderConfirmation:                    detail.OrderConfirmation,
			FrameworkContract:                    detail.FrameworkContract,
			PostContractSup:                      detail.PostContractSup,
			ArrangedDate:                         detail.ArrangedDate,
			CaConcert:                            detail.CaConcert,
			FixationPeriod1:                      detail.FixationPeriod1,
			FixationPeriod2:                      detail.FixationPeriod2,
			NecessaryPlanningObligations:         detail.NecessaryPlanningObligations,
			ExclusionIndicator:                   detail.ExclusionIndicator,
			BaseMeasurementUnit:                  detail.BaseMeasurementUnit,
			ShippingRules:                        detail.ShippingRules,
			FrameContrPrev:                       detail.FrameContrPrev,
			NonDeductible:                        detail.NonDeductible,
			QuantityStandOrderDelivery:           detail.QuantityStandOrderDelivery,
			PriceDate:                            detail.PriceDate,
			PurchaseDocumentType:                 detail.PurchaseDocumentType,
			EffectiveValue:                       detail.EffectiveValue,
			CommittedRelease:                     detail.CommittedRelease,
			Customer:                             detail.Customer,
			Address:                              detail.Address,
			ConditionGroup:                       detail.ConditionGroup,
			WithoutDiscount:                      detail.WithoutDiscount,
			Status:                               detail.Status,
			PreliminaryDeliveryTime:              detail.PreliminaryDeliveryTime,
			NetWeight:                            detail.NetWeight,
			WeightUnit:                           detail.WeightUnit,
			TaxResidence:                         detail.TaxResidence,
			RelevantImpression:                   detail.RelevantImpression,
			SpecialStock:                         detail.SpecialStock,
			SettlementReserve:                    detail.SettlementReserve,
			LiquidReserve:                        detail.LiquidReserve,
			Unmodifiable:                         detail.Unmodifiable,
			QmControlKey:                         detail.QmControlKey,
			CertificateType:                      detail.CertificateType,
			EanCode:                              detail.EanCode,
			ConfirmationControl:                  detail.ConfirmationControl,
			ReviewStatus:                         detail.ReviewStatus,
			Money:                                detail.Money,
			ManagementCenter:                     detail.ManagementCenter,
			BudgetPost:                           detail.BudgetPost,
			DivisionNotifiedPartner:              detail.DivisionNotifiedPartner,
			SupposedDivisionInterlocutor:         detail.SupposedDivisionInterlocutor,
			ProfitCenter:                         detail.ProfitCenter,
			Interlocutor:                         detail.Interlocutor,
			PriceDateControl:                     detail.PriceDateControl,
			GrossWeight:                          detail.GrossWeight,
			Volume:                               detail.Volume,
			VolumeUnit:                           detail.VolumeUnit,
			Incoterms1:                           detail.Incoterms1,
			Incoterms2:                           detail.Incoterms2,
			PriorApprove:                         detail.PriorApprove,
			PreviousSupplier:                     detail.PreviousSupplier,
			SupplierParkSupply:                   detail.SupplierParkSupply,
			PackageNumber:                        detail.PackageNumber,
			BillingPlanNumber:                    detail.BillingPlanNumber,
			NetOrderValue2:                       detail.NetOrderValue2,
			Statistics:                           detail.Statistics,
			TopPosition:                          detail.TopPosition,
			LatestDate:                           detail.LatestDate,
			Supplier:                             detail.Supplier,
			SubcontractedSupplier:                detail.SubcontractedSupplier,
			MatConfig:                            detail.MatConfig,
			MaterialCategory:                     detail.MaterialCategory,
			ShippingClass:                        detail.ShippingClass,
			PlaceDelivery:                        detail.PlaceDelivery,
			ProductSupply:                        detail.ProductSupply,
			Address2:                             detail.Address2,
			DeliveryAddressClass:                 detail.DeliveryAddressClass,
			InternalObjectNumber:                 detail.InternalObjectNumber,
			SelfBilling:                          detail.SelfBilling,
			LiquidBased:                          detail.LiquidBased,
			DateModificationTransmitted:          detail.DateModificationTransmitted,
			TransmissionTime:                     detail.TransmissionTime,
			NextTransmissionNumber:               detail.NextTransmissionNumber,
			TradePromotion:                       detail.TradePromotion,
			AllocationTable:                      detail.AllocationTable,
			Position2:                            detail.Position2,
			Points:                               detail.Points,
			PointUnit:                            detail.PointUnit,
			Season:                               detail.Season,
			SeasonYear:                           detail.SeasonYear,
			SettlementGroup2:                     detail.SettlementGroup2,
			SettlementGroup3:                     detail.SettlementGroup3,
			LiquidPosterior:                      detail.LiquidPosterior,
			AssetLedger:                          detail.AssetLedger,
			MinDurationTime:                      detail.MinDurationTime,
			OfferPetition:                        detail.OfferPetition,
			Position3:                            detail.Position3,
			ConfigurationOrigin:                  detail.ConfigurationOrigin,
			UseQuotaRegulation:                   detail.UseQuotaRegulation,
			TransferIndicator:                    detail.TransferIndicator,
			OrderRequest:                         detail.OrderRequest,
			PosRequestOrder:                      detail.PosRequestOrder,
			MaterialType:                         detail.MaterialType,
			SubPositionType:                      detail.SubPositionType,
			SubPositions:                         detail.SubPositions,
			Subtotal1:                            detail.Subtotal1,
			Subtotal2:                            detail.Subtotal2,
			Subtotal3:                            detail.Subtotal3,
			Subtotal4:                            detail.Subtotal4,
			Subtotal5:                            detail.Subtotal5,
			Subtotal6:                            detail.Subtotal6,
			TreatmentKey:                         detail.TreatmentKey,
			QtyAccumMaxRelease:                   detail.QtyAccumMaxRelease,
			QtyAccumMaxReleaseFabr:               detail.QtyAccumMaxReleaseFabr,
			ReturnPosition:                       detail.ReturnPosition,
			RelayAssignedTable:                   detail.RelayAssignedTable,
			ReasonOrder:                          detail.ReasonOrder,
			ReturnDeliveryClass:                  detail.ReturnDeliveryClass,
			MaterialCarryingGroup:                detail.MaterialCarryingGroup,
			KindBonus:                            detail.KindBonus,
			NcmCode:                              detail.NcmCode,
			MaterialUtilization:                  detail.MaterialUtilization,
			MaterialOrigin:                       detail.MaterialOrigin,
			OwnManufacturing:                     detail.OwnManufacturing,
			CfopTypeMaterial:                     detail.CfopTypeMaterial,
			DeliveryOrderCreationProfile:         detail.DeliveryOrderCreationProfile,
			NextOrderDeterminationDeliverySupply: detail.NextOrderDeterminationDeliverySupply,
			NextTransOrdEntrg:                    detail.NextTransOrdEntrg,
			SpecialStockValue:                    detail.SpecialStockValue,
			RappellingBase:                       detail.RappellingBase,
			InputExact:                           detail.InputExact,
			LoadingUnloadingPoint:                detail.LoadingUnloadingPoint,
			InflationIndex:                       detail.InflationIndex,
			InflationIndexDate:                   detail.InflationIndexDate,
			FabricPartsProfile:                   detail.FabricPartsProfile,
			FinalDelivery:                        detail.FinalDelivery,
			PartialPosDelivery:                   detail.PartialPosDelivery,
			UseMeasure:                           detail.UseMeasure,
			RoundingProfile:                      detail.RoundingProfile,
			StandardValuation:                    detail.StandardValuation,
			ModifiedConfiguration:                detail.ModifiedConfiguration,
			NoInvoicePosition:                    detail.NoInvoicePosition,
			ManufacturerPartNumber:               detail.ManufacturerPartNumber,
			Maker:                                detail.Maker,
			ExternalManufacturer:                 detail.ExternalManufacturer,
			ShipmentLock:                         detail.ShipmentLock,
			Applicant:                            detail.Applicant,
			TimeZone:                             detail.TimeZone,
			ExpirationIndicator:                  detail.ExpirationIndicator,
			VerificationInvoicesServices:         detail.VerificationInvoicesServices,
			NecArea:                              detail.NecArea,
			ConditionPositionInvoice:             detail.ConditionPositionInvoice,
			ExternalPlanning:                     detail.ExternalPlanning,
			TypeTransfer:                         detail.TypeTransfer,
			Grant:                                detail.Grant,
			FunctionalArea:                       detail.FunctionalArea,
			PositionStatus:                       detail.PositionStatus,
			IssuingWarehouse:                     detail.IssuingWarehouse,
			BudgetDocument:                       detail.BudgetDocument,
			DocumentPosition2:                    detail.DocumentPosition2,
			Element:                              detail.Element,
			CostCenter:                           detail.CostCenter,
			GeneralLedgerAccount:                 detail.GeneralLedgerAccount,
			SupplierAcceptance:                   detail.SupplierAcceptance,
			CommittedServiceBased:                detail.CommittedServiceBased,
			UrgentNeed:                           detail.UrgentNeed,
			NecessaryPriority:                    detail.NecessaryPriority,
			ReceptionPoint:                       detail.ReceptionPoint,
			CreationDifferenceInvoice:            detail.CreationDifferenceInvoice,
			RiskRelevance:                        detail.RiskRelevance,
			CreationDate:                         detail.CreationDate,
			CreationTime:                         detail.CreationTime,
			ValueChainCategory:                   detail.ValueChainCategory,
			ReasonForRejection:                   detail.ReasonRejection,
			CrmCustomerOrderNumber:               detail.CrmCustomerOrderNumber,
			CrmCustomerOrderItemNumber:           detail.CrmCustomerOrderItemNumber,
			CrmReferenceOrderNumber:              detail.CrmReferenceOrderNumber,
			CrmReferencePositionNumber:           detail.CrmReferencePositionNumber,
			CrmInvoiceRelevance:                  detail.CrmInvoiceRelevance,
			ModifiedSystemCategory:               detail.ModifiedSystemCategory,
			IssuerWarehouseStockType:             detail.IssuerWarehouseStockType,
			ControlType:                          detail.ControlType,
			TransferInputOrder:                   detail.TransferInputOrder,
			CauseCode:                            detail.CauseCode,
			AccumulateDivertedOrders:             detail.AccumulateDivertedOrders,
			QuantitySerialNumbers:                detail.QuantitySerialNumbers,
			ViewTotalBaseEWM:                     detail.ViewTotalBaseEWM,
			HierarchyNumber:                      detail.HierarchyNumber,
			ClassificationExternalNumber:         detail.ClassificationExternalNumber,
			ExternalHierarchyType:                detail.ExternalHierarchyType,
			RetentionPercentage:                  detail.RetentionPercentage,
			Advance:                              detail.Advance,
			AdvancePaymentPercentage:             detail.AdvancePaymentPercentage,
			AdvanceAmount:                        detail.AdvanceAmount,
			AdvancePaymentDueDate:                detail.AdvancePaymentDueDate,
			StoreReturn:                          detail.StoreReturn,
			DocumentNumberExternalDocument:       detail.DocumentNumberExternalDocument,
			ExternalPositionNumber:               detail.ExternalPositionNumber,
			LogicalSystem:                        detail.LogicalSystem,
			CentralOpenRequest:                   detail.CentralOpenRequest,
			CentralOpenorderResponsePosition:     detail.CentralOpenorderResponsePosition,
			MerchandiseCountCorrection:           detail.MerchandiseCountCorrection,
			ExternalDeliveryId:                   detail.ExternalDeliveryId,
			ExternalPos:                          detail.ExternalPos,
			MotBloqIdentifier:                    detail.MotBloqIdentifier,
			MotivBloqText:                        detail.MotivBloqText,
			AccountConsumptionOport:              detail.AccountConsumptionOport,
			FixedDateQuantity:                    detail.FixedDateQuantity,
			MechanicalOutputReference:            detail.MechanicalOutputReference,
			CompleteSupply:                       detail.CompleteSupply,
			IncotermsPlace1:                      detail.IncotermsPlace1,
			IncotermsPlace2:                      detail.IncotermsPlace2,
			IncotermLocation1:                    detail.IncotermLocation1,
			IncotermLocation2:                    detail.IncotermLocation2,
			DeviationDestiny:                     detail.DeviationDestiny,
			GoodsCode:                            detail.GoodsCode,
			IntrastatServiceCode:                 detail.IntrastatServiceCode,
			BorderCrossingValue:                  detail.BorderCrossingValue,
			ServiceProvider:                      detail.ServiceProvider,
			ProductTypeGroup:                     detail.ProductTypeGroup,
			Emhes:                                detail.Emhes,
			PriceModification:                    detail.PriceModification,
			OfferPetition2:                       detail.OfferPetition,
			PositionNumberRFQ:                    detail.PositionNumberRFQ,
			RenegotiationStatus:                  detail.RenegotiationStatus,
			SupplierVerificationStatus:           detail.SupplierVerificationStatus,
			ProductMarketStatus:                  detail.ProductMarketStatus,
			DangerousGoodsStatus:                 detail.DangerousGoodsStatus,
			SafetyDataSheetStatus:                detail.SafetyDataSheetStatus,
			Material2:                            detail.Material2,
			ConnectedSystemID:                    detail.ConnectedSystemID,
			ExpectedPositionValue:                detail.ExpectedPositionValue,
			ExternalReferenceID:                  detail.ExternalReferenceID,
			CodeAutomaticallyDetermined:          detail.CodeAutomaticallyDetermined,
			CodeReasonManual:                     detail.CodeReasonManual,
			IncentiveType:                        detail.IncentiveType,
			SubjectTaxSubstitution:               detail.SubjectTaxSubstitution,
			IncentiveId:                          detail.IncentiveId,
			OriginJurisdCode:                     detail.OriginJurisdCode,
			IncludesExtensibility:                detail.IncludesExtensibility,
			ExpectedValue:                        detail.ExpectedValue,
			GlobalLimit:                          detail.GlobalLimit,
			OpenPurchaseOrderLimit:               detail.OpenPurchaseOrderLimit,
			StartDate:                            detail.StartDate,
			EndDate:                              detail.EndDate,
			PercentageRate:                       detail.PercentageRate,
			WorkingTimeHours:                     detail.WorkingTimeHours,
			DataFilterValue:                      detail.DataFilterValue,
			UniqueProjectCode:                    detail.UniqueProjectCode,
			CompetitionIdentification:            detail.CompetitionIdentification,
			MonitoringMajorWorks:                 detail.MonitoringMajorWorks,
			BusinessTransaction:                  detail.BusinessTransaction,
			CustomerUsage:                        detail.CustomerUsage,
			UsagePurpose:                         detail.UsagePurpose,
			GeneratedPosition:                    detail.GeneratedPosition,
			FreeDependency:                       detail.FreeDependency,
			StructureCategory:                    detail.StructureCategory,
			InfoCode:                             detail.InfoCode,
			Budget:                               detail.Budget,
			EntryPeriod:                          detail.EntryPeriod,
			USGovernmentCamp:                     detail.USGovernmentCamp,
			RelevantIUID:                         detail.RelevantIUID,
			MaxRetailPriceRelevance:              detail.MaxRetailPriceRelevance,
			StockSegment:                         detail.StockSegment,
			NeedSegment:                          detail.NeedSegment,
			TransportationReferenceUuid:          detail.TransportationReferenceUuid,
			Location1:                            detail.Location1,
			Location2:                            detail.Location2,
			CharacteristicDesignation1:           detail.CharacteristicDesignation1,
			CharacteristicDesignation2:           detail.CharacteristicDesignation2,
			CharacteristicDesignation3:           detail.CharacteristicDesignation3,
			ShoppingReferralCenter:               detail.ShoppingReferralCenter,
			DetailNumber:                         detail.DetailNumber,
			Optionality:                          detail.Optionality,
			MaxIcValue:                           detail.MaxIcValue,
			PositionType2:                        detail.PositionType2,
			EffectiveValidity:                    detail.EffectiveValidity,
			Cash:                                 detail.Cash,
			OptionItem:                           detail.OptionItem,
			PostingCategoryDetails:               detail.PostingCategoryDetails,
			FasCodeHeader:                        detail.FasCodeHeader,
			ProgrammingDesk:                      detail.ProgrammingDesk,
			MixedProductNumber:                   detail.MixedProductNumber,
			Product:                              detail.Product,
			PostedDate:                           detail.PostedDate,
			Accounted:                            detail.Accounted,
			UmInvoice:                            detail.UmInvoice,
			AnnexingPackageKey:                   detail.AnnexingPackageKey,
			AnnexingPackageExtend:                detail.AnnexingPackageExtend,
			BaseDate:                             detail.BaseDate,
			AnnexingDateType:                     detail.AnnexingDateType,
			AnnexingStartDate:                    detail.AnnexingStartDate,
			DeviationPercentage:                  detail.DeviationPercentage,
			AnnexedIndicator:                     detail.AnnexedIndicator,
			LimitDate:                            detail.LimitDate,
			Numerator:                            detail.Numerator,
			NewBaseDate:                          detail.NewBaseDate,
			AccountantGeneralMethod:              detail.AccountantGeneralMethod,
			NegativeAnnexing:                     detail.NegativeAnnexing,
			PurchasingOrganization:               detail.PurchasingOrganization,
			KnownIndexIndicator:                  detail.KnownIndexIndicator,
			GlobalPositionNumber:                 detail.GlobalPositionNumber,
			OfferPositionNumber:                  detail.OfferPositionNumber,
			ModelIDCode:                          detail.ModelIDCode,
			OrderPriority:                        detail.OrderPriority,
			DeliveryPriority:                     detail.DeliveryPriority,
			AircraftRegistrationNumber:           detail.AircraftRegistrationNumber,
			Position1:                            detail.Position1,
			ConfirmationClass:                    detail.ConfirmationClass,
			DocumentDate:                         detail.DocumentDate,
			Quotation:                            detail.Quotation,
			MessageS1pnstat:                      detail.MessageS1pnstat,
			DoNotReplace:                         detail.DoNotReplace,
			DemandPriority1:                      detail.DemandPriority1,
			DemandPriority2:                      detail.DemandPriority2,
			ArunOrderPriority:                    detail.ArunOrderPriority,
			Subcontracting:                       detail.Subcontracting,
			ProfileSerialNumber:                  detail.ProfileSerialNumber,
			SpecialStock2:                        detail.SpecialStock2,
			ElementPEP:                           detail.ElementPEP,
			Customer2:                            detail.Customer2,
			CommercialDocument:                   detail.CommercialDocument,
			PositionSD:                           detail.PositionSD,
			StockOwner:                           detail.StockOwner,
			SeasonalYear:                         detail.SeasonYear,
			Season2:                              detail.Season2,
			Collection:                           detail.Collection,
			Issue:                                detail.Issue,
			StartDateATP:                         detail.StartDateATP,
			RelevantSVA:                          detail.RelevantSVA,
			Position4:                            detail.Position4,
			TransactionNumber:                    detail.TransactionNumber,
			PositionGroup:                        detail.PositionGroup,
			PositionNumber:                       detail.PositionNumber,
			OrderSchedulingStrategy:              detail.OrderSchedulingStrategy,
			MatrixRegistrationNumber:             detail.MatrixRegistrationNumber,
			PfmPartId:                            detail.PfmPartId,
			ConfirmedQuantity:                    detail.ConfirmedQuantity,
			HighQuantityRejection:                detail.HighQuantityRejection,
			DeviationProcessStatus:               detail.DeviationProcessStatus,
			SeasonIntegrityIndicator:             detail.SeasonIntegrityIndicator,
			ActivateOverride:                     detail.ActivateOverride,
			DischargePoint1:                      detail.DischargePoint1,
			DischargePoint2:                      detail.DischargePoint2,
			AddressNumber:                        detail.AddressNumber,
			CurrentNumber:                        detail.CurrentNumber,
			DuringRegistration:                   detail.DuringRegistration,
			Department:                           detail.Department,
			BudgetDocument2:                      detail.BudgetDocument2,
			DocumentPosition3:                    detail.DocumentPosition3,
			CommitmentDocument:                   detail.CommitmentDocument,
			CommitmentItem:                       detail.CommitmentItem,
			ElementWbs:                           detail.ElementWbs,
			PsstGroupingRule:                     detail.PsstGroupingRule,
			PsstGroup:                            detail.PsstGroup,
			ReferenceDocumentOrder:               detail.ReferenceDocumentOrder,
			ReferenceOrder:                       detail.ReferenceOrder,
			ReferencePartitionAction:             detail.ReferencePartitionAction,
			DistributionItemNumber:               detail.DistributionItemNumber,
			ReferencePosition:                    detail.ReferencePosition,
			OriginProfile:                        detail.OriginProfile,
			KeySourceSystem:                      detail.KeySourceSystem,
			TriggerIndicator:                     detail.TriggerIndicator,
			OrderListItemNumber:                  detail.OrderListItemNumber,
			PreferentialConsignment:              detail.PreferentialConsignment,
		})
	}

	response.HeaderOrders = responseHeader
	response.DetailOrders = responseDetail

	return response
}
