package order

import "encoding/xml"

type SoapResponseRecovery struct {
	XMLName   xml.Name             `xml:"Envelope"`
	XMLNsSoap string               `xml:"soap,attr"`
	XMLNsUrn  string               `xml:"xmlns:urn,attr"`
	Body      ResponseBodyRecovery `xml:"Body"`
}

type DataReturn struct {
	HeaderOrders HeaderOrders `xml:"PFE_EKKO>item"` //PFE_EKKO
	DetailOrders DetailOrders `xml:"PFE_EKPO>item"` //PFE_EKPO
}

type HeaderOrders []HeaderOrder
type DetailOrders []DetailOrder

type ResponseBodyRecovery struct {
	DataReturn DataReturn `xml:"ZP2PRFC_GUIA_REMISION_PEDIDOResponse"`
}

type HeaderOrder struct {
	Principal                           string  `xml:"MANDT"`
	PurchasingDocument                  string  `xml:"EBELN"`
	Society                             string  `xml:"BUKRS"`
	DescriptionSociety                  string  `xml:"BUTXT"`
	PurchasingDocumentType              string  `xml:"BSTYP"`
	PurchasingDocumentCI                string  `xml:"BSART"`
	ControlIndicator                    string  `xml:"BSAKZ"`
	EraseIndicator                      string  `xml:"LOEKZ"`
	Status                              string  `xml:"STATU"`
	CreationDate                        string  `xml:"AEDAT"`
	Author                              string  `xml:"ERNAM"`
	LastModification                    float64 `xml:"LASTCHANGEDATETIME"`
	PositionInterval                    string  `xml:"PINCR"`
	LastPosition                        string  `xml:"LPONR"`
	Supplier                            string  `xml:"LIFNR"`
	SupplierName                        string  `xml:"NAME1"`
	TypeNIF                             string  `xml:"TAXTYPE"`
	Nif                                 string  `xml:"TAXNUM"`
	LanguajeKey                         string  `xml:"SPRAS"`
	PaymentCondition                    string  `xml:"ZTERM"`
	Pay1                                float64 `xml:"ZBD1T"`
	Pay2                                float64 `xml:"ZBD2T"`
	Pay3                                float64 `xml:"ZBD3T"`
	Discount1                           float64 `xml:"ZBD1P"`
	Discount2                           float64 `xml:"ZBD2P"`
	PurchasingOrganization              string  `xml:"EKORG"`
	ShoppingGroup                       string  `xml:"EKGRP"`
	Currency                            string  `xml:"WAERS"`
	ExchangeRate                        float64 `xml:"WKURS"`
	FixedExchangeRate                   string  `xml:"KUFIX"`
	DocumentDate                        string  `xml:"BEDAT"`
	StartPeriodValidity                 string  `xml:"KDATB"`
	EndPeriodValidity                   string  `xml:"KDATE"`
	TenderDeadline                      string  `xml:"BWBDT"`
	OfferPeriod                         string  `xml:"ANGDT"`
	BindingTerm                         string  `xml:"BNDDT"`
	Warranty                            string  `xml:"GWLDT"`
	Tender                              string  `xml:"AUSNR"`
	Offer                               string  `xml:"ANGNR"`
	OfferDate                           string  `xml:"IHRAN"`
	Reference                           string  `xml:"IHREZ"`
	Seller                              string  `xml:"VERKF"`
	Phone                               string  `xml:"TELF1"`
	MerchandiseSupplier                 string  `xml:"LLIEF"`
	Customer                            string  `xml:"KUNNR"`
	ActivePurchasingDocument            string  `xml:"ACTIVE_ID"`
	FrameworkContract                   string  `xml:"KONNR"`
	NotUsed                             string  `xml:"ABGRU"`
	CompleteSupply                      string  `xml:"AUTLF"`
	MessageEM                           string  `xml:"WEAKT"`
	SupplyCenter                        string  `xml:"RESWK"`
	ReceivingProvider                   string  `xml:"LBLIF"`
	Incoterms1                          string  `xml:"INCO1"`
	Incoterms2                          string  `xml:"INCO2"`
	ExpectedValue                       float64 `xml:"KTWRT"`
	DistributionClassPurchasingDocument string  `xml:"DISTRIBUTIONTYPE"`
	Tender2                             string  `xml:"SUBMI"`
	DocumentConditionNumber             string  `xml:"KNUMV"`
	Scheme                              string  `xml:"KALSM"`
	Current                             string  `xml:"STAFO"`
	InvoiceIssuer                       string  `xml:"LIFRE"`
	ForeignTradeData                    string  `xml:"EXNUM"`
	OurReference                        string  `xml:"UNSEZ"`
	LogicalSystem                       string  `xml:"LOGSY"`
	SubpositionInterval                 string  `xml:"UPINC"`
	TemporaryConditions                 string  `xml:"STAKO"`
	LiberationGroup                     string  `xml:"FRGGR"`
	LiberationStrategy                  string  `xml:"FRGSX"`
	IndRelease                          string  `xml:"FRGKE"`
	ReleaseStatus                       string  `xml:"FRGZU"`
	RelevantRelease                     string  `xml:"FRGRL"`
	Country                             string  `xml:"LANDS"`
	DeliveryOrderDocument               string  `xml:"LPHIS"`
	Address                             string  `xml:"ADRNR"`
	CountryNIF                          string  `xml:"STCEG_L"`
	CommunityNIF                        string  `xml:"STCEG"`
	ReasonRejection                     string  `xml:"ABSGR"`
	DocumentNumber                      string  `xml:"ADDNR"`
	Type                                string  `xml:"KORNR"`
	Incomplete                          string  `xml:"MEMORY"`
	PurchasingProcessStatus             string  `xml:"PROCSTAT"`
	ProcessIndicator                    string  `xml:"PROCESS_INDICATOR"`
	TotalReleaseValue                   float64 `xml:"RLWRT"`
	ModificationStatus                  string  `xml:"CR_STAT"`
	Version                             string  `xml:"REVNO"`
	Scmproc                             string  `xml:"SCMPROC"`
	CauseCode                           string  `xml:"REASON_CODE"`
	IncompleteDate                      string  `xml:"MEMORYTYPE"`
	Retention                           string  `xml:"RETTP"`
	RetentionPercentage                 float64 `xml:"RETPC"`
	Advance                             string  `xml:"DPTYP"`
	AdvancePercentage                   float64 `xml:"DPPCT"`
	AdvanceAmount                       float64 `xml:"DPAMT"`
	AdvancePaymentDueDate               string  `xml:"DPDAT"`
	ProcessIdNumber                     string  `xml:"MSR_ID"`
	OrderHierachyPart                   string  `xml:"HIERARCHY_EXISTS"`
	GroupingID                          string  `xml:"GROUPING_ID"`
	SuperiorDocument                    string  `xml:"PARENT_ID"`
	ThresholdExchange                   string  `xml:"THRESHOLD_EXISTS"`
	LegalOrder                          string  `xml:"LEGAL_CONTRACT"`
	LegalOrderDescription               string  `xml:"DESCRIPTION"`
	LegarOrderDate                      string  `xml:"RELEASE_DATE"`
	ShippingClass                       string  `xml:"VSART"`
	PlaceDelivery                       string  `xml:"HANDOVERLOC"`
	ShippingCondition                   string  `xml:"SHIPCOND"`
	IncotermsVersion                    string  `xml:"INCOV"`
	IncotermsPlace                      string  `xml:"INCO2_L"`
	IncotermsPlace2                     string  `xml:"INCO3_L"`
	IncotermLocation1                   string  `xml:"INCO2_KEY"` //CAMBIE TIPO FLOAT64
	IncotermLocation2                   string  `xml:"INCO3_KEY"` //CAMBIE TIPO FLOAT64
	DeviationDestiny                    string  `xml:"INCO4_KEY"` //CAMBIE TIPO FLOAT64
	Currency2                           string  `xml:"GRWCU"`
	IntraRelevance                      string  `xml:"INTRA_REL"`
	IntraExclude                        string  `xml:"INTRA_EXCL"`
	TotalStatusProducts                 string  `xml:"TOTAL_STATUS_PCS"`
	TotalStatusMarket                   string  `xml:"TOTAL_STATUS_PMA"`
	TotalStatusDangerous                string  `xml:"TOTAL_STATUS_DG"`
	TotalStatusSecurity                 string  `xml:"TOTAL_STATUS_SDS"`
	OfferStartDate                      string  `xml:"QTN_ERLST_SUBMSN_DATE"`
	FollowDocumentCategory              string  `xml:"FOLLOWON_DOC_CAT"`
	FollowDocumentType                  string  `xml:"FOLLOWON_DOC_TYPE"`
	DummyOrder                          string  `xml:"DUMMY_EKKO_INCL_EEW_PS"`
	ExternarlSystem                     string  `xml:"EXTERNALSYSTEM"`
	ExternalReference                   string  `xml:"EXTERNALREFERENCEID"`
	ExternalReviewing                   float64 `xml:"EXT_REV_TMSTMP"`
	BusinessObjectiveAchieved           string  `xml:"ISEOPBLOCKED"`
	DocumentOld                         string  `xml:"ISAGED"`
	UniqueId                            string  `xml:"FORCE_ID"`
	Counter                             string  `xml:"FORCE_CNT"`
	TransferId                          string  `xml:"RELOC_ID"`
	TransferStageId                     string  `xml:"RELOC_SEQ_ID"`
	SourceLogicalSystem                 string  `xml:"SOURCE_LOGSYS"`
	TransactionNumber                   string  `xml:"FSH_TRANSACTION"`
	PositionGroup                       string  `xml:"FSH_ITEM_GROUP"`
	SvaLastItem                         string  `xml:"FSH_VAS_LAST_ITEM"`
	OrderScheduleChange                 string  `xml:"FSH_OS_STG_CHANGE"`
	TransportationSap                   string  `xml:"TMS_REF_UUID"`
	ConsideredPaymentDate               string  `xml:"_-DMBE_-PAYMENTDEEMED"`
	OperationNumber                     string  `xml:"_-DMBE_-DEALNUMBER"`
	RenewalPeriod                       string  `xml:"_-DMBE_-EVGIDRENEWAL"`
	CancellationPeriod                  string  `xml:"_-DMBE_-EVGIDCANCEL"`
	AnnexingPackageKey                  string  `xml:"ZAPCGK"`
	AnnexingPackageExtend               string  `xml:"APCGK_EXTEND"`
	BaseDate                            string  `xml:"ZBAS_DATE"`
	AnnexingDateType                    string  `xml:"ZADATTYP"`
	AnnexingStartDate                   string  `xml:"ZSTART_DAT"`
	DeviationPerecentage                float64 `xml:"Z_DEV"`
	AnnexedIndicator                    string  `xml:"ZINDANX"`
	LimitDate                           string  `xml:"ZLIMIT_DAT"`
	Numerator                           string  `xml:"NUMERATOR"`
	NewBaseDate                         string  `xml:"HASHCAL_BDAT"`
	AccountGeneralMethod                string  `xml:"HASHCAL"`
	NegativeAnnexing                    string  `xml:"NEGATIVE"`
	PurchasingOrganization2             string  `xml:"HASHCAL_EXISTS"`
	IndexIndicator                      string  `xml:"KNOWN_INDEX"`
	Postat                              string  `xml:"POSTAT"`
	InterestIndicator                   string  `xml:"VZSKZ"`
	InstantStatus                       string  `xml:"FSH_SNST_STATUS"`
	ProcedureNumber                     string  `xml:"PROCE"`
	Adjustment                          string  `xml:"CONC"`
	ContractType                        string  `xml:"CONT"`
	LegalCompetence                     string  `xml:"COMP"`
	Miscellaneous                       string  `xml:"OUTR"`
	Despatch                            string  `xml:"DESP"`
	DespDate                            string  `xml:"DESP_DAT"`
	DespJob                             string  `xml:"DESP_CARGO"`
	Assesment                           string  `xml:"PARE"`
	AssesmentDate                       string  `xml:"PARE_DAT"`
	AssesmentJob                        string  `xml:"PARE_CARGO"`
	Contract                            string  `xml:"PFM_CONTRACT"`
	DocumentType                        string  `xml:"POHF_TYPE"`
	SameDelliveryDate                   string  `xml:"EQ_EINDT"`
	SameCenter                          string  `xml:"EQ_WERKS"`
	FixedDateCommercial                 string  `xml:"FIXPO"`
	ConsiderPurchasingGroup             string  `xml:"EKGRP_ALLOW"`
	ConsiderCenter                      string  `xml:"WERKS_ALLOW"`
	ConsiderOpenOrders                  string  `xml:"CONTRACT_ALLOW"`
	ConsiderPositionType                string  `xml:"PSTYP_ALLOW"`
	FixedOperation                      string  `xml:"FIXPO_ALLOW"`
	ConsiderBudget                      string  `xml:"KEY_ID_ALLOW"`
	ConsiderReleaveAssignment           string  `xml:"AUREL_ALLOW"`
	ConsiderDeliveryPeriod              string  `xml:"DELPER_ALLOW"`
	ConsiderDeliveryDate                string  `xml:"EINDT_ALLOW"`
	ConsiderSupllier                    string  `xml:"LTSNR_ALLOW"`
	VerificationLevel                   string  `xml:"OTB_LEVEL"`
	ConditionClass                      string  `xml:"OTB_COND_TYPE"`
	BudgetNumber                        string  `xml:"KEY_ID"`
	BudgetNecessary                     float64 `xml:"OTB_VALUE"`
	Coin                                string  `xml:"OTB_CURR"`
	BudgetReserved                      float64 `xml:"OTB_RES_VALUE"`
	BudgetSpecial                       float64 `xml:"OTB_SPEC_VALUE"`
	JustificationProfile                string  `xml:"SPR_RSN_PROFILE"`
	BudgetClass                         string  `xml:"BUDG_TYPE"`
	VerificationStatus                  string  `xml:"OTB_STATUS"`
	Justification                       string  `xml:"OTB_REASON"`
	CheckType                           string  `xml:"CHECK_TYPE"`
	OpenOrders                          string  `xml:"CON_OTB_REQ"`
	OpenOrdersLevel                     string  `xml:"CON_PREBOOK_LEV"`
	OpenOrdersDistribution              string  `xml:"CON_DISTR_LEV"`
}

type DetailOrder struct {
	Principal                            string  `xml:"MANDT"`
	PurchasingDocument                   string  `xml:"EBELN"`
	Position                             float64 `xml:"EBELP"`
	DispatchPoint                        string  `xml:"VSTEL"`
	ShippingPositionDescription          string  `xml:"VTEXT"`
	Batch                                string  `xml:"CHARG"`
	DocumentPosition                     string  `xml:"UNIQUEID"`
	EraseIndicator                       string  `xml:"LOEKZ"`
	Origin                               string  `xml:"STATU"`
	LastModification                     string  `xml:"AEDAT"`
	ShortText                            string  `xml:"TXZ01"`
	Material                             string  `xml:"MATNR"`
	ShortMaterialText                    string  `xml:"MAKTX"`
	ShortMaterialMatchcodes              string  `xml:"MAKTG"`
	ExtSunatCode                         string  `xml:"EXTWG"`
	MaterialBaseMeasurementUnit          string  `xml:"MEINS1"`
	MaterialE                            string  `xml:"EMATN"`
	Society                              string  `xml:"BUKRS"`
	CompanyName                          string  `xml:"BUTXT"`
	Center                               string  `xml:"WERKS"`
	NameCenter                           string  `xml:"NAME1"`
	Store                                string  `xml:"LGORT"`
	WarehouseName                        string  `xml:"LGOBE"`
	NeedNumber                           string  `xml:"BEDNR"`
	ItemGroup                            string  `xml:"MATKL"`
	PurchasingInformation                string  `xml:"INFNR"`
	SupplierNumber                       string  `xml:"IDNLF"`
	PlannedQuantity                      string  `xml:"KTMNG"`
	OrderQuantity                        string  `xml:"MENGE"`
	OrderedUnitMeasure                   string  `xml:"MEINS"`
	UmAskingPrice                        string  `xml:"BPRME"`
	QuantityConversion1                  float64 `xml:"BPUMZ"`
	QuantityConversion2                  float64 `xml:"BPUMN"`
	Corresponds                          float64 `xml:"UMREZ"`
	Denominator                          float64 `xml:"UMREN"`
	NetAskingPrice                       float64 `xml:"NETPR"`
	BaseQuantity                         float64 `xml:"PEINH"`
	NetOrderValue                        float64 `xml:"NETWR"`
	GrossOrderedValue                    float64 `xml:"BRTWR"`
	OfferPeriod                          string  `xml:"AGDAT"`
	EmTreatmentTime                      float64 `xml:"WEBAZ"`
	TaxIndicator                         string  `xml:"MWSKZ"`
	BeginningTaxRateValidity             string  `xml:"TXDAT_FROM"`
	TaxDate                              string  `xml:"TXDAT"`
	Country                              string  `xml:"TAX_COUNTRY"`
	SettlementGroup1                     string  `xml:"BONUS"`
	StockType                            string  `xml:"INSMK"`
	ActInfo                              string  `xml:"SPINF"`
	PricePrinting                        string  `xml:"PRSDR"`
	EstimatedPrice                       string  `xml:"SCHPR"`
	NumberClaims                         float64 `xml:"MAHNZ"`
	FirstClaim                           float64 `xml:"MAHN1"`
	SecondClaim                          float64 `xml:"MAHN2"`
	ThirdClaim                           float64 `xml:"MAHN3"`
	TolExcSupply                         float64 `xml:"UEBTO"`
	ExcessSupply                         string  `xml:"UEBTK"`
	TolerateSupplyFaults                 float64 `xml:"UNTTO"`
	ValuationClass                       string  `xml:"BWTAR"`
	ValuationType                        string  `xml:"BWTTY"`
	RejectionIndicator                   string  `xml:"ABSKZ"`
	OfferCharacteristics                 string  `xml:"AGMEM"`
	CompleteDelivery                     string  `xml:"ELIKZ"`
	FinalBill                            string  `xml:"EREKZ"`
	PositionType                         string  `xml:"PSTYP"`
	AllocationType                       string  `xml:"KNTTP"`
	Consumption                          string  `xml:"KZVBR"`
	DistributionIndustry                 string  `xml:"VRTKZ"`
	PartialInvoice                       string  `xml:"TWRKZ"`
	GoodsEntry                           string  `xml:"WEPOS"`
	NotValued                            string  `xml:"WEUNB"`
	ReceiptInvoices                      string  `xml:"REPOS"`
	BaseVerification                     string  `xml:"WEBRE"`
	ConfirmationRequired                 string  `xml:"KZABS"`
	OrderConfirmation                    string  `xml:"LABNR"`
	FrameworkContract                    string  `xml:"KONNR"`
	PostContractSup                      string  `xml:"KTPNR"`
	ArrangedDate                         string  `xml:"ABDAT"`
	CaConcert                            float64 `xml:"ABFTZ"`
	FixationPeriod1                      float64 `xml:"ETFZ1"`
	FixationPeriod2                      float64 `xml:"ETFZ2"`
	NecessaryPlanningObligations         string  `xml:"KZSTU"`
	ExclusionIndicator                   string  `xml:"NOTKZ"`
	BaseMeasurementUnit                  string  `xml:"LMEIN"`
	ShippingRules                        string  `xml:"EVERS"`
	FrameContrPrev                       float64 `xml:"ZWERT"`
	NonDeductible                        float64 `xml:"NAVNW"`
	QuantityStandOrderDelivery           float64 `xml:"ABMNG"`
	PriceDate                            string  `xml:"PRDAT"`
	PurchaseDocumentType                 string  `xml:"BSTYP"`
	EffectiveValue                       float64 `xml:"EFFWR"`
	CommittedRelease                     string  `xml:"XOBLR"`
	Customer                             string  `xml:"KUNNR"`
	Address                              string  `xml:"ADRNR"`
	ConditionGroup                       string  `xml:"EKKOL"`
	WithoutDiscount                      string  `xml:"SKTOF"`
	Status                               string  `xml:"STAFO"`
	PreliminaryDeliveryTime              float64 `xml:"PLIFZ"`
	NetWeight                            float64 `xml:"NTGEW"`
	WeightUnit                           string  `xml:"GEWEI"`
	TaxResidence                         string  `xml:"TXJCD"`
	RelevantImpression                   string  `xml:"ETDRK"`
	SpecialStock                         string  `xml:"SOBKZ"`
	SettlementReserve                    string  `xml:"ARSNR"`
	LiquidReserve                        string  `xml:"ARSPS"`
	Unmodifiable                         string  `xml:"INSNC"`
	QmControlKey                         string  `xml:"SSQSS"`
	CertificateType                      string  `xml:"ZGTYP"`
	EanCode                              string  `xml:"EAN11"`
	ConfirmationControl                  string  `xml:"BSTAE"`
	ReviewStatus                         string  `xml:"REVLV"`
	Money                                string  `xml:"GEBER"`
	ManagementCenter                     string  `xml:"FISTL"`
	BudgetPost                           string  `xml:"FIPOS"`
	DivisionNotifiedPartner              string  `xml:"KO_GSBER"`
	SupposedDivisionInterlocutor         string  `xml:"KO_PARGB"`
	ProfitCenter                         string  `xml:"KO_PRCTR"`
	Interlocutor                         string  `xml:"KO_PPRCTR"`
	PriceDateControl                     string  `xml:"MEPRF"`
	GrossWeight                          float64 `xml:"BRGEW"`
	Volume                               float64 `xml:"VOLUM"`
	VolumeUnit                           string  `xml:"VOLEH"`
	Incoterms1                           string  `xml:"INCO1"`
	Incoterms2                           string  `xml:"INCO2"`
	PriorApprove                         string  `xml:"VORAB"`
	PreviousSupplier                     string  `xml:"KOLIF"`
	SupplierParkSupply                   string  `xml:"LTSNR"`
	PackageNumber                        string  `xml:"PACKNO"`
	BillingPlanNumber                    string  `xml:"FPLNR"`
	NetOrderValue2                       float64 `xml:"GNETWR"`
	Statistics                           string  `xml:"STAPO"`
	TopPosition                          string  `xml:"UEBPO"`
	LatestDate                           string  `xml:"LEWED"`
	Supplier                             string  `xml:"EMLIF"`
	SubcontractedSupplier                string  `xml:"LBLKZ"`
	MatConfig                            string  `xml:"SATNR"`
	MaterialCategory                     string  `xml:"ATTYP"`
	ShippingClass                        string  `xml:"VSART"`
	PlaceDelivery                        string  `xml:"HANDOVERLOC"`
	ProductSupply                        string  `xml:"KANBA"`
	Address2                             string  `xml:"ADRN2"`
	DeliveryAddressClass                 string  `xml:"DELIVERY_ADDRESS_TYPE"`
	InternalObjectNumber                 string  `xml:"CUOBJ"`
	SelfBilling                          string  `xml:"XERSY"`
	LiquidBased                          string  `xml:"EILDT"`
	DateModificationTransmitted          string  `xml:"DRDAT"`
	TransmissionTime                     string  `xml:"DRUHR"`
	NextTransmissionNumber               string  `xml:"DRUNR"`
	TradePromotion                       string  `xml:"AKTNR"`
	AllocationTable                      string  `xml:"ABELN"`
	Position2                            string  `xml:"ABELP"`
	Points                               float64 `xml:"ANZPU"`
	PointUnit                            string  `xml:"PUNEI"`
	Season                               string  `xml:"SAISO"`
	SeasonYear                           string  `xml:"SAISJ"`
	SettlementGroup2                     string  `xml:"EBON2"`
	SettlementGroup3                     string  `xml:"EBON3"`
	LiquidPosterior                      string  `xml:"EBONF"`
	AssetLedger                          string  `xml:"MLMAA"`
	MinDurationTime                      float64 `xml:"MHDRZ"`
	OfferPetition                        string  `xml:"ANFNR"`
	Position3                            string  `xml:"ANFPS"`
	ConfigurationOrigin                  string  `xml:"KZKFG"`
	UseQuotaRegulation                   string  `xml:"USEQU"`
	TransferIndicator                    string  `xml:"UMSOK"`
	OrderRequest                         string  `xml:"BANFN"`
	PosRequestOrder                      string  `xml:"BNFPO"`
	MaterialType                         string  `xml:"MTART"`
	SubPositionType                      string  `xml:"UPTYP"`
	SubPositions                         string  `xml:"UPVOR"`
	Subtotal1                            float64 `xml:"KZWI1"`
	Subtotal2                            float64 `xml:"KZWI2"`
	Subtotal3                            float64 `xml:"KZWI3"`
	Subtotal4                            float64 `xml:"KZWI4"`
	Subtotal5                            float64 `xml:"KZWI5"`
	Subtotal6                            float64 `xml:"KZWI6"`
	TreatmentKey                         string  `xml:"SIKGR"`
	QtyAccumMaxRelease                   float64 `xml:"MFZHI"`
	QtyAccumMaxReleaseFabr               float64 `xml:"FFZHI"`
	ReturnPosition                       string  `xml:"RETPO"`
	RelayAssignedTable                   string  `xml:"AUREL"`
	ReasonOrder                          string  `xml:"BSGRU"`
	ReturnDeliveryClass                  string  `xml:"LFRET"`
	MaterialCarryingGroup                string  `xml:"MFRGR"`
	KindBonus                            string  `xml:"NRFHG"`
	NcmCode                              string  `xml:"J_1BNBM"`
	MaterialUtilization                  string  `xml:"J_1BMATUSE"`
	MaterialOrigin                       string  `xml:"J_1BMATORG"`
	OwnManufacturing                     string  `xml:"J_1BOWNPRO"`
	CfopTypeMaterial                     string  `xml:"J_1BINDUST"`
	DeliveryOrderCreationProfile         string  `xml:"ABUEB"`
	NextOrderDeterminationDeliverySupply string  `xml:"NLABD"`
	NextTransOrdEntrg                    string  `xml:"NFABD"`
	SpecialStockValue                    string  `xml:"KZBWS"`
	RappellingBase                       float64 `xml:"BONBA"`
	InputExact                           string  `xml:"FABKZ"`
	LoadingUnloadingPoint                string  `xml:"LOADINGPOINT"`
	InflationIndex                       string  `xml:"J_1AINDXP"`
	InflationIndexDate                   string  `xml:"J_1AIDATEP"`
	FabricPartsProfile                   string  `xml:"MPROF"`
	FinalDelivery                        string  `xml:"EGLKZ"`
	PartialPosDelivery                   string  `xml:"KZTLF"`
	UseMeasure                           string  `xml:"KZFME"`
	RoundingProfile                      string  `xml:"RDPRF"`
	StandardValuation                    string  `xml:"TECHS"`
	ModifiedConfiguration                string  `xml:"CHG_SRV"`
	NoInvoicePosition                    string  `xml:"CHG_FPLNR"`
	ManufacturerPartNumber               string  `xml:"MFRPN"`
	Maker                                string  `xml:"MFRNR"`
	ExternalManufacturer                 string  `xml:"EMNFR"`
	ShipmentLock                         string  `xml:"NOVET"`
	Applicant                            string  `xml:"AFNAM"`
	TimeZone                             string  `xml:"TZONRC"`
	ExpirationIndicator                  string  `xml:"IPRKZ"`
	VerificationInvoicesServices         string  `xml:"LEBRE"`
	NecArea                              string  `xml:"BERID"`
	ConditionPositionInvoice             string  `xml:"XCONDITIONS"`
	ExternalPlanning                     string  `xml:"APOMS"`
	TypeTransfer                         string  `xml:"CCOMP"`
	Grant                                string  `xml:"GRANT_NBR"`
	FunctionalArea                       string  `xml:"FKBER"`
	PositionStatus                       string  `xml:"STATUS"`
	IssuingWarehouse                     string  `xml:"RESLO"`
	BudgetDocument                       string  `xml:"KBLNR"`
	DocumentPosition2                    string  `xml:"KBLPOS"`
	Element                              string  `xml:"PS_PSP_PNR"`
	CostCenter                           string  `xml:"KOSTL"`
	GeneralLedgerAccount                 string  `xml:"SAKTO"`
	SupplierAcceptance                   string  `xml:"WEORA"`
	CommittedServiceBased                string  `xml:"SRV_BAS_COM"`
	UrgentNeed                           string  `xml:"PRIO_URG"`
	NecessaryPriority                    string  `xml:"PRIO_REQ"`
	ReceptionPoint                       string  `xml:"EMPST"`
	CreationDifferenceInvoice            string  `xml:"DIFF_INVOICE"`
	RiskRelevance                        string  `xml:"TRMRISK_RELEVANT"`
	CreationDate                         string  `xml:"CREATIONDATE"`
	CreationTime                         string  `xml:"CREATIONTIME"`
	ValueChainCategory                   string  `xml:"VCM_CHAIN_CATEGORY"`
	ReasonRejection                      string  `xml:"SPE_ABGRU"`
	CrmCustomerOrderNumber               string  `xml:"SPE_CRM_SO"`
	CrmCustomerOrderItemNumber           string  `xml:"SPE_CRM_SO_ITEM"`
	CrmReferenceOrderNumber              string  `xml:"SPE_CRM_REF_SO"`
	CrmReferencePositionNumber           string  `xml:"SPE_CRM_REF_ITEM"`
	CrmInvoiceRelevance                  string  `xml:"SPE_CRM_FKREL"`
	ModifiedSystemCategory               string  `xml:"SPE_CHNG_SYS"`
	IssuerWarehouseStockType             string  `xml:"SPE_INSMK_SRC"`
	ControlType                          string  `xml:"SPE_CQ_CTRLTYPE"`
	TransferInputOrder                   string  `xml:"SPE_CQ_NOCQ"`
	CauseCode                            string  `xml:"REASON_CODE"`
	AccumulateDivertedOrders             float64 `xml:"CQU_SAR"`
	QuantitySerialNumbers                int     `xml:"ANZSN"`
	ViewTotalBaseEWM                     string  `xml:"SPE_EWM_DTC"`
	HierarchyNumber                      string  `xml:"EXLIN"`
	ClassificationExternalNumber         string  `xml:"EXSNR"`
	ExternalHierarchyType                string  `xml:"EHTYP"`
	RetentionPercentage                  float64 `xml:"RETPC"`
	Advance                              string  `xml:"DPTYP"`
	AdvancePaymentPercentage             float64 `xml:"DPPCT"`
	AdvanceAmount                        float64 `xml:"DPAMT"`
	AdvancePaymentDueDate                string  `xml:"DPDAT"`
	StoreReturn                          string  `xml:"FLS_RSTO"`
	DocumentNumberExternalDocument       string  `xml:"EXT_RFX_NUMBER"`
	ExternalPositionNumber               string  `xml:"EXT_RFX_ITEM"`
	LogicalSystem                        string  `xml:"EXT_RFX_SYSTEM"`
	CentralOpenRequest                   string  `xml:"SRM_CONTRACT_ID"`
	CentralOpenorderResponsePosition     string  `xml:"SRM_CONTRACT_ITM"`
	MerchandiseCountCorrection           string  `xml:"GOODS_COUNT_CORRECTION"`
	ExternalDeliveryId                   string  `xml:"LIFEX"`
	ExternalPos                          string  `xml:"LIFEXPOS"`
	MotBloqIdentifier                    string  `xml:"BLK_REASON_ID"`
	MotivBloqText                        string  `xml:"BLK_REASON_TXT"`
	AccountConsumptionOport              string  `xml:"ITCONS"`
	FixedDateQuantity                    string  `xml:"FIXMG"`
	MechanicalOutputReference            string  `xml:"WABWE"`
	CompleteSupply                       string  `xml:"CMPL_DLV_ITM"`
	IncotermsPlace1                      string  `xml:"INCO2_L"`
	IncotermsPlace2                      string  `xml:"INCO3_L"`
	IncotermLocation1                    string  `xml:"INCO2_KEY"` //CAMBIE EL TIPO DE DATO FLOAT54
	IncotermLocation2                    string  `xml:"INCO3_KEY"` //CAMBIE EL TIPO DE DATO FLOAT54
	DeviationDestiny                     string  `xml:"INCO4_KEY"`
	GoodsCode                            string  `xml:"STAWN"`
	IntrastatServiceCode                 string  `xml:"ISVCO"`
	BorderCrossingValue                  float64 `xml:"GRWRT"`
	ServiceProvider                      string  `xml:"SERVICEPERFORMER"`
	ProductTypeGroup                     string  `xml:"PRODUCTTYPE"`
	Emhes                                string  `xml:"GR_BY_SES"`
	PriceModification                    string  `xml:"PRICE_CHANGE_IN_SES_ALLOWED"`
	OfferPetition2                       string  `xml:"REQUESTFORQUOTATION"`
	PositionNumberRFQ                    string  `xml:"REQUESTFORQUOTATIONITEM"`
	RenegotiationStatus                  string  `xml:"RENEGOTIATION_STATUS"`
	SupplierVerificationStatus           string  `xml:"STATUS_PCS"`
	ProductMarketStatus                  string  `xml:"STATUS_PMA"`
	DangerousGoodsStatus                 string  `xml:"STATUS_DG"`
	SafetyDataSheetStatus                string  `xml:"STATUS_SDS"`
	Material2                            string  `xml:"EXTMATERIALFORPURG"`
	ConnectedSystemID                    string  `xml:"PROCMT_HUB_SOURCE_SYSTEM"`
	ExpectedPositionValue                float64 `xml:"TARGET_VALUE"`
	ExternalReferenceID                  string  `xml:"EXTERNALREFERENCEID"`
	CodeAutomaticallyDetermined          string  `xml:"TC_AUT_DET"`
	CodeReasonManual                     string  `xml:"MANUAL_TC_REASON"`
	IncentiveType                        string  `xml:"FISCAL_INCENTIVE"`
	SubjectTaxSubstitution               string  `xml:"TAX_SUBJECT_ST"`
	IncentiveId                          string  `xml:"FISCAL_INCENTIVE_ID"`
	OriginJurisdCode                     string  `xml:"SF_TXJCD"`
	IncludesExtensibility                string  `xml:"DUMMY_EKPO_INCL_EEW_PS"`
	ExpectedValue                        float64 `xml:"EXPECTED_VALUE"`
	GlobalLimit                          float64 `xml:"LIMIT_AMOUNT"`
	OpenPurchaseOrderLimit               string  `xml:"CONTRACT_FOR_LIMIT"`
	StartDate                            string  `xml:"ENH_DATE1"`
	EndDate                              string  `xml:"ENH_DATE2"`
	PercentageRate                       float64 `xml:"ENH_PERCENT"`
	WorkingTimeHours                     string  `xml:"ENH_NUMC1"`
	DataFilterValue                      string  `xml:"_DATAAGING"`
	UniqueProjectCode                    string  `xml:"CUPIT"`
	CompetitionIdentification            string  `xml:"CIGIT"`
	MonitoringMajorWorks                 string  `xml:"MGOIT"`
	BusinessTransaction                  string  `xml:"TXS_BUSINESS_TRANSACTION"`
	CustomerUsage                        string  `xml:"TXS_MATERIAL_USAGE"`
	UsagePurpose                         string  `xml:"TXS_USAGE_PURPOSE"`
	GeneratedPosition                    string  `xml:"_-BEV1_-NEGEN_ITEM"`
	FreeDependency                       string  `xml:"_-BEV1_-NEDEPFREE"`
	StructureCategory                    string  `xml:"_-BEV1_-NESTRUCCAT"`
	InfoCode                             string  `xml:"ADVCODE"`
	Budget                               string  `xml:"BUDGET_PD"`
	EntryPeriod                          string  `xml:"EXCPE"`
	USGovernmentCamp                     string  `xml:"FMFGUS_KEY"`
	RelevantIUID                         string  `xml:"IUID_RELEVANT"`
	MaxRetailPriceRelevance              string  `xml:"MRPIND"`
	StockSegment                         string  `xml:"SGT_SCAT"`
	NeedSegment                          string  `xml:"SGT_RCAT"`
	TransportationReferenceUuid          string  `xml:"TMS_REF_UUID"`
	Location1                            string  `xml:"TMS_SRC_LOC_KEY"` //cambie tipo de dato estaba con float
	Location2                            string  `xml:"TMS_DES_LOC_KEY"` //cambie tipo de dato estaba con float
	CharacteristicDesignation1           string  `xml:"WRF_CHARSTC1"`
	CharacteristicDesignation2           string  `xml:"WRF_CHARSTC2"`
	CharacteristicDesignation3           string  `xml:"WRF_CHARSTC3"`
	ShoppingReferralCenter               string  `xml:"REFSITE"`
	DetailNumber                         string  `xml:"_-DMBE_-OPTIONALITYKEY"`
	Optionality                          string  `xml:"_-DMBE_-OPTIONALITYFOR"`
	MaxIcValue                           string  `xml:"_-DMBE_-CIMAX2"`
	PositionType2                        string  `xml:"-DMBE_-ITEM_TYPE"`
	EffectiveValidity                    string  `xml:"_-DMBE_-EFFECTIVEDATEFROM"`
	Cash                                 string  `xml:"_-DMBE_-EFFECTIVEDATETO"`
	OptionItem                           string  `xml:"_-DMBE_-OPTIONOF"`
	PostingCategoryDetails               string  `xml:"_-DMBE_-ACCOUNTING_TYPE"`
	FasCodeHeader                        string  `xml:"_-DMBE_-FAS_CODE"`
	ProgrammingDesk                      string  `xml:"_-DMBE_-SCHEDULING_DESK"`
	MixedProductNumber                   string  `xml:"_-DMBE_-COMPONENTFOR"`
	Product                              string  `xml:"_-DMBE_-MIXEDPRODUCT"`
	PostedDate                           string  `xml:"_-DMBE_-POSTEDDATE"`
	Accounted                            string  `xml:"_-DMBE_-DEAL_POSTED"`
	UmInvoice                            string  `xml:"_-DMBE_-INVOICEUOM"`
	AnnexingPackageKey                   string  `xml:"ZAPCGK"`
	AnnexingPackageExtend                string  `xml:"APCGK_EXTEND"`
	BaseDate                             string  `xml:"ZBAS_DATE"`
	AnnexingDateType                     string  `xml:"ZADATTYP"`
	AnnexingStartDate                    string  `xml:"ZSTART_DAT"`
	DeviationPercentage                  float64 `xml:"Z_DEV"`
	AnnexedIndicator                     string  `xml:"ZINDANX"`
	LimitDate                            string  `xml:"ZLIMIT_DAT"`
	Numerator                            string  `xml:"NUMERATOR"`
	NewBaseDate                          string  `xml:"HASHCAL_BDAT"`
	AccountantGeneralMethod              string  `xml:"HASHCAL"`
	NegativeAnnexing                     string  `xml:"NEGATIVE"`
	PurchasingOrganization               string  `xml:"HASHCAL_EXISTS"`
	KnownIndexIndicator                  string  `xml:"KNOWN_INDEX"`
	GlobalPositionNumber                 string  `xml:"_-SAPMP_-GPOSE"`
	OfferPositionNumber                  string  `xml:"ANGPN"`
	ModelIDCode                          string  `xml:"ADMOI"`
	OrderPriority                        string  `xml:"ADPRI"`
	DeliveryPriority                     string  `xml:"LPRIO"`
	AircraftRegistrationNumber           string  `xml:"ADACN"`
	Position1                            string  `xml:"AFPNR"`
	ConfirmationClass                    string  `xml:"BSARK"`
	DocumentDate                         string  `xml:"AUDAT"`
	Quotation                            string  `xml:"ANGNR"`
	MessageS1pnstat                      string  `xml:"PNSTAT"`
	DoNotReplace                         string  `xml:"ADDNS"`
	DemandPriority1                      string  `xml:"ASSIGNMENT_PRIORITY"`
	DemandPriority2                      string  `xml:"ARUN_GROUP_PRIO"`
	ArunOrderPriority                    int     `xml:"ARUN_ORDER_PRIO"`
	Subcontracting                       string  `xml:"SERRU"`
	ProfileSerialNumber                  string  `xml:"SERNP"`
	SpecialStock2                        string  `xml:"DISUB_SOBKZ"`
	ElementPEP                           string  `xml:"DISUB_PSPNR"`
	Customer2                            string  `xml:"DISUB_KUNNR"`
	CommercialDocument                   string  `xml:"DISUB_VBELN"`
	PositionSD                           string  `xml:"DISUB_POSNR"`
	StockOwner                           string  `xml:"DISUB_OWNER"`
	SeasonalYear                         string  `xml:"FSH_SEASON_YEAR"`
	Season2                              string  `xml:"FSH_SEASON"`
	Collection                           string  `xml:"FSH_COLLECTION"`
	Issue                                string  `xml:"FSH_THEME"`
	StartDateATP                         string  `xml:"FSH_ATP_DATE"`
	RelevantSVA                          string  `xml:"FSH_VAS_REL"`
	Position4                            string  `xml:"FSH_VAS_PRNT_ID"`
	TransactionNumber                    string  `xml:"FSH_TRANSACTION"`
	PositionGroup                        string  `xml:"FSH_ITEM_GROUP"`
	PositionNumber                       string  `xml:"FSH_ITEM"`
	OrderSchedulingStrategy              string  `xml:"FSH_SS"`
	MatrixRegistrationNumber             string  `xml:"FSH_GRID_COND_REC"`
	PfmPartId                            string  `xml:"FSH_PSM_PFM_SPLIT"`
	ConfirmedQuantity                    float64 `xml:"CNFM_QTY"`
	HighQuantityRejection                string  `xml:"FSH_PQR_UEPOS"`
	DeviationProcessStatus               string  `xml:"RFM_DIVERSION"`
	SeasonIntegrityIndicator             string  `xml:"RFM_SCC_INDICATOR"`
	ActivateOverride                     string  `xml:"STPAC"`
	DischargePoint1                      string  `xml:"LGBZO"`
	DischargePoint2                      string  `xml:"LGBZO_B"`
	AddressNumber                        string  `xml:"ADDRNUM"`
	CurrentNumber                        string  `xml:"CONSNUM"`
	DuringRegistration                   string  `xml:"BORGR_MISS"`
	Department                           string  `xml:"DEP_ID"`
	BudgetDocument2                      string  `xml:"BELNR"`
	DocumentPosition3                    string  `xml:"KBLPOS_CAB"`
	CommitmentDocument                   string  `xml:"KBLNR_COMP"`
	CommitmentItem                       string  `xml:"KBLPOS_COMP"`
	ElementWbs                           string  `xml:"WBS_ELEMENT"`
	PsstGroupingRule                     string  `xml:"RFM_PSST_RULE"`
	PsstGroup                            string  `xml:"RFM_PSST_GROUP"`
	ReferenceDocumentOrder               string  `xml:"RFM_REF_DOC"`
	ReferenceOrder                       float64 `xml:"RFM_REF_ITEM"`
	ReferencePartitionAction             string  `xml:"RFM_REF_ACTION"`
	DistributionItemNumber               float64 `xml:"RFM_REF_SLITEM"`
	ReferencePosition                    float64 `xml:"REF_ITEM"`
	OriginProfile                        string  `xml:"SOURCE_ID"`
	KeySourceSystem                      string  `xml:"SOURCE_KEY"`
	TriggerIndicator                     string  `xml:"PUT_BACK"`
	OrderListItemNumber                  string  `xml:"POL_ID"`
	PreferentialConsignment              string  `xml:"CONS_ORDER"`
}
