package delivery

import "encoding/xml"

type SoapResponseRecovery struct {
	XMLName   xml.Name             `xml:"Envelope"`
	XMLNsSoap string               `xml:"soap,attr"`
	XMLNsUrn  string               `xml:"xmlns:urn,attr"`
	Body      ResponseBodyRecovery `xml:"Body"`
}

type DataReturn struct {
	HeaderDeliveries   HeaderDeliveries   `xml:"PFE_LIKP>item"`
	PositionDeliveries PositionDeliveries `xml:"PFE_LIPS>item"`
}

type HeaderDeliveries []HeaderDelivery
type PositionDeliveries []PositionDelivery

type HeaderDelivery struct {
	Principal                            string  `xml:"MANDT"`
	Delivery                             string  `xml:"VBELN"`
	Author                               string  `xml:"ERNAM"`
	Hour                                 string  `xml:"ERZET"`
	Created                              string  `xml:"ERDAT"`
	SalesArea                            string  `xml:"BZIRK"`
	DispatchPoint                        string  `xml:"VSTEL"`
	ShippingPositionDescription          string  `xml:"VTEXT"`
	SalesOrganization                    string  `xml:"VKORG"`
	DeliveryClass1                       string  `xml:"LFART"`
	CompleteSupply                       string  `xml:"AUTLF"`
	GroupingOrders                       string  `xml:"KZAZU"`
	MerchandiseMovementDate              string  `xml:"WADAT"`
	UploadDate                           string  `xml:"LDDAT"`
	TransportationPlanningDate           string  `xml:"TDDAT"`
	DateDelivery                         string  `xml:"LFDAT"`
	PickingDAte                          string  `xml:"KODAT"`
	UnloadingStation                     string  `xml:"ABLAD"`
	Incoterms1                           string  `xml:"INCO1"`
	Incoterms2                           string  `xml:"INCO2"`
	Export                               string  `xml:"EXPKZ"`
	Route                                string  `xml:"ROUTE"`
	InvoiceLock                          string  `xml:"FAKSK"`
	DeliveryLock                         string  `xml:"LIFSK"`
	SalesDocumentType                    string  `xml:"VBTYP"`
	FactoryCalendar                      string  `xml:"KNFAK"`
	TransportationMeansQualificat        string  `xml:"TPQUA"`
	TransportationMeansGroup             string  `xml:"TPGRP"`
	DeliveryPriority                     string  `xml:"LPRIO"`
	ShippingCondition                    string  `xml:"VSBED"`
	Customer                             string  `xml:"KUNNR"`
	SupplierName                         string  `xml:"NAME1"`
	PostalCode                           string  `xml:"PSTLZ"`
	Population                           string  `xml:"ORT01"`
	District                             string  `xml:"ORT02"`
	Region                               string  `xml:"REGIO"`
	Street                               string  `xml:"STRAS"`
	Applicant                            string  `xml:"KUNAG"`
	CustomerGroup                        string  `xml:"KDGRP"`
	WaitingTimeClass                     float64 `xml:"STZKL"`
	WaitingTimeSurcharge                 float64 `xml:"STZZU"`
	TotalWeigh                           float64 `xml:"BTGEW"`
	NetWeight                            float64 `xml:"NTGEW"`
	WeightUnit                           string  `xml:"GEWEI"`
	Volume                               float64 `xml:"VOLUM"`
	VolumeUnit                           string  `xml:"VOLEH"`
	NumberPackages                       string  `xml:"ANZPK"`
	LocationAvailable                    string  `xml:"BEROT"`
	DeliveryTime                         string  `xml:"LFUHR"`
	WeightGroup                          string  `xml:"GRULG"`
	ChargingStation                      string  `xml:"LSTEL"`
	TransportGroup                       string  `xml:"TRAGR"`
	InvoiceClassDelivery                 string  `xml:"FKARV"`
	InvoiceDate                          string  `xml:"FKDAT"`
	BillingDates                         string  `xml:"PERFK"`
	Route2                               string  `xml:"ROUTA"`
	Current                              string  `xml:"STAFO"`
	Scheme                               string  `xml:"KALSM"`
	DocumentConditionNumber1             string  `xml:"KNUMV"`
	DocumentCurrency                     string  `xml:"WAERK"`
	SalesOffice                          string  `xml:"VKBUR"`
	TimeTratamExpedic                    float64 `xml:"VBEAK"`
	GroupingCriterion                    string  `xml:"ZUKRL"`
	OriginalDocument                     string  `xml:"VERUR"`
	CommunicationNumber                  string  `xml:"COMMN"`
	StatisticalCurrency                  string  `xml:"STWAE"`
	EstablishedExchangeRate              float64 `xml:"STCUR"`
	ForeignTradeDataNumber               string  `xml:"EXNUM"`
	ModifiedBy                           string  `xml:"AENAM"`
	CreationDate                         string  `xml:"AEDAT"`
	WarehouseNumber                      string  `xml:"LGNUM"`
	DeliveryIdWarehouseNumber            string  `xml:"LISPL"`
	VciSalesOrganization                 string  `xml:"VKOIV"`
	DistributionChannel                  string  `xml:"VTWIV"`
	InternalSector                       string  `xml:"SPAIV"`
	InternalBillingDateA                 string  `xml:"FKAIV"`
	InternalBillingDateO                 string  `xml:"PIOIV"`
	InternalBillingDateD                 string  `xml:"FKDIV"`
	InternalBillingCustomer              string  `xml:"KUNIV"`
	CreditControlArea                    string  `xml:"KKBER"`
	CreditAccount                        string  `xml:"KNKLI"`
	CustomerCreditGroup                  string  `xml:"GRUPP"`
	ResponsibleTeam                      string  `xml:"SBGRP"`
	RiskClass                            string  `xml:"CTLPC"`
	Currency                             string  `xml:"CMWAE"`
	FreeCreditValue                      float64 `xml:"AMTBL"`
	Waybill                              string  `xml:"BOLNR"`
	Supplier                             string  `xml:"LIFNR"`
	TypeNif                              string  `xml:"TAXTYPE"`
	Nif                                  string  `xml:"TAXNUM"`
	TypeTransport                        string  `xml:"TRATY"`
	MeansTransportIdentifier             string  `xml:"TRAID"`
	ReleaseDate                          string  `xml:"CMFRE"`
	NextDate                             string  `xml:"CMNGV"`
	MerchandiseVoucher                   string  `xml:"XABLN"`
	DocumentDate                         string  `xml:"BLDAT"`
	ActualMerchandiseMovementDate        string  `xml:"WADAT_IST"`
	TransportBlockageReason              string  `xml:"TRSPG"`
	TransportSystemId                    string  `xml:"TPSID"`
	ExternalDeliveryIdentification       string  `xml:"LIFEX"`
	Order1                               string  `xml:"TERNR"`
	SearchScheme                         string  `xml:"KALSM_CH"`
	CorrectiveDelivery                   string  `xml:"KLIEF"`
	Scheme2                              string  `xml:"KALSP"`
	DocumentConditionNumber2             string  `xml:"KNUMP"`
	NetOrderValue                        float64 `xml:"NETWR"`
	ItineraryPlan                        string  `xml:"AULWE"`
	Enter                                string  `xml:"WERKS"`
	FinancialDocumentNumber              string  `xml:"LCNUM"`
	GuaranteeScheme                      string  `xml:"ABSSC"`
	PickingTime                          string  `xml:"KOUHR"`
	TransportationPlanningTime           string  `xml:"TDUHR"`
	ChargingTime                         string  `xml:"LDUHR"`
	GoodsDepartureTime1                  string  `xml:"WAUHR"`
	DockWarehouseNumber                  string  `xml:"LGTOR"`
	LayoutArea                           string  `xml:"LGBZO"`
	LetterCreditDocument1                string  `xml:"AKWAE"`
	ExchangeCreditDocument               float64 `xml:"AKKUR"`
	AmortizationDegree                   float64 `xml:"AKPRZ"`
	DangerousGoods                       string  `xml:"PROLI"`
	Reference                            string  `xml:"XBLNR"`
	ProgramControl                       string  `xml:"HANDLE"`
	AvailSafeSecurity                    string  `xml:"TSEGFL"`
	Model                                string  `xml:"TSEGTP"`
	SupplyLocation                       string  `xml:"TZONIS"`
	TimeZone1                            string  `xml:"TZONRC"`
	ContainsDangerousGoods               string  `xml:"CONT_DG"`
	OriginalSystem                       string  `xml:"VERURSYS"`
	MerchandiseMovementIndicator         string  `xml:"KZWAB"`
	TransactionCode                      string  `xml:"TCODE"`
	ShippingClass                        string  `xml:"VSART"`
	Conveyance1                          string  `xml:"TRMTYP"`
	SpecialManagementIndicator           string  `xml:"SDABW"`
	GlCompanyNumber                      string  `xml:"VBUND"`
	OpenValFormat                        string  `xml:"XWOFF"`
	DirectOtCreation                     string  `xml:"DIRTA"`
	ProductionSupplyArea                 string  `xml:"PRVBE"`
	DeliveryClass2                       string  `xml:"FOLAR"`
	DeliveryReceiptDate                  string  `xml:"PODAT"`
	DeliveryReceiptTime                  string  `xml:"POTIM"`
	PosPredSystem                        int     `xml:"VGANZ"`
	Middle                               string  `xml:"IMWRK"`
	DocumentDeletionIndicator            string  `xml:"SPE_LOEKZ"`
	LocationSequence                     string  `xml:"SPE_LOC_SEQ"`
	DeliveryConfirmationStatus           string  `xml:"SPE_ACC_APP_STS"`
	TransportInformationStatus           string  `xml:"SPE_SHP_INF_STS"`
	CanceledReturnDelivery               string  `xml:"SPE_RET_CANC"`
	GoodsDepartureTime2                  string  `xml:"SPE_WAUHR_IST"`
	TimeZone2                            string  `xml:"SPE_WAZONE_IST"`
	WarehouseStatus1                     string  `xml:"SPE_REV_VLSTK"`
	LogisticsExecutionScene              string  `xml:"SPE_LE_SCENARIO"`
	OriginalSystemCategory               string  `xml:"SPE_ORIG_SYS"`
	ModifiedSystemCategory               string  `xml:"SPE_CHNG_SYS"`
	GeographicRoute                      string  `xml:"SPE_GEOROUTE"`
	RouteModification                    string  `xml:"SPE_GEOROUTEIND"`
	TransportModification                string  `xml:"SPE_CARRIER_IND"`
	CirculationMerchandise               string  `xml:"SPE_GTS_REL"`
	SapGtsCode                           string  `xml:"SPE_GTS_RT_CDE"`
	TimeframeRelease                     float64 `xml:"SPE_REL_TMSTMP"`
	MeasurementUnitSystems               string  `xml:"SPE_UNIT_SYSTEM"`
	InvoiceBefore                        string  `xml:"SPE_INV_BFR_GI"`
	StatusQuality                        string  `xml:"SPE_QI_STATUS"`
	IndicatorDeviation                   string  `xml:"SPE_RED_IND"`
	CustodyStatus                        string  `xml:"SAKES"`
	ExternalIdentifier                   string  `xml:"SPE_LIFEX_TYPE"`
	Conveyance2                          string  `xml:"SPE_TTYPE"`
	ProNumber                            string  `xml:"SPE_PRO_NUMBER"`
	LetterCreditDocument2                string  `xml:"LOC_GUID"`
	BillingIndicationEwm                 string  `xml:"SPE_BILLING_IND"`
	PrintProfile                         string  `xml:"PRINTER_PROFILE"`
	ReturnExtensionManagement            string  `xml:"MSR_ACTIVE"`
	LogDocument                          string  `xml:"PRTNR"`
	WarehouseModification                string  `xml:"STGE_LOC_CHANGE"`
	Controlkey                           string  `xml:"TM_CTRL_KEY"`
	PartitionLauncher                    string  `xml:"DLV_SPLIT_INITIA"`
	DeliveryVersion                      string  `xml:"DLV_VERSION"`
	DataFilterValue                      string  `xml:"_DATAAGING"`
	PreliminaryDocumentType              string  `xml:"GTS_VORPA"`
	PreliminaryDocumentNumber            string  `xml:"GTS_VORNU"`
	TransportMode                        string  `xml:"GTS_EXPVZ"`
	PortAirport                          string  `xml:"GTS_PORTI"`
	BorderTransportationMode             string  `xml:"ITM_EXPVZ"`
	CountryMeansTransportationBorder     string  `xml:"ITM_STGBE"`
	TransfrontMediaId                    string  `xml:"ITM_KZGBE"`
	PropertyTransmissionReferrerId       string  `xml:"ITM_VYGID"`
	RiverTransportMode                   string  `xml:"ITM_IEVER"`
	CountryAverageNationalTransportation string  `xml:"ITM_STABE"`
	NationalTransportationId             string  `xml:"ITM_KZABE"`
	PlaceDelivery                        string  `xml:"HANDOVERLOC"`
	DeliverDate                          string  `xml:"HANDOVERDATE"`
	TransferTime                         string  `xml:"HANDOVERTIME"`
	PickupLocation                       string  `xml:"HANDOVERTZONE"`
	DeliveryStatus                       string  `xml:"BESTK"`
	MaximumValue                         string  `xml:"CMPSC"`
	PaymentConditions                    string  `xml:"CMPSD"`
	FinancialDocument                    string  `xml:"CMPSI"`
	CreditInsurance                      string  `xml:"CMPSJ"`
	PaymentCardStatus                    string  `xml:"CMPSK"`
	SapCreditManagement                  string  `xml:"CMPS_CM"`
	TechnicalErrorStatus                 string  `xml:"CMPS_TE"`
	CreditStatus                         string  `xml:"CMGST"`
	IntercompanyBillingStatus            string  `xml:"FKIVK"`
	StockTransferOrderStatus             string  `xml:"FKSTK"`
	GlobalStatus                         string  `xml:"GBSTK"`
	Hold                                 string  `xml:"HDALL"`
	HoldPosition                         string  `xml:"HDALS"`
	PickingConfirmation                  string  `xml:"KOQUK"`
	PickingStatus                        string  `xml:"KOSTK"`
	PickingStorage                       string  `xml:"KOSTK_WH"`
	ActivityStatus                       string  `xml:"LVSTK"`
	DeliveryReceiptStatus                string  `xml:"PDSTK"`
	PackagingStatus                      string  `xml:"PKSTK"`
	TemporaryDeliveryInformation         string  `xml:"SPE_TMPID"`
	OverallBillingStatus                 string  `xml:"SPSTG"`
	TransportationPlanningStatus         string  `xml:"TRSTA"`
	GeneralHeader                        string  `xml:"UVALL"`
	IncompleteArticles                   string  `xml:"UVALS"`
	InvoiceHeader                        string  `xml:"UVFAK"`
	InvoiceAllpositions                  string  `xml:"UVFAS"`
	PackagingHeader                      string  `xml:"UVPAK"`
	PackagingOptions                     string  `xml:"UVPAS"`
	EntryStock                           string  `xml:"UVPIK"`
	PositionsPicking                     string  `xml:"UVPIS"`
	DeliveryHeader                       string  `xml:"UVVLK"`
	DeliveryAll                          string  `xml:"UVVLS"`
	MovementHeader                       string  `xml:"UVWAK"`
	MovementMerchandise                  string  `xml:"UVWAS"`
	WarehouseHandling                    string  `xml:"VESTK"`
	WarehouseStatus2                     string  `xml:"VLSTK"`
	MovementStatus                       string  `xml:"WBSTK"`
	ReserveHeader1                       string  `xml:"UVK01"`
	ReserveHeader2                       string  `xml:"UVK02"`
	ReserveHeader3                       string  `xml:"UVK03"`
	ReserveHeader4                       string  `xml:"UVK04"`
	ReserveHeader5                       string  `xml:"UVK05"`
	TotalReservation1                    string  `xml:"UVS01"`
	TotalReservation2                    string  `xml:"UVS02"`
	TotalReservation3                    string  `xml:"UVS03"`
	TotalReservation4                    string  `xml:"UVS04"`
	TotalReservation5                    string  `xml:"UVS05"`
	TotalProductMarket                   string  `xml:"TOTAL_PCSTA"`
	TotalDangerousGoods                  string  `xml:"TOTAL_DGSTA"`
	TotalDataSheet                       string  `xml:"TOTAL_SDSSTA"`
	TotalConsumptionTax                  string  `xml:"TOTAL_ARC_STATUS"`
	InvoiceStatusBetweenCompanies        string  `xml:"ICO_FKIVK"`
	EmbargoStatus                        string  `xml:"TOTAL_EMCST"`
	InspectionStatus                     string  `xml:"TOTAL_SLCST"`
	LegalControlStatus                   string  `xml:"TOTAL_LCCST"`
	StatDnp                              string  `xml:"_-SAPMP_-LBASK"`
	IncotermsVersion                     string  `xml:"INCOV"`
	IncotermsPlace1                      string  `xml:"INCO2_L"`
	IncotermsPlace2                      string  `xml:"INCO3_L"`
	IncotermLocation1                    string  `xml:"INCO2_KEY"`
	IncotermLocation2                    string  `xml:"INCO3_KEY"`
	DeviationDestiny                     string  `xml:"INCO4_KEY"`
	ExtConsignmentNumber                 string  `xml:"OID_EXTBOL"`
	MiscellaneousDeliveries              string  `xml:"OID_MISCDL"`
	ExternalBusinessSystemId             string  `xml:"EXT_BUS_SYST_ID"`
	TransportStockSpecification          string  `xml:"SITKZ_DB"`
	RelevanceDeliveryReceipt             string  `xml:"TM_ADV_SHIP_RECV"`
	WarehouseExecution                   string  `xml:"TM_WHSE_EXEC"`
	WarehouseExecutionBlock              string  `xml:"TM_WHSE_BLOCK"`
	LegalControlLicenseIndicator         string  `xml:"LGLC_LIC_IND"`
	Timekeeper1                          float64 `xml:"CREATION_TS"`
	Timekeeper2                          float64 `xml:"CHANGED_TS"`
	CorrectionIndicator                  string  `xml:"CORR_IND"`
	DummyFunction                        string  `xml:"DUMMY_DELIVERY_INCL_EEW_PS"`
	LoadUnits                            string  `xml:"_-BEV1_-LULEINH"`
	CategoryNumber1                      float64 `xml:"_-BEV1_-RPFAESS"`
	CategoryNumber2                      float64 `xml:"_-BEV1_-RPKIST"`
	CategoryNumber3                      float64 `xml:"_-BEV1_-RPCONT"`
	CategoryNumber4                      float64 `xml:"_-BEV1_-RPSONST"`
	SequenceNumber                       string  `xml:"_-BEV1_-RPFLGNR"`
	CurrentNode                          string  `xml:"IDT_CUR_EVTLOC"`
	IndicatesArrivalDepartureNode1       string  `xml:"IDT_CUR_EVTQUA"`
	CurrentTimearker                     float64 `xml:"IDT_CUR_EVTTST"`
	CurrentBaseNode                      string  `xml:"IDT_CUR_ESTLOC"`
	CheckCheckOut                        string  `xml:"IDT_CUR_ESTQUA"`
	TimeEstimateMark                     float64 `xml:"IDT_CUR_ESTTST"`
	IndicatesEventTimeEstimate1          string  `xml:"IDT_CUR_WRKQUA"`
	PreviousNodeRouteTracking            string  `xml:"IDT_PRE_EVTLOC"`
	IndicatesArrivalDepartureNode2       string  `xml:"IDT_PRE_EVTQUA"`
	IndicatesPreviousTimeMarker          float64 `xml:"IDT_PRE_EVTTST"`
	InidcatePreviousBaseNode             string  `xml:"IDT_PRE_ESTLOC"`
	IndicatesCheckCheckOut               string  `xml:"IDT_PRE_ESTQUA"`
	IndicatesTimeEstimateMark            float64 `xml:"IDT_PRE_ESTTST"`
	IndicatesEventTimeEstimate2          string  `xml:"IDT_PRE_WRKQUA"`
	IndicatesCurrentBaseNode             string  `xml:"IDT_REF_ESTLOC"`
	IndicatesArrivalNode                 string  `xml:"IDT_REF_ESTQUA"`
	IndicatesEstimatedTime               float64 `xml:"IDT_REF_ESTTST"`
	IndicatesDegreeObligation            string  `xml:"IDT_FIRM_LFDAT"`
	IndicatesDocumentNumber              string  `xml:"IDT_DOCNUM"`
	InboundDeliveryGroup                 string  `xml:"BORGR_GRP"`
	ProductSupply                        string  `xml:"KBNKZ"`
	TransactionNumber                    string  `xml:"FSH_TRANSACTION"`
	SvaLastItem                          string  `xml:"FSH_VAS_LAST_ITEM"`
	SvaClientGroup                       string  `xml:"FSH_VAS_CG"`
	PsstGroup                            string  `xml:"RFM_PSST_GROUP"`
	ExternalActualDate                   float64 `xml:"EXT_ACT_DATE_TOCD"`
	ExternalPlanningDate                 float64 `xml:"EXT_PLAN_DATE_TOCD"`
	ExternalZoneDate                     string  `xml:"EXT_TZONE_TOCD"`
	InternalActualTdcDate                float64 `xml:"INT_ACT_DATE_TOCD"`
	InternalPlanningTdcDate              float64 `xml:"INT_PLAN_DATE_TOCD"`
	InternalZoneTdcDate                  string  `xml:"INT_TZONE_TOCD"`
	ReliefJit                            string  `xml:"JIT_RLVNT"`
	FreightOrder                         string  `xml:"ZZTOR_ID"`
	BpCarrier                            string  `xml:"ZZTSPID"`
	DriverName                           string  `xml:"ZZNAMEDRIVER"`
	DriverLicense                        string  `xml:"ZZLICDRIVER"`
	Plate1                               string  `xml:"ZZPLATENUMBER1"`
	Plate2                               string  `xml:"ZZPLATENUMBER2"`
	Plate3                               string  `xml:"ZZPLATENUMBER"`
}

type PositionDelivery struct {
	Principal                           string  `xml:"MANDT"`
	Delivery                            string  `xml:"VBELN"`
	Position1                           string  `xml:"POSNR"`
	OrderCode                           string  `xml:"TKNUM"`
	TransportDocumentType               string  `xml:"SHTYP"`
	BusinessName                        string  `xml:"TDLNR"`
	CompanyName                         string  `xml:"NAME1_T"`
	TypeNif                             string  `xml:"TAXTYPE"`
	Nif                                 string  `xml:"TAXNUM"`
	PositionType1                       string  `xml:"PSTYV"`
	Author                              string  `xml:"ERNAM"`
	Hour                                string  `xml:"ERZET"`
	CreateDay                           string  `xml:"ERDAT"`
	ItemCode                            string  `xml:"MATNR"`
	ShortMaterialText                   string  `xml:"MAKTX"`
	ShortMaterialMatchcodes             string  `xml:"MAKTG"`
	MaterialIntroduced                  string  `xml:"MATWA"`
	ExtSunatCode                        string  `xml:"EXTWG"`
	MaterialBaseMeasurementUnit         string  `xml:"MEINS1"`
	ItemGroup                           string  `xml:"MATKL"`
	Center                              string  `xml:"WERKS"`
	SupplierName                        string  `xml:"NAME1"`
	DistributorCode                     string  `xml:"BUKRS"`
	DescriptionDistributorCode          string  `xml:"BUTXT"`
	Store                               string  `xml:"LGORT"`
	WarehouseName                       string  `xml:"LGOBE"`
	Batch                               string  `xml:"CHARG"`
	SupplierLot                         string  `xml:"LICHN"`
	ClientItemCode                      string  `xml:"KDMAT"`
	ProductHierarchy                    string  `xml:"PRODH"`
	NodeCode                            string  `xml:"PRDH_UNI_BATDET_PARNT_NODID"`
	DeliveryQuantity1                   float64 `xml:"LFIMG"`
	OrderedUnitMeasure                  string  `xml:"MEINS"`
	SalesUnitMeasure                    string  `xml:"VRKME"`
	Counter1                            float64 `xml:"UMVKZ"`
	Denominator                         float64 `xml:"UMVKN"`
	NetWeight                           float64 `xml:"NTGEW"`
	GrossWeight                         float64 `xml:"BRGEW"`
	WeightUnit1                         string  `xml:"GEWEI"`
	Volume                              float64 `xml:"VOLUM"`
	VolumeUnit1                         string  `xml:"VOLEH"`
	PartialPosDelivery                  string  `xml:"KZTLF"`
	ExcessSupply                        string  `xml:"UEBTK"`
	TolExcSupply                        float64 `xml:"UEBTO"`
	TolerateSupplyFaults                float64 `xml:"UNTTO"`
	LotDivisionAllowed                  string  `xml:"CHSPL"`
	InvoiceLock                         string  `xml:"FAKSP"`
	MateiralDistributionDate            string  `xml:"MBDAT"`
	ActualAmountUma                     float64 `xml:"LGMNG"`
	PositionName                        string  `xml:"ARKTX"`
	Location1                           string  `xml:"LGPBE"`
	Cause                               string  `xml:"VBELV"`
	CausativePosition                   string  `xml:"POSNV"`
	SalesDocumentType                   string  `xml:"VBTYV"`
	PredecessorLogicalSystem            string  `xml:"VGSYS"`
	ModelDocument                       string  `xml:"VGBEL"`
	ModelPosition                       string  `xml:"VGPOS"`
	DocumentFlowUpdate                  string  `xml:"UPFLU"`
	TopPosition                         string  `xml:"UEPOS"`
	RelevantInvoice                     string  `xml:"FKREL"`
	BatchBillingVariant                 string  `xml:"BATCH_BILLING_VARIANT"`
	LoadGroup                           string  `xml:"LADGR"`
	TransportGroup                      string  `xml:"TRAGR"`
	PickingIndicator                    string  `xml:"KOMKZ"`
	WarehouseNumber                     string  `xml:"LGNUM"`
	DeliveryIdWarehouseNumber           string  `xml:"LISPL"`
	WarehouseType                       string  `xml:"LGTYP"`
	Location2                           string  `xml:"LGPLA"`
	ReviewSeparate                      string  `xml:"BWTEX"`
	DistributionType                    string  `xml:"ETTYP"`
	MovementClass1                      string  `xml:"BWART"`
	MovementClass2                      string  `xml:"BWLVS"`
	DynamicLocationIndex                string  `xml:"KZDLG"`
	NeedClass                           string  `xml:"BDART"`
	PlanningClass                       string  `xml:"PLART"`
	ItemCodeType                        string  `xml:"MTART"`
	BatchManagement1                    string  `xml:"XCHPF"`
	BatchManagement2                    string  `xml:"XCHAR"`
	PreviousDocumentCreated             string  `xml:"VGREF"`
	PositionType2                       string  `xml:"POSAR"`
	ValuationClass                      string  `xml:"BWTAR"`
	TotalNeed                           string  `xml:"SUMBD"`
	AvailabilityCheck1                  string  `xml:"MTVFP"`
	EanNumber                           string  `xml:"EANNR"`
	Division                            string  `xml:"GSBER"`
	SalesOffice                         string  `xml:"VKBUR"`
	SellerGroup                         string  `xml:"VKGRP"`
	DistributionChannel                 string  `xml:"VTWEG"`
	Sector                              string  `xml:"SPART"`
	DeliveryGroup                       string  `xml:"GRKOR"`
	FixedQuantity                       string  `xml:"FMENG"`
	MaximumPartialDeliveries            float64 `xml:"ANTLF"`
	FixedTreatmentTime                  float64 `xml:"VBEAF"`
	VariableProcessingTime              float64 `xml:"VBEAV"`
	Current                             string  `xml:"STAFO"`
	InternalCosts                       float64 `xml:"WAVWR"`
	Subtotal1                           float64 `xml:"KZWI1"`
	Subtotal2                           float64 `xml:"KZWI2"`
	Subtotal3                           float64 `xml:"KZWI3"`
	Subtotal4                           float64 `xml:"KZWI4"`
	Subtotal5                           float64 `xml:"KZWI5"`
	Subtotal6                           float64 `xml:"KZWI6"`
	SpecialStock                        string  `xml:"SOBKZ"`
	CreationDate                        string  `xml:"AEDAT"`
	EanCode                             string  `xml:"EAN11"`
	CustomerGroup1                      string  `xml:"KVGR1"`
	CustomerGroup2                      string  `xml:"KVGR2"`
	CustomerGroup3                      string  `xml:"KVGR3"`
	CustomerGroup4                      string  `xml:"KVGR4"`
	CustomerGroup5                      string  `xml:"KVGR5"`
	ItemCodeGroup1                      string  `xml:"MVGR1"`
	ItemCodeGroup2                      string  `xml:"MVGR2"`
	ItemCodeGroup3                      string  `xml:"MVGR3"`
	ItemCodeGroup4                      string  `xml:"MVGR4"`
	ItemCodeGroup5                      string  `xml:"MVGR5"`
	AssignmentIndicator                 string  `xml:"VPZUO"`
	PreviousDocumentType                string  `xml:"VGTYP"`
	CentralDocumentType                 string  `xml:"RFVGTYP"`
	CostCenter                          string  `xml:"KOSTL"`
	ControlledDistributorCode           string  `xml:"KOKRS"`
	PaObjectNumber                      string  `xml:"PAOBJNR"`
	ProfitCenter                        string  `xml:"PRCTR"`
	Element                             string  `xml:"PS_PSP_PNR"`
	Order                               string  `xml:"AUFNR"`
	PositionNumber1                     string  `xml:"POSNR_PP"`
	Operation                           string  `xml:"VORNR"`
	RecipientLocation                   string  `xml:"RECIPIENT_LOCATION_CODE"`
	OperationRouteSheetNumber           string  `xml:"AUFPL"`
	Counter2                            string  `xml:"APLZL"`
	CustomerOrder                       string  `xml:"KDAUF"`
	CustomerOrderPosition               string  `xml:"KDPOS"`
	PreplanningItemCode                 string  `xml:"VPMAT"`
	PreplanningCenter                   string  `xml:"VPWRK"`
	UmProductGroup                      string  `xml:"PRBME"`
	Conversion                          bool    `xml:"UMREF"`
	AllocationType                      string  `xml:"KNTTP"`
	Consumption                         string  `xml:"KZVBR"`
	BudgetPosition                      string  `xml:"FIPOS"`
	ManagementCenter                    string  `xml:"FISTL"`
	Money                               string  `xml:"GEBER"`
	PackagingControl                    string  `xml:"PCKPF"`
	NeedCategory                        string  `xml:"BEDAR_LF"`
	ActiveCreditFunction                string  `xml:"CMPNT"`
	AcumulatedBatchQuantity             float64 `xml:"KCMENG"`
	AccumulatedGrossWeight              float64 `xml:"KCBRGEW"`
	AccumulatedNetWeight                float64 `xml:"KCNTGEW"`
	AccumulatedVolume                   float64 `xml:"KCVOLUM"`
	LotTopPosition                      string  `xml:"UECHA"`
	Configuration                       string  `xml:"CUOBJ"`
	InternalObjectNumber                string  `xml:"CUOBJ_CH"`
	QuantitySerialNumbers               int     `xml:"ANZSN"`
	ProfileSerialNumber                 string  `xml:"SERAIL"`
	WeightUnit2                         string  `xml:"KCGEWEI"`
	VolumeUnit2                         string  `xml:"KCVOLEH"`
	SerialNumber                        string  `xml:"SERNR"`
	OrderInternalDelivery               string  `xml:"ABRLI"`
	DeliveryOrderClass                  string  `xml:"ABART"`
	Utilization                         string  `xml:"ABRVW"`
	InspectionLot                       string  `xml:"QPLOS"`
	PartialLot                          string  `xml:"QTLOS"`
	WithoutEmClient                     string  `xml:"NACHL"`
	MeItemCode                          string  `xml:"MAGRV"`
	HeaderObjectNumber                  string  `xml:"OBJKO"`
	ObjectPositionNumber                string  `xml:"OBJPO"`
	ModifyProject                       string  `xml:"AESKD"`
	Returns                             string  `xml:"SHKZG"`
	ActiveMaterialDetection             string  `xml:"PROSA"`
	PossUsage                           string  `xml:"UEPVW"`
	ReceptionPoint                      string  `xml:"EMPST"`
	Department                          string  `xml:"ABTNR"`
	Confirmation                        string  `xml:"KOQUI"`
	StatisticalDate                     string  `xml:"STADAT"`
	TradePromotion                      string  `xml:"AKTNR"`
	ConditionLotNumber                  string  `xml:"KNUMH_CH"`
	CustomsPreference                   string  `xml:"PREFE"`
	OperationComercial                  string  `xml:"EXART"`
	InternalClassNumber                 string  `xml:"CLINT"`
	ProposedQuantities                  string  `xml:"CHMVS"`
	AllocationTable                     string  `xml:"ABELN"`
	Position2                           string  `xml:"ABELP"`
	InternalFieldLfimg                  bool    `xml:"LFIMG_FLO"`
	InternalFieldLfgmng                 bool    `xml:"LGMNG_FLO"`
	InternalFieldKcmeng                 bool    `xml:"KCMENG_FLO"`
	EnvironmentalRelief                 string  `xml:"KZUMW"`
	ComponentQuantity                   float64 `xml:"KMPMG"`
	RelayAssignedTable                  string  `xml:"AUREL"`
	PriceUm                             float64 `xml:"KPEIN"`
	UnitMeasurement                     string  `xml:"KMEIN"`
	NetAskingPrice                      float64 `xml:"NETPR"`
	NetOrderValue                       float64 `xml:"NETWR"`
	StatisticalValues                   string  `xml:"KOWRR"`
	MovementIndicator                   string  `xml:"KZBEW"`
	ItemCodeCarryingGroup               string  `xml:"MFRGR"`
	PackagingAccumulatedLotPosition     string  `xml:"CHHPV"`
	GuaranteeForm                       string  `xml:"ABFOR"`
	Guaranteed                          bool    `xml:"ABGES"`
	TimeMadeAvailableMaterial           string  `xml:"MBUHR"`
	OpenOrderNumberValue                string  `xml:"WKTNR"`
	OpenOrderPosition                   string  `xml:"WKTPS"`
	Cfop                                string  `xml:"J_1BCFOP"`
	IcmsLaw                             string  `xml:"J_1BTAXLW1"`
	IpiLaw                              string  `xml:"J_1BTAXLW2"`
	TaxCode                             string  `xml:"J_1BTXSDC"`
	Situation                           string  `xml:"SITUA"`
	Booking1                            string  `xml:"RSNUM"`
	ReservationPositionNumber1          string  `xml:"RSPOS"`
	RegistrationClass                   string  `xml:"RSART"`
	SequenceNumber                      string  `xml:"KANNR"`
	UseMeasure1                         string  `xml:"KZFME"`
	MpIndicatorProfile                  string  `xml:"PROFL"`
	QuantityCumulativeBatch             float64 `xml:"KCMENGVME"`
	CumulativeBatchSplitQuantity        bool    `xml:"KCMENGVMEF"`
	SpecialStockValue                   string  `xml:"KZBWS"`
	DefinitionProject                   string  `xml:"PSPNR"`
	TakeSequenceGroup                   string  `xml:"EPRIO"`
	StockDeterminationRule              string  `xml:"RULES"`
	CurrentStockDetermination           string  `xml:"KZBEF"`
	FabricPartsProfile                  string  `xml:"MPROF"`
	ManufacturerPartNumber              string  `xml:"EMATN"`
	DischargePoint1                     string  `xml:"LGBZO"`
	ProgramControl                      string  `xml:"HANDLE"`
	OriginalPosition                    string  `xml:"VERURPOS"`
	ExternalPosition                    string  `xml:"LIFEXPOS"`
	AvailabilityCheck2                  string  `xml:"NOATP"`
	NotRelevantPicking                  string  `xml:"NOPCK"`
	WMReferenceMovementClass            string  `xml:"RBLVS"`
	NECArea                             string  `xml:"BERID"`
	StockDifferentiation1               string  `xml:"BESTQ"`
	StockDifferentiation2               string  `xml:"UMBSQ"`
	ReceivingItemCode                   string  `xml:"UMMAT"`
	ReceivingCenter                     string  `xml:"UMWRK"`
	ReceivingWarehouse                  string  `xml:"UMLGO"`
	ReceivingLot                        string  `xml:"UMCHA"`
	DestLotValueClass                   string  `xml:"UMBAR"`
	TransferIndicator                   string  `xml:"UMSOK"`
	SpecialStockNumber1                 string  `xml:"SONUM"`
	SpecialStockNumber2                 string  `xml:"USONU"`
	ChangeTypeCreditDocLetter           float64 `xml:"AKKUR"`
	CurrentQuantity                     string  `xml:"AKMNG"`
	ClassificationPositions             string  `xml:"VKGRU"`
	ReferenceAccountingIndicator        string  `xml:"SHKZG_UM"`
	StockType                           string  `xml:"INSMK"`
	BatchEntry                          string  `xml:"KZECH"`
	DestinationLocationDataCopied       string  `xml:"FLGWM"`
	MadeAvailable                       string  `xml:"BERKZ"`
	DeliveryItemStoreItem               string  `xml:"HUPOS"`
	NoMovementMerchandise               string  `xml:"NOWAB"`
	GeneralLedgerAccount                string  `xml:"KONTO"`
	FinalDeparture                      string  `xml:"KZEAR"`
	ManufacturingDate                   string  `xml:"HSDAT"`
	ExpiresDate                         string  `xml:"VFDAT"`
	CurrentPeriod                       string  `xml:"LFGJA"`
	ReferenceDocument                   string  `xml:"LFBNR"`
	ReferenceDocumentPosition           string  `xml:"LFPOS"`
	MovementReason                      string  `xml:"GRUND"`
	SubsequentMovement                  string  `xml:"FOBWA"`
	DeliveryType                        string  `xml:"DLVTP"`
	ForeignAmountLocal                  float64 `xml:"EXBWR"`
	QuantityUmpp                        float64 `xml:"BPMNG"`
	SaleValue                           float64 `xml:"EXVKW"`
	CreditPrice                         bool    `xml:"CMPRE_FLT"`
	AreIndicator                        string  `xml:"KZPOD"`
	NotRelevantSga                      string  `xml:"LFDEZ"`
	ConversionFactor                    bool    `xml:"UMREV"`
	PurchaseSaleDocument                string  `xml:"PODREL"`
	Transfer                            string  `xml:"KZUML"`
	FunctionalArea                      string  `xml:"FKBER"`
	Grant                               string  `xml:"GRANT_NBR"`
	UseMeasure2                         string  `xml:"KZWSO"`
	MerchandiseMovementControl          string  `xml:"GMCONTROL"`
	MerchandiseMovementControlIndicator string  `xml:"POSTING_CHANGE"`
	ElementTransfer                     string  `xml:"UM_PS_PSP_PNR"`
	CurrentNumber                       string  `xml:"PRE_VL_ETENS"`
	CompleteDelivery                    string  `xml:"SPE_GEN_ELIKZ"`
	IndustryProcessingEwm               string  `xml:"SPE_SCRAP_IND"`
	RmaNumber                           string  `xml:"SPE_AUTH_NUMBER"`
	InspectionResult                    string  `xml:"SPE_INSPOUT_GUID"`
	NextActivity                        string  `xml:"SPE_FOLLOW_UP"`
	EndValidityReturnsReceipts          float64 `xml:"SPE_EXP_DATE_EXT"`
	EndValidityInternal                 float64 `xml:"SPE_EXP_DATE_INT"`
	ClosedRmaNumber                     string  `xml:"SPE_AUTH_COMPLET"`
	DeliveryQuantity2                   float64 `xml:"ORMNG"`
	AtpTimekeeper                       float64 `xml:"SPE_ATP_TMSTMP"`
	OriginalSystemCategory              string  `xml:"SPE_ORIG_SYS"`
	AccumulatedQuantityDeliverySupplier float64 `xml:"SPE_LIEFFZ"`
	Middle                              string  `xml:"SPE_IMWRK"`
	ExternalProductIdentifier           string  `xml:"SPE_LIFEXPOS2"`
	StoreExceptionCode                  string  `xml:"SPE_EXCEPT_CODE"`
	RetentionAmountScrappingProcess     float64 `xml:"SPE_KEEP_QTY"`
	AlternativeProductNumber            string  `xml:"SPE_ALTERNATE"`
	ReplacementReason                   string  `xml:"SPE_MAT_SUBST"`
	Structure                           string  `xml:"SPE_STRUC"`
	Numerator                           float64 `xml:"SPE_APO_QNTYFAC"`
	Denomination                        float64 `xml:"SPE_APO_QNTYDIV"`
	CountryRegionOrigin                 string  `xml:"SPE_HERKL"`
	ReturnsDeliveryValidityIndicator    float64 `xml:"SPE_BXP_DATE_EXT"`
	ConfirmationDelivery                string  `xml:"SPE_VERSION"`
	ClosingContab                       string  `xml:"SPE_COMPL_MVT"`
	CofinsLaw                           string  `xml:"J_1BTAXLW4"`
	PsiLaw                              string  `xml:"J_1BTAXLW5"`
	IssLaw                              string  `xml:"J_1BTAXLW3"`
	Budget                              string  `xml:"BUDGET_PD"`
	ProductSupply                       string  `xml:"KBNKZ"`
	IncomeAccountingClass               string  `xml:"FARR_RELTYPE"`
	StockSpecification                  string  `xml:"SITKZ"`
	NeedSegment                         string  `xml:"SGT_RCAT"`
	StockSegment                        string  `xml:"SGT_SCAT"`
	Resource                            string  `xml:"RESOURCE_ID"`
	ReceivingResource                   string  `xml:"UMRESOURCE_ID"`
	FieldLogisticsIndustry              string  `xml:"FLPKZ"`
	LoadingUnloadingPoint               string  `xml:"LOADING_POINT"`
	SolutionOrder                       string  `xml:"SOLUTION_ORDER_ID"`
	PositionNumberDocument              string  `xml:"SOLUTION_ORDER_ITM_ID"`
	RegionOrigin                        string  `xml:"SPE_HERKR"`
	MerchandiseCode                     string  `xml:"ITM_COMCO"`
	MerchandiseDestination              string  `xml:"WEMPF"`
	TimekeeperCreation                  float64 `xml:"CREATION_TS"`
	TimekeeperChanged                   float64 `xml:"CHANGED_TS"`
	PickingQuantity1                    float64 `xml:"PIKMG_WH"`
	PickingQuantity2                    float64 `xml:"PIKMG_WH_BU"`
	DeliveryStatus                      string  `xml:"BESTA"`
	FinancialDocument                   string  `xml:"CMPPI"`
	CreditInsurance                     string  `xml:"CMPPJ"`
	InvoiceStatusBetweenCompanies1      string  `xml:"FKIVP"`
	DeliveryInvoiceStatus               string  `xml:"FKSTA"`
	GlobalStatus                        string  `xml:"GBSTA"`
	DeliveryPositionNotComplete         string  `xml:"HDALL"`
	ConfirmationPicking                 string  `xml:"KOQUA"`
	PickingStatus1                      string  `xml:"KOSTA"`
	GaActivityStatus                    string  `xml:"LVSTA"`
	DeliveryReceiptStatus               string  `xml:"PDSTA"`
	PackagingStatus                     string  `xml:"PKSTA"`
	Position3                           string  `xml:"UVALL"`
	InvoicePosition                     string  `xml:"UVFAK"`
	PackingPosition                     string  `xml:"UVPAK"`
	PickingStockEntry                   string  `xml:"UVPIK"`
	DeliveryPosition                    string  `xml:"UVVLK"`
	MovementPosition                    string  `xml:"UVWAK"`
	DecentralizedWarehouse              string  `xml:"VLSTP"`
	MovementStatus                      string  `xml:"WBSTA"`
	ReservePosition1                    string  `xml:"UVP01"`
	ReservePosition2                    string  `xml:"UVP02"`
	ReservePosition3                    string  `xml:"UVP03"`
	ReservePosition4                    string  `xml:"UVP04"`
	ReservePosition5                    string  `xml:"UVP05"`
	EmbargoStatus                       string  `xml:"EMCST"`
	VerificationStatus                  string  `xml:"SLCST"`
	LegalControlStatus                  string  `xml:"LCCST"`
	ProductMarketCapacityStatus         string  `xml:"PCSTA"`
	DangerousGoodsStatus                string  `xml:"DGSTA"`
	SafetyDataSheetStatus               string  `xml:"SDSSTA"`
	InvoiceStatusBetweenCompanies2      string  `xml:"ICO_FKIVP"`
	PickingStatus2                      string  `xml:"KOSTA_WH"`
	StatDnp                             string  `xml:"_-SAPMP_-LBASP"`
	ExciseTaxArcStatus                  string  `xml:"ARC_STATUS"`
	DataFilterValue                     string  `xml:"_DATAAGING"`
	QuantityDeliveredUmp                float64 `xml:"_-CWM_-LFIMG"`
	DeliveryMeasurementUnit             string  `xml:"_-CWM_-LFIME"`
	PickingQuantity                     float64 `xml:"_-CWM_-PIKMG"`
	ParallelPickingMeasurementUnit      string  `xml:"_-CWM_-PIKME"`
	IndicatedQuantity                   string  `xml:"_-CWM_-XENTER"`
	EntryOt                             string  `xml:"_-CWM_-XTAENTER"`
	AccumulatedCatchWeightQuantity      float64 `xml:"_-CWM_-KCMENG"`
	QuantityPostedUmp                   float64 `xml:"_-CWM_-EBUMG"`
	DummyFunction                       string  `xml:"DUMMY_DELITM_INCL_EEW_PS"`
	InternalReferenceDocumentype        string  `xml:"ICO_VGTYP"`
	InternalReferenceDocument           string  `xml:"ICO_VGBEL"`
	InternalReferenceDocumentPosition   string  `xml:"ICO_VGPOS"`
	InternalBillingClass                string  `xml:"ICO_FKAIV"`
	SalesOrganization                   string  `xml:"ICO_VKOIV"`
	BillingDate                         string  `xml:"ICO_PIOIV"`
	FactCompIntDate                     string  `xml:"ICO_FKDIV"`
	UniqueId16                          string  `xml:"VCM_CHAIN_UUID"`
	ValueChainCategory                  string  `xml:"VCM_CHAIN_CATEGORY"`
	Inverted                            string  `xml:"_-KJEDM_-INVERTED"`
	Cpa                                 string  `xml:"_-SAPMP_-LBA_NO"`
	ConversionFactorsIndicator          string  `xml:"_-SAPMP_-ALT_CONV"`
	DockWarehouseNumber                 string  `xml:"LGTOR"`
	SeasonalYear                        string  `xml:"FSH_SEASON_YEAR"`
	Season2                             string  `xml:"FSH_SEASON"`
	Collection                          string  `xml:"FSH_COLLECTION"`
	Issue                               string  `xml:"FSH_THEME"`
	CustomerGroup6                      string  `xml:"FSH_KVGR6"`
	CustomerGroup7                      string  `xml:"FSH_KVGR7"`
	CustomerGroup8                      string  `xml:"FSH_KVGR8"`
	CustomerGroup9                      string  `xml:"FSH_KVGR9"`
	CustomerGroup10                     string  `xml:"FSH_KVGR10"`
	RelevantSva                         string  `xml:"FSH_VAS_REL"`
	Position4                           string  `xml:"FSH_VAS_PRNT_ID"`
	TransactionNumber                   string  `xml:"FSH_TRANSACTION"`
	PositionGroup                       string  `xml:"FSH_ITEM_GROUP"`
	PositionNumber2                     string  `xml:"FSH_ITEM"`
	Booking2                            string  `xml:"FSH_RSNUM"`
	ReservationPositionNumber2          string  `xml:"FSH_RSPOS"`
	LotsCommonOrigin                    string  `xml:"MILL_UCDET"`
	PreferentialConsignment             string  `xml:"CONS_ORDER"`
	CharacteristicDesignation1          string  `xml:"WRF_CHARSTC1"`
	CharacteristicDesignation2          string  `xml:"WRF_CHARSTC2"`
	CharacteristicDesignation3          string  `xml:"WRF_CHARSTC3"`
	Reference                           string  `xml:"ZZXBLNR"`
}

type ResponseBodyRecovery struct {
	DataReturn DataReturn `xml:"ZP2PRFC_GUIA_REMISION_ENTREGAResponse"`
}
